// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/application/usecase/shop_usecase (interfaces: ShopOwnerVerifier)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/usecase/mock_shop_owner_verifier.go -package=usecase . ShopOwnerVerifier
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockShopOwnerVerifier is a mock of ShopOwnerVerifier interface.
type MockShopOwnerVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockShopOwnerVerifierMockRecorder
	isgomock struct{}
}

// MockShopOwnerVerifierMockRecorder is the mock recorder for MockShopOwnerVerifier.
type MockShopOwnerVerifierMockRecorder struct {
	mock *MockShopOwnerVerifier
}

// NewMockShopOwnerVerifier creates a new mock instance.
func NewMockShopOwnerVerifier(ctrl *gomock.Controller) *MockShopOwnerVerifier {
	mock := &MockShopOwnerVerifier{ctrl: ctrl}
	mock.recorder = &MockShopOwnerVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShopOwnerVerifier) EXPECT() *MockShopOwnerVerifierMockRecorder {
	return m.recorder
}

// IsOwner mocks base method.
func (m *MockShopOwnerVerifier) IsOwner(ctx context.Context, shopID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOwner", ctx, shopID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsOwner indicates an expected call of IsOwner.
func (mr *MockShopOwnerVerifierMockRecorder) IsOwner(ctx, shopID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOwner", reflect.TypeOf((*MockShopOwnerVerifier)(nil).IsOwner), ctx, shopID, userID)
}
