// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/infrastructure/payment (interfaces: Provider)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/usecase/mock_payment_provider.go -package=usecase Goshop/infrastructure/payment Provider
//

// Package usecase is a generated GoMock package.
package usecase

import (
	entity "Goshop/domain/entity"
	payment "Goshop/infrastructure/payment"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// CheckStatus mocks base method.
func (m *MockProvider) CheckStatus(ctx context.Context, providerRef string) (*payment.PaymentStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckStatus", ctx, providerRef)
	ret0, _ := ret[0].(*payment.PaymentStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckStatus indicates an expected call of CheckStatus.
func (mr *MockProviderMockRecorder) CheckStatus(ctx, providerRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckStatus", reflect.TypeOf((*MockProvider)(nil).CheckStatus), ctx, providerRef)
}

// Code mocks base method.
func (m *MockProvider) Code() entity.PaymentProvider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Code")
	ret0, _ := ret[0].(entity.PaymentProvider)
	return ret0
}

// Code indicates an expected call of Code.
func (mr *MockProviderMockRecorder) Code() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Code", reflect.TypeOf((*MockProvider)(nil).Code))
}

// InitiatePayment mocks base method.
func (m *MockProvider) InitiatePayment(ctx context.Context, req *payment.PaymentRequest) (*payment.PaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiatePayment", ctx, req)
	ret0, _ := ret[0].(*payment.PaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiatePayment indicates an expected call of InitiatePayment.
func (mr *MockProviderMockRecorder) InitiatePayment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiatePayment", reflect.TypeOf((*MockProvider)(nil).InitiatePayment), ctx, req)
}

// IsAvailable mocks base method.
func (m *MockProvider) IsAvailable(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAvailable", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAvailable indicates an expected call of IsAvailable.
func (mr *MockProviderMockRecorder) IsAvailable(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAvailable", reflect.TypeOf((*MockProvider)(nil).IsAvailable), ctx)
}

// Refund mocks base method.
func (m *MockProvider) Refund(ctx context.Context, providerRef string, amountCents int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refund", ctx, providerRef, amountCents)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refund indicates an expected call of Refund.
func (mr *MockProviderMockRecorder) Refund(ctx, providerRef, amountCents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refund", reflect.TypeOf((*MockProvider)(nil).Refund), ctx, providerRef, amountCents)
}

// ValidateWebhook mocks base method.
func (m *MockProvider) ValidateWebhook(ctx context.Context, payload []byte, signature string) (*payment.WebhookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateWebhook", ctx, payload, signature)
	ret0, _ := ret[0].(*payment.WebhookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateWebhook indicates an expected call of ValidateWebhook.
func (mr *MockProviderMockRecorder) ValidateWebhook(ctx, payload, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateWebhook", reflect.TypeOf((*MockProvider)(nil).ValidateWebhook), ctx, payload, signature)
}
