// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/infrastructure/payment (interfaces: ProviderCompletable)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/usecase/mock_provider_completable.go -package=usecase Goshop/infrastructure/payment ProviderCompletable
//

// Package usecase is a generated GoMock package.
package usecase

import (
	payment "Goshop/infrastructure/payment"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProviderCompletable is a mock of ProviderCompletable interface.
type MockProviderCompletable struct {
	ctrl     *gomock.Controller
	recorder *MockProviderCompletableMockRecorder
	isgomock struct{}
}

// MockProviderCompletableMockRecorder is the mock recorder for MockProviderCompletable.
type MockProviderCompletableMockRecorder struct {
	mock *MockProviderCompletable
}

// NewMockProviderCompletable creates a new mock instance.
func NewMockProviderCompletable(ctrl *gomock.Controller) *MockProviderCompletable {
	mock := &MockProviderCompletable{ctrl: ctrl}
	mock.recorder = &MockProviderCompletableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderCompletable) EXPECT() *MockProviderCompletableMockRecorder {
	return m.recorder
}

// CompletePayment mocks base method.
func (m *MockProviderCompletable) CompletePayment(ctx context.Context, paymentIntentID, operatorCode, customerMSISDN, otp string) (*payment.CompletePaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompletePayment", ctx, paymentIntentID, operatorCode, customerMSISDN, otp)
	ret0, _ := ret[0].(*payment.CompletePaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompletePayment indicates an expected call of CompletePayment.
func (mr *MockProviderCompletableMockRecorder) CompletePayment(ctx, paymentIntentID, operatorCode, customerMSISDN, otp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompletePayment", reflect.TypeOf((*MockProviderCompletable)(nil).CompletePayment), ctx, paymentIntentID, operatorCode, customerMSISDN, otp)
}
