// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/application/usecase/cod_usecase (interfaces: WalletDebiter)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/usecase/mock_wallet_debiter.go -package=usecase . WalletDebiter
//

// Package usecase is a generated GoMock package.
package usecase

import (
	walletusecase "Goshop/application/usecase/wallet_usecase"
	entity "Goshop/domain/entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWalletDebiter is a mock of WalletDebiter interface.
type MockWalletDebiter struct {
	ctrl     *gomock.Controller
	recorder *MockWalletDebiterMockRecorder
	isgomock struct{}
}

// MockWalletDebiterMockRecorder is the mock recorder for MockWalletDebiter.
type MockWalletDebiterMockRecorder struct {
	mock *MockWalletDebiter
}

// NewMockWalletDebiter creates a new mock instance.
func NewMockWalletDebiter(ctrl *gomock.Controller) *MockWalletDebiter {
	mock := &MockWalletDebiter{ctrl: ctrl}
	mock.recorder = &MockWalletDebiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletDebiter) EXPECT() *MockWalletDebiterMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockWalletDebiter) Execute(ctx context.Context, req *walletusecase.DebitWalletRequest) (*walletusecase.DebitWalletResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, req)
	ret0, _ := ret[0].(*walletusecase.DebitWalletResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockWalletDebiterMockRecorder) Execute(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockWalletDebiter)(nil).Execute), ctx, req)
}

// GetWallet mocks base method.
func (m *MockWalletDebiter) GetWallet(ctx context.Context, shopID string) (*entity.MerchantWallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWallet", ctx, shopID)
	ret0, _ := ret[0].(*entity.MerchantWallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWallet indicates an expected call of GetWallet.
func (mr *MockWalletDebiterMockRecorder) GetWallet(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWallet", reflect.TypeOf((*MockWalletDebiter)(nil).GetWallet), ctx, shopID)
}
