// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/application/usecase/withdrawal_usecase (interfaces: ShopPaymentSettingsRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/usecase/mock_shop_payment_settings.go -package=usecase . ShopPaymentSettingsRepository
//

// Package usecase is a generated GoMock package.
package usecase

import (
	entity "Goshop/domain/entity"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockShopPaymentSettingsRepository is a mock of ShopPaymentSettingsRepository interface.
type MockShopPaymentSettingsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShopPaymentSettingsRepositoryMockRecorder
	isgomock struct{}
}

// MockShopPaymentSettingsRepositoryMockRecorder is the mock recorder for MockShopPaymentSettingsRepository.
type MockShopPaymentSettingsRepositoryMockRecorder struct {
	mock *MockShopPaymentSettingsRepository
}

// NewMockShopPaymentSettingsRepository creates a new mock instance.
func NewMockShopPaymentSettingsRepository(ctrl *gomock.Controller) *MockShopPaymentSettingsRepository {
	mock := &MockShopPaymentSettingsRepository{ctrl: ctrl}
	mock.recorder = &MockShopPaymentSettingsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShopPaymentSettingsRepository) EXPECT() *MockShopPaymentSettingsRepositoryMockRecorder {
	return m.recorder
}

// GetPaymentSettings mocks base method.
func (m *MockShopPaymentSettingsRepository) GetPaymentSettings(ctx context.Context, shopID uuid.UUID) (*entity.ShopPaymentSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentSettings", ctx, shopID)
	ret0, _ := ret[0].(*entity.ShopPaymentSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentSettings indicates an expected call of GetPaymentSettings.
func (mr *MockShopPaymentSettingsRepositoryMockRecorder) GetPaymentSettings(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentSettings", reflect.TypeOf((*MockShopPaymentSettingsRepository)(nil).GetPaymentSettings), ctx, shopID)
}
