// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/application/usecase/payment_usecase (interfaces: PaymentRegistry)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/usecase/mock_payment_registry.go -package=usecase . PaymentRegistry
//

// Package usecase is a generated GoMock package.
package usecase

import (
	entity "Goshop/domain/entity"
	payment "Goshop/infrastructure/payment"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentRegistry is a mock of PaymentRegistry interface.
type MockPaymentRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRegistryMockRecorder
	isgomock struct{}
}

// MockPaymentRegistryMockRecorder is the mock recorder for MockPaymentRegistry.
type MockPaymentRegistryMockRecorder struct {
	mock *MockPaymentRegistry
}

// NewMockPaymentRegistry creates a new mock instance.
func NewMockPaymentRegistry(ctrl *gomock.Controller) *MockPaymentRegistry {
	mock := &MockPaymentRegistry{ctrl: ctrl}
	mock.recorder = &MockPaymentRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRegistry) EXPECT() *MockPaymentRegistryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPaymentRegistry) Get(providerCode entity.PaymentProvider) (payment.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", providerCode)
	ret0, _ := ret[0].(payment.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPaymentRegistryMockRecorder) Get(providerCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPaymentRegistry)(nil).Get), providerCode)
}

// GetAvailable mocks base method.
func (m *MockPaymentRegistry) GetAvailable(ctx context.Context, providerCode entity.PaymentProvider) (payment.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailable", ctx, providerCode)
	ret0, _ := ret[0].(payment.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailable indicates an expected call of GetAvailable.
func (mr *MockPaymentRegistryMockRecorder) GetAvailable(ctx, providerCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailable", reflect.TypeOf((*MockPaymentRegistry)(nil).GetAvailable), ctx, providerCode)
}
