// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/application/usecase/cod_usecase (interfaces: AccountFreezer)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/usecase/mock_account_freezer.go -package=usecase . AccountFreezer
//

// Package usecase is a generated GoMock package.
package usecase

import (
	walletusecase "Goshop/application/usecase/wallet_usecase"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAccountFreezer is a mock of AccountFreezer interface.
type MockAccountFreezer struct {
	ctrl     *gomock.Controller
	recorder *MockAccountFreezerMockRecorder
	isgomock struct{}
}

// MockAccountFreezerMockRecorder is the mock recorder for MockAccountFreezer.
type MockAccountFreezerMockRecorder struct {
	mock *MockAccountFreezer
}

// NewMockAccountFreezer creates a new mock instance.
func NewMockAccountFreezer(ctrl *gomock.Controller) *MockAccountFreezer {
	mock := &MockAccountFreezer{ctrl: ctrl}
	mock.recorder = &MockAccountFreezerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountFreezer) EXPECT() *MockAccountFreezerMockRecorder {
	return m.recorder
}

// FreezeForNegativeBalance mocks base method.
func (m *MockAccountFreezer) FreezeForNegativeBalance(ctx context.Context, shopID string, amountDueCents int64) (*walletusecase.FreezeAccountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FreezeForNegativeBalance", ctx, shopID, amountDueCents)
	ret0, _ := ret[0].(*walletusecase.FreezeAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FreezeForNegativeBalance indicates an expected call of FreezeForNegativeBalance.
func (mr *MockAccountFreezerMockRecorder) FreezeForNegativeBalance(ctx, shopID, amountDueCents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FreezeForNegativeBalance", reflect.TypeOf((*MockAccountFreezer)(nil).FreezeForNegativeBalance), ctx, shopID, amountDueCents)
}
