// application/metrics/metrics.go
package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
)

// ================================
// MÉTRIQUES AUTHENTIFICATION
// ================================

// Compteurs existants (déjà présents)
var (
	AuthLoginTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_auth_login_total",
		Help: "Total number of successful login attempts",
	})
	AuthLoginFailedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_auth_login_failed_total",
		Help: "Total number of failed login attempts",
	})
	AuthRegisterTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_auth_register_total",
		Help: "Total number of successful user registrations",
	})
)

// NOUVEAUX HISTOGRAMMES
var (
	// Durée des opérations d'authentification
	AuthLoginDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_auth_login_duration_seconds",
		Help:    "Duration of login operations in seconds",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10},
	})
	AuthRegisterDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_auth_register_duration_seconds",
		Help:    "Duration of user registration operations in seconds",
		Buckets: []float64{0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10, 20},
	})
	AuthProfileDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_auth_profile_duration_seconds",
		Help:    "Duration of profile retrieval operations in seconds",
		Buckets: []float64{0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1},
	})
)

// ================================
// MÉTRIQUES PRODUITS
// ================================

var (
	ProductsCreatedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_products_created_total",
		Help: "Total number of products created",
	})
)

var (
	ProductsCreateDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_products_create_duration_seconds",
		Help:    "Duration of product creation operations in seconds",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5},
	})
	ProductsGetDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_products_get_duration_seconds",
		Help:    "Duration of product retrieval operations in seconds",
		Buckets: []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5},
	})
	ProductsListDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_products_list_duration_seconds",
		Help:    "Duration of product listing operations in seconds",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10},
	})
)

// ================================
// MÉTRIQUES COMMANDES
// ================================

var (
	OrdersCreatedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_orders_created_total",
		Help: "Total number of orders created",
	})
	OrdersRevenueCentsTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_orders_revenue_cents_total",
		Help: "Total revenue generated by orders (in cents)",
	})
)

var (
	OrdersCreateDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_orders_create_duration_seconds",
		Help:    "Duration of order creation operations in seconds",
		Buckets: []float64{0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10, 20},
	})
	OrdersGetDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_orders_get_duration_seconds",
		Help:    "Duration of order retrieval operations in seconds",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2},
	})
	OrdersListDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_orders_list_duration_seconds",
		Help:    "Duration of order listing operations in seconds",
		Buckets: []float64{0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10},
	})
)

// ================================
// MÉTRIQUES HTTP GÉNÉRALES
// ================================

var (
	HTTPRequestDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "goshop_http_request_duration_seconds",
			Help:    "Duration of HTTP requests in seconds",
			Buckets: []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10},
		},
		[]string{"method", "path", "status"},
	)
)
