// application/metrics/metrics.go
package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
)

// ================================
// MÉTRIQUES AUTHENTIFICATION
// ================================

var (
	AuthLoginTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_auth_login_total",
		Help: "Total number of successful login attempts",
	})
	AuthLoginFailedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_auth_login_failed_total",
		Help: "Total number of failed login attempts",
	})
	AuthRegisterTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_auth_register_total",
		Help: "Total number of successful user registrations",
	})
	AuthLoginDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_auth_login_duration_seconds",
		Help:    "Duration of login operations in seconds",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10},
	})
	AuthRegisterDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_auth_register_duration_seconds",
		Help:    "Duration of user registration operations in seconds",
		Buckets: []float64{0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10, 20},
	})
	AuthProfileDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_auth_profile_duration_seconds",
		Help:    "Duration of profile retrieval operations in seconds",
		Buckets: []float64{0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1},
	})
)

// ================================
// MÉTRIQUES PRODUITS
// ================================

var (
	ProductsCreatedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_products_created_total",
		Help: "Total number of products created",
	})
	ProductsUpdatedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_products_updated_total",
		Help: "Total number of products updated",
	})
	ProductsDeletedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_products_deleted_total",
		Help: "Total number of products deleted (soft delete)",
	})
	ProductsCreateDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_products_create_duration_seconds",
		Help:    "Duration of product creation operations in seconds",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5},
	})
	ProductsGetDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_products_get_duration_seconds",
		Help:    "Duration of product retrieval operations in seconds",
		Buckets: []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5},
	})
	ProductsListDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_products_list_duration_seconds",
		Help:    "Duration of product listing operations in seconds",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10},
	})
	ProductsOperationDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_products_operation_duration_seconds",
		Help:    "Duration of product operations in seconds",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5},
	}, []string{"operation"})
	ProductsOperationErrors = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_products_operation_errors_total",
		Help: "Total number of product operation errors by type",
	}, []string{"operation", "reason"})
	ProductsListedCount = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_products_listed_count",
		Help:    "Distribution of products returned by list operations",
		Buckets: []float64{0, 1, 5, 10, 20, 50, 100, 200, 500},
	})
	PublicProductsListedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_public_products_listed_total",
		Help: "Total number of public product catalog requests",
	})
	PublicProductsListedCount = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_public_products_listed_count",
		Help:    "Distribution of public products returned",
		Buckets: []float64{0, 5, 10, 25, 50, 100, 200},
	})
)

// ================================
// MÉTRIQUES COMMANDES
// ================================

var (
	OrdersCreatedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_orders_created_total",
		Help: "Total number of orders created",
	})
	OrdersRevenueCentsTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_orders_revenue_cents_total",
		Help: "Total revenue generated by orders (in cents)",
	})
	OrdersCreateDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_orders_create_duration_seconds",
		Help:    "Duration of order creation operations in seconds",
		Buckets: []float64{0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10, 20},
	})
	OrdersGetDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_orders_get_duration_seconds",
		Help:    "Duration of order retrieval operations in seconds",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2},
	})
	OrdersListDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_orders_list_duration_seconds",
		Help:    "Duration of order listing operations in seconds",
		Buckets: []float64{0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10},
	})
)

// ================================
// MÉTRIQUES CASH ON DELIVERY (COD)
// ================================

var (
	CODOperationTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_cod_operation_total",
		Help: "Total number of COD operations by type and status",
	}, []string{"operation", "status"})
	CODOperationDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_cod_operation_duration_seconds",
		Help:    "Duration of COD operations in seconds",
		Buckets: []float64{0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10},
	}, []string{"operation"})
	CODDeliveryAmountCents = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_cod_delivery_amount_cents",
		Help:    "Distribution of COD delivery amounts in cents",
		Buckets: []float64{1000, 5000, 10000, 25000, 50000, 100000, 250000, 500000, 1000000},
	})
)

// ================================
// MÉTRIQUES PAIEMENTS
// ================================

var (
	PaymentSuccessTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_payment_success_total",
		Help: "Total number of successful payments",
	}, []string{"provider", "shop_id"})
	PaymentFailedTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_payment_failed_total",
		Help: "Total number of failed payments",
	}, []string{"provider", "reason"})
	PaymentDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_payment_duration_seconds",
		Help:    "Duration of payment processing",
		Buckets: []float64{0.1, 0.5, 1, 2, 5, 10, 30, 60},
	}, []string{"provider"})
	PaymentAmountCents = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_payment_amount_cents",
		Help:    "Distribution of payment amounts in cents",
		Buckets: []float64{100, 500, 1000, 5000, 10000, 50000, 100000, 500000, 1000000},
	}, []string{"provider"})
)

// ================================
// MÉTRIQUES TONTINE
// ================================

var (
	TontinePaymentSuccessTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_tontine_payment_success_total",
		Help: "Total number of successful tontine payments",
	})
	TontinePaymentFailedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_tontine_payment_failed_total",
		Help: "Total number of failed tontine payments",
	})
	TontineCycleCompletedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_tontine_cycle_completed_total",
		Help: "Total number of tontine cycles completed",
	})
	TontineGroupCreatedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_tontine_group_created_total",
		Help: "Total number of tontine groups created",
	})
	TontineVoucherRedeemedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_tontine_voucher_redeemed_total",
		Help: "Total number of tontine vouchers redeemed",
	})
	TontineGroupJoinTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_tontine_group_join_total",
		Help: "Total number of tontine group join attempts",
	}, []string{"status"})
	TontinePaymentInitiatedTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_tontine_payment_initiated_total",
		Help: "Total number of tontine payments initiated",
	}, []string{"operator"})
	TontinePaymentDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_tontine_payment_duration_seconds",
		Help:    "Duration of tontine payment initiation",
		Buckets: []float64{0.1, 0.5, 1, 2, 5, 10, 30},
	})
	TontineSyncPaymentTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_tontine_sync_payment_total",
		Help: "Total number of tontine payment syncs",
	}, []string{"status"})
	TontineVoucherListedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_tontine_voucher_listed_total",
		Help: "Total number of tontine voucher list operations",
	})
	TontineVoucherRedeemFailedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_tontine_voucher_redeem_failed_total",
		Help: "Total number of failed tontine voucher redemptions",
	})
	TontineOperationDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_tontine_operation_duration_seconds",
		Help:    "Duration of tontine operations by type",
		Buckets: []float64{0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10},
	}, []string{"operation"})
)

// ================================
// MÉTRIQUES TONTINE SETTINGS
// ================================

var (
	TontineSettingsOperationTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_tontine_settings_operation_total",
		Help: "Total number of tontine settings operations",
	}, []string{"operation", "status"})
	TontineSettingsDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_tontine_settings_duration_seconds",
		Help:    "Duration of tontine settings operations",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5},
	}, []string{"operation"})
)

// ================================
// MÉTRIQUES WEBHOOKS
// ================================

var (
	WebhookReceivedTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_webhook_received_total",
		Help: "Total number of webhooks received",
	}, []string{"provider", "event_type"})
	WebhookProcessedTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_webhook_processed_total",
		Help: "Total number of webhooks successfully processed",
	}, []string{"provider", "status"})
	WebhookProcessingDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_webhook_processing_duration_seconds",
		Help:    "Duration of webhook processing",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5},
	}, []string{"provider"})
)

// ================================
// MÉTRIQUES WALLET
// ================================

var (
	WalletCreditTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_wallet_credit_total",
		Help: "Total number of wallet credits",
	}, []string{"type"})
	WalletDebitTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_wallet_debit_total",
		Help: "Total number of wallet debits",
	}, []string{"type"})
	WalletAmountCents = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_wallet_amount_cents",
		Help:    "Distribution of wallet transaction amounts",
		Buckets: []float64{100, 500, 1000, 5000, 10000, 50000, 100000},
	}, []string{"type"})
)

// ================================
// MÉTRIQUES ERREURS APPLICATIVES & DB
// ================================

var (
	ApplicationErrorsTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_application_errors_total",
		Help: "Total number of application errors",
	}, []string{"type", "component"})
	DatabaseQueryDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_database_query_duration_seconds",
		Help:    "Duration of database queries",
		Buckets: []float64{0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 2, 5},
	}, []string{"operation", "table"})
	DatabaseConnectionPoolActive = prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "goshop_database_connection_pool_active",
		Help: "Number of active database connections",
	})
)

// ================================
// MÉTRIQUES SESSIONS
// ================================

var (
	SessionOperationTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_session_operation_total",
		Help: "Total number of session management operations by type and status",
	}, []string{"operation", "status"})
	SessionOperationDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_session_operation_duration_seconds",
		Help:    "Duration of session management operations in seconds",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5},
	}, []string{"operation"})
	SessionRevokedTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_session_revoked_total",
		Help: "Total number of revoked sessions by scope (single/all)",
	}, []string{"scope"})
	SessionsCleanedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_sessions_cleaned_total",
		Help: "Total number of sessions cleaned from database",
	})
	SessionsListedCount = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_sessions_listed_count",
		Help:    "Distribution of sessions returned by list operation",
		Buckets: []float64{0, 1, 5, 10, 20, 50, 100, 200},
	})
)

// ================================
// MÉTRIQUES BOUTIQUES (SHOPS)
// ================================

var (
	ShopCreatedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_shop_created_total",
		Help: "Total number of shops created",
	})
	ShopCreationFailedTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_shop_creation_failed_total",
		Help: "Total number of failed shop creations by reason",
	}, []string{"reason"})
	ShopUpdatedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_shop_updated_total",
		Help: "Total number of shops updated",
	})
	ShopListedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_shop_listed_total",
		Help: "Total number of shop list operations",
	})
	ShopOperationDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_shop_operation_duration_seconds",
		Help:    "Duration of shop operations in seconds",
		Buckets: []float64{0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10},
	}, []string{"operation"})
	ShopListedCount = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_shop_listed_count",
		Help:    "Distribution of shops returned by list operation",
		Buckets: []float64{0, 1, 2, 5, 10, 20, 50, 100},
	})
)

// ================================
// MÉTRIQUES MERCHANT KYC
// ================================

var (
	MerchantKYCSubmitTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_merchant_kyc_submit_total",
		Help: "Total number of merchant KYC submissions",
	}, []string{"status"})
	MerchantKYCReviewTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_merchant_kyc_review_total",
		Help: "Total number of merchant KYC reviews by action",
	}, []string{"action", "status"})
	MerchantKYCStatusCheckTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_merchant_kyc_status_check_total",
		Help: "Total number of merchant KYC status checks",
	})
	MerchantKYCPendingListTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_merchant_kyc_pending_list_total",
		Help: "Total number of pending KYC list operations (admin)",
	})
	MerchantKYCOperationDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_merchant_kyc_operation_duration_seconds",
		Help:    "Duration of merchant KYC operations in seconds",
		Buckets: []float64{0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10},
	}, []string{"operation"})
	MerchantKYCDocumentsPerSubmit = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_merchant_kyc_documents_per_submit",
		Help:    "Distribution of documents per KYC submission",
		Buckets: []float64{1, 2, 3, 5, 10},
	})
	MerchantKYCPendingCount = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_merchant_kyc_pending_count",
		Help:    "Distribution of pending KYC count returned",
		Buckets: []float64{0, 1, 5, 10, 20, 50, 100},
	})
)

// ================================
// MÉTRIQUES MERCHANT OVERVIEW
// ================================

var (
	MerchantOverviewRequestTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_merchant_overview_request_total",
		Help: "Total number of merchant overview requests",
	}, []string{"status"})
	MerchantOverviewDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_merchant_overview_duration_seconds",
		Help:    "Duration of merchant overview retrieval in seconds",
		Buckets: []float64{0.1, 0.25, 0.5, 1, 2, 5, 10},
	})
)

// ================================
// MÉTRIQUES DISPUTES
// ================================

var (
	DisputeOpenTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_dispute_open_total",
		Help: "Total number of disputes opened",
	}, []string{"status", "initiator_role"})
	DisputeResolveTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_dispute_resolve_total",
		Help: "Total number of disputes resolved",
	}, []string{"resolution", "status"})
	DisputeListTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_dispute_list_total",
		Help: "Total number of dispute list requests",
	})
	DisputeGetTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_dispute_get_total",
		Help: "Total number of dispute get by ID requests",
	})
	DisputeOperationDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_dispute_operation_duration_seconds",
		Help:    "Duration of dispute operations in seconds",
		Buckets: []float64{0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10},
	}, []string{"operation"})
	DisputeConflictTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_dispute_conflict_total",
		Help: "Total number of dispute conflicts (409)",
	}, []string{"operation"})
	DisputeListedCount = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_dispute_listed_count",
		Help:    "Distribution of disputes returned by list operation",
		Buckets: []float64{0, 1, 5, 10, 20, 50, 100},
	})
)

// ================================
// MÉTRIQUES DELIVERY PROOF
// ================================

var (
	DeliveryProofSubmitTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_delivery_proof_submit_total",
		Help: "Total number of delivery proof submissions",
	}, []string{"type", "status"})
	DeliveryProofDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_delivery_proof_duration_seconds",
		Help:    "Duration of delivery proof submissions in seconds",
		Buckets: []float64{0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10},
	}, []string{"type"})
	DeliveryProofTenantErrors = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_delivery_proof_tenant_errors_total",
		Help: "Total number of delivery proof requests rejected due to missing tenant context",
	})
	DeliveryProofPayloadErrors = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_delivery_proof_payload_errors_total",
		Help: "Total number of delivery proof requests with invalid JSON payload",
	})
)

// ================================
// MÉTRIQUES CUSTOMER
// ================================

var (
	CustomerCreatedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_customer_created_total",
		Help: "Total number of customers created",
	})
	CustomerUpdatedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_customer_updated_total",
		Help: "Total number of customers updated",
	})
	CustomerDeletedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_customer_deleted_total",
		Help: "Total number of customers deleted",
	})
	CustomerOperationDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_customer_operation_duration_seconds",
		Help:    "Duration of customer operations in seconds",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5},
	}, []string{"operation"})
	CustomerOperationErrors = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_customer_operation_errors_total",
		Help: "Total number of customer operation errors by type",
	}, []string{"operation", "reason"})
	CustomerListedCount = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_customer_listed_count",
		Help:    "Distribution of customers returned by list operation",
		Buckets: []float64{0, 1, 5, 10, 20, 50, 100, 200, 500},
	})
)

// ================================
// MÉTRIQUES CUSTOMER KYC
// ================================

var (
	CustomerKYCUploadTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_customer_kyc_upload_total",
		Help: "Total number of customer KYC document uploads",
	}, []string{"document_type", "status"})
	CustomerKYCStatusCheckTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_customer_kyc_status_check_total",
		Help: "Total number of customer KYC status checks",
	})
	CustomerKYCReviewTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_customer_kyc_review_total",
		Help: "Total number of customer KYC reviews by merchant",
	}, []string{"status"})
	CustomerKYCPendingListTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_customer_kyc_pending_list_total",
		Help: "Total number of pending KYC list operations",
	})
	CustomerKYCOperationDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_customer_kyc_operation_duration_seconds",
		Help:    "Duration of customer KYC operations in seconds",
		Buckets: []float64{0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10},
	}, []string{"operation"})
)

// ================================
// MÉTRIQUES CUSTOMER DASHBOARD
// ================================

var (
	CustomerDashboardRequestTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_customer_dashboard_request_total",
		Help: "Total number of customer dashboard requests",
	}, []string{"status"})
	CustomerDashboardDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_customer_dashboard_duration_seconds",
		Help:    "Duration of customer dashboard retrieval in seconds",
		Buckets: []float64{0.1, 0.25, 0.5, 1, 2, 5, 10},
	})
)

// ================================
// MÉTRIQUES HTTP GÉNÉRALES
// ================================

var (
	HTTPRequestDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_http_request_duration_seconds",
		Help:    "Duration of HTTP requests in seconds",
		Buckets: []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10},
	}, []string{"method", "path", "status"})
	HTTPRequestsTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_http_requests_total",
		Help: "Total number of HTTP requests",
	}, []string{"method", "path", "status"})
	HTTPRequestSizeBytes = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_http_request_size_bytes",
		Help:    "Size of HTTP requests in bytes",
		Buckets: []float64{100, 1000, 10000, 100000, 1000000},
	}, []string{"method", "path"})
	HTTPResponseSizeBytes = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_http_response_size_bytes",
		Help:    "Size of HTTP responses in bytes",
		Buckets: []float64{100, 1000, 10000, 100000, 1000000},
	}, []string{"method", "path", "status"})
)

// ================================
// 🆕 MÉTRIQUES COMMISSION RATES
// ================================

var (
	// CommissionRateUpdateTotal compte les créations/mises à jour de taux
	CommissionRateUpdateTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_commission_rate_update_total",
		Help: "Total number of commission rate create/update operations",
	}, []string{"action", "status", "transaction_type"})

	// CommissionRateGetTotal compte les récupérations de taux
	CommissionRateGetTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_commission_rate_get_total",
		Help: "Total number of commission rate list operations",
	}, []string{"status"})

	// CommissionRateOperationDuration mesure la durée des opérations sur les taux
	CommissionRateOperationDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_commission_rate_operation_duration_seconds",
		Help:    "Duration of commission rate operations in seconds",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5},
	}, []string{"operation"})

	// CommissionRateConfigured nombre total de taux configurés (mis à jour lors des upserts)
	CommissionRateConfigured = prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Name: "goshop_commission_rate_configured",
		Help: "Number of configured commission rates by shop and transaction type",
	}, []string{"shop_id", "transaction_type"})

	// CommissionTriggerTotal compte les déclenchements manuels de collecte
	CommissionTriggerTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_commission_trigger_total",
		Help: "Total number of manual commission collection triggers",
	}, []string{"type", "status"})

	// CommissionRateValueBps observe la valeur des taux configurés (en basis points)
	CommissionRateValueBps = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_commission_rate_value_bps",
		Help:    "Distribution of commission rate values in basis points",
		Buckets: []float64{50, 100, 150, 200, 250, 300, 500, 750, 1000, 1250, 1500},
	}, []string{"transaction_type"})
)

// ================================
// 🆕 MÉTRIQUES COLLABORATOR
// ================================

var (
	// CollaboratorInvitationTotal compte les invitations (platform/shop)
	CollaboratorInvitationTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_collaborator_invitation_total",
		Help: "Total number of collaborator invitations",
	}, []string{"type", "status"})

	// CollaboratorListTotal compte les listings de collaborateurs
	CollaboratorListTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_collaborator_list_total",
		Help: "Total number of collaborator list operations",
	}, []string{"type", "status"})

	// CollaboratorRoleUpdateTotal compte les mises à jour de rôle
	CollaboratorRoleUpdateTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_collaborator_role_update_total",
		Help: "Total number of collaborator role updates",
	}, []string{"type", "status"})

	// CollaboratorRemovalTotal compte les suppressions de collaborateurs
	CollaboratorRemovalTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_collaborator_removal_total",
		Help: "Total number of collaborator removals",
	}, []string{"type", "status"})

	// CollaboratorInvitationAcceptTotal compte les acceptations d'invitation (public)
	CollaboratorInvitationAcceptTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_collaborator_invitation_accept_total",
		Help: "Total number of invitation acceptances",
	}, []string{"status"})

	// CollaboratorInvitationPreviewTotal compte les prévisualisations d'invitation (public)
	CollaboratorInvitationPreviewTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_collaborator_invitation_preview_total",
		Help: "Total number of invitation previews",
	}, []string{"status"})

	// CollaboratorOperationDuration mesure la durée des opérations
	CollaboratorOperationDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_collaborator_operation_duration_seconds",
		Help:    "Duration of collaborator operations in seconds",
		Buckets: []float64{0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10},
	}, []string{"operation"})

	// CollaboratorActiveCount gauge pour le nombre de collaborateurs actifs
	CollaboratorActiveCount = prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Name: "goshop_collaborator_active_count",
		Help: "Number of active collaborators by type",
	}, []string{"type"})
)

// ================================
// 🆕 MÉTRIQUES COD PROOFS & COMMISSIONS
// ================================

var (
	// CODProofSubmitTotal compte les soumissions de preuves (client/merchant)
	CODProofSubmitTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_cod_proof_submit_total",
		Help: "Total number of COD proof submissions by type (client/merchant)",
	}, []string{"type", "status"})

	// CODProofGetTotal compte les récupérations de preuve par order_id
	CODProofGetTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_cod_proof_get_total",
		Help: "Total number of COD proof retrievals by order_id",
	}, []string{"status"})

	// CODProofListTotal compte les listings de preuves par boutique
	CODProofListTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_cod_proof_list_total",
		Help: "Total number of COD proof list operations by shop",
	}, []string{"status", "has_filter"})

	// CODCommissionCollectTotal compte les collectes de commission
	CODCommissionCollectTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_cod_commission_collect_total",
		Help: "Total number of COD commission collections",
	}, []string{"status"})

	// CODCommissionRetryTotal compte les retries de commission
	CODCommissionRetryTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_cod_commission_retry_total",
		Help: "Total number of COD commission retry attempts",
	}, []string{"status"})

	// CODCommissionStatsTotal compte les requêtes de stats COD
	CODCommissionStatsTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_cod_commission_stats_total",
		Help: "Total number of COD commission stats requests",
	}, []string{"status"})

	// CODDueCommissionsTotal compte les listings des commissions dues
	CODDueCommissionsTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_cod_due_commissions_total",
		Help: "Total number of due commissions list operations",
	}, []string{"status"})

	// CODProofOperationDuration mesure la durée des opérations COD
	CODProofOperationDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_cod_proof_operation_duration_seconds",
		Help:    "Duration of COD proof and commission operations in seconds",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10},
	}, []string{"operation"})

	// CODCommissionAmountCents observe les montants des commissions collectées
	CODCommissionAmountCents = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_cod_commission_amount_cents",
		Help:    "Distribution of collected COD commission amounts in cents",
		Buckets: []float64{100, 500, 1000, 5000, 10000, 50000, 100000, 500000, 1000000},
	})

	// CODProofTenantErrors compte les erreurs de contexte tenant
	CODProofTenantErrors = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_cod_proof_tenant_errors_total",
		Help: "Total number of COD proof requests rejected due to missing tenant context",
	})

	// CODProofPayloadErrors compte les erreurs de payload JSON
	CODProofPayloadErrors = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_cod_proof_payload_errors_total",
		Help: "Total number of COD proof requests with invalid JSON payload",
	})
)

// ================================
// 🆕 MÉTRIQUES API KEYS
// ================================

var (
	// APIKeyCreateTotal compte les créations de clés API
	APIKeyCreateTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_apikey_create_total",
		Help: "Total number of API key creations",
	}, []string{"status", "is_test"})

	// APIKeyListTotal compte les listings de clés API
	APIKeyListTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_apikey_list_total",
		Help: "Total number of API key list operations",
	}, []string{"status", "active_only"})

	// APIKeyRevokeTotal compte les révocations de clés API
	APIKeyRevokeTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_apikey_revoke_total",
		Help: "Total number of API key revocations",
	}, []string{"status", "scope"})

	// APIKeyStatsTotal compte les requêtes de statistiques
	APIKeyStatsTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_apikey_stats_total",
		Help: "Total number of API key stats requests",
	}, []string{"status"})

	// APIKeyOperationDuration mesure la durée des opérations API keys
	APIKeyOperationDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_apikey_operation_duration_seconds",
		Help:    "Duration of API key operations in seconds",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5},
	}, []string{"operation"})

	// APIKeyScopesCount distribution du nombre de scopes par clé
	APIKeyScopesCount = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_apikey_scopes_count",
		Help:    "Distribution of scopes per API key",
		Buckets: []float64{1, 2, 3, 5, 10, 15, 20},
	})
)

// ================================
// 🆕 MÉTRIQUES ADMIN SHOP
// ================================

var (
	// AdminShopOperationTotal compte les opérations admin shop par type et statut
	AdminShopOperationTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_admin_shop_operation_total",
		Help: "Total number of admin shop operations by type and status",
	}, []string{"operation", "status"})

	// AdminShopOperationDuration mesure la durée des opérations admin shop
	AdminShopOperationDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_admin_shop_operation_duration_seconds",
		Help:    "Duration of admin shop operations in seconds",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10},
	}, []string{"operation"})

	// AdminShopSuspendTotal compte les suspensions de boutiques
	AdminShopSuspendTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_admin_shop_suspend_total",
		Help: "Total number of shop suspensions by admin",
	})

	// AdminShopActivateTotal compte les réactivations de boutiques
	AdminShopActivateTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_admin_shop_activate_total",
		Help: "Total number of shop activations by admin",
	})

	// AdminShopListedCount distribution du nombre de shops retournés par list
	AdminShopListedCount = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_admin_shop_listed_count",
		Help:    "Distribution of shops returned by admin list operation",
		Buckets: []float64{0, 1, 5, 10, 20, 50, 100, 200, 500},
	})

	// AdminShopHealthChecksTotal compte les vérifications de santé
	AdminShopHealthChecksTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_admin_shop_health_checks_total",
		Help: "Total number of shop health score checks",
	})
)

// ================================
// 🆕 MÉTRIQUES WEBSOCKET
// ================================

var (
	// WebSocketConnectionsTotal compte les connexions WebSocket
	WebSocketConnectionsTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_websocket_connections_total",
		Help: "Total number of WebSocket connections",
	}, []string{"status"})

	// WebSocketConnectionsActive gauge des connexions actives
	WebSocketConnectionsActive = prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "goshop_websocket_connections_active",
		Help: "Number of active WebSocket connections",
	})

	// WebSocketConnectionDuration mesure la durée des connexions
	WebSocketConnectionDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_websocket_connection_duration_seconds",
		Help:    "Duration of WebSocket connections in seconds",
		Buckets: []float64{1, 5, 10, 30, 60, 300, 600, 1800, 3600},
	})

	// WebSocketMessagesReceived compte les messages reçus
	WebSocketMessagesReceived = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_websocket_messages_received_total",
		Help: "Total number of WebSocket messages received",
	})

	// WebSocketUpgradeErrors compte les erreurs d'upgrade
	WebSocketUpgradeErrors = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_websocket_upgrade_errors_total",
		Help: "Total number of WebSocket upgrade failures",
	})

	// WebSocketUnexpectedCloses compte les fermetures inattendues
	WebSocketUnexpectedCloses = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_websocket_unexpected_closes_total",
		Help: "Total number of unexpected WebSocket disconnections",
	})
)

// ================================
// 🆕 MÉTRIQUES HEALTH CHECKS
// ================================

var (
	// HealthCheckTotal compte les health checks par type
	HealthCheckTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_health_check_total",
		Help: "Total number of health checks by type",
	}, []string{"type", "status"})

	// HealthCheckDuration mesure la durée des health checks
	HealthCheckDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_health_check_duration_seconds",
		Help:    "Duration of health checks in seconds",
		Buckets: []float64{0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 3},
	}, []string{"type"})

	// HealthDependenciesStatus gauge du status des dépendances
	HealthDependenciesStatus = prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Name: "goshop_health_dependencies_status",
		Help: "Status of external dependencies (1=healthy, 0=unhealthy)",
	}, []string{"dependency"})

	// HealthDatabasePingDuration mesure la durée des pings DB
	HealthDatabasePingDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_health_database_ping_duration_seconds",
		Help:    "Duration of database ping in seconds",
		Buckets: []float64{0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 3},
	})

	// HealthRedisPingDuration mesure la durée des pings Redis
	HealthRedisPingDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_health_redis_ping_duration_seconds",
		Help:    "Duration of Redis ping in seconds",
		Buckets: []float64{0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 3},
	})
)

// ================================
// 🆕 MÉTRIQUES WITHDRAWALS
// ================================

var (
	// WithdrawalCreateTotal compte les créations de retraits
	WithdrawalCreateTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_withdrawal_create_total",
		Help: "Total number of withdrawal creations by status",
	}, []string{"status"})

	// WithdrawalListTotal compte les listings de retraits
	WithdrawalListTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_withdrawal_list_total",
		Help: "Total number of withdrawal list operations by status",
	}, []string{"status"})

	// WithdrawalGetTotal compte les récupérations de retraits par ID
	WithdrawalGetTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_withdrawal_get_total",
		Help: "Total number of withdrawal get operations by status",
	}, []string{"status"})

	// WithdrawalOperationDuration mesure la durée des opérations de retrait
	WithdrawalOperationDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_withdrawal_operation_duration_seconds",
		Help:    "Duration of withdrawal operations in seconds",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10},
	}, []string{"operation"})

	// WithdrawalAmountCents observe les montants des retraits
	WithdrawalAmountCents = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_withdrawal_amount_cents",
		Help:    "Distribution of withdrawal amounts in cents",
		Buckets: []float64{1000, 5000, 10000, 25000, 50000, 100000, 250000, 500000, 1000000, 5000000},
	})

	// WithdrawalHeldCentsRejections compte les rejets dus à held_cents
	WithdrawalHeldCentsRejections = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_withdrawal_held_cents_rejections_total",
		Help: "Total number of withdrawals rejected due to held_cents protection",
	})

	// WithdrawalListedCount distribution du nombre de retraits retournés
	WithdrawalListedCount = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_withdrawal_listed_count",
		Help:    "Distribution of withdrawals returned by list operation",
		Buckets: []float64{0, 1, 5, 10, 20, 50, 100, 200},
	})
)

// ================================
// 🆕 MÉTRIQUES 2FA (Two-Factor Authentication)
// ================================

var (
	// TwoFAOperationTotal compte les opérations 2FA par type et statut
	TwoFAOperationTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_2fa_operation_total",
		Help: "Total number of 2FA operations by type and status",
	}, []string{"operation", "status"})

	// TwoFAOperationDuration mesure la durée des opérations 2FA
	TwoFAOperationDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_2fa_operation_duration_seconds",
		Help:    "Duration of 2FA operations in seconds",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5},
	}, []string{"operation"})

	// TwoFAVerificationAttempts compte les tentatives de vérification
	TwoFAVerificationAttempts = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_2fa_verification_attempts_total",
		Help: "Total number of 2FA verification attempts",
	}, []string{"status"})

	// TwoFARecoveryCodesUsed compte les codes de récupération utilisés
	TwoFARecoveryCodesUsed = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_2fa_recovery_codes_used_total",
		Help: "Total number of recovery codes used",
	})

	// TwoFAInvalidCodes compte les codes TOTP invalides
	TwoFAInvalidCodes = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_2fa_invalid_codes_total",
		Help: "Total number of invalid TOTP codes",
	})

	// TwoFAEnabledUsers gauge des utilisateurs avec 2FA activée
	TwoFAEnabledUsers = prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "goshop_2fa_enabled_users",
		Help: "Number of users with 2FA enabled",
	})
)

// ================================
// 🆕 MÉTRIQUES SYNC ORDER
// ================================

var (
	// SyncOrderTotal compte les synchronisations de paiement order
	SyncOrderTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_sync_order_total",
		Help: "Total number of order payment syncs",
	}, []string{"status"})

	// SyncOrderDuration mesure la durée des synchronisations
	SyncOrderDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_sync_order_duration_seconds",
		Help:    "Duration of order payment syncs in seconds",
		Buckets: []float64{0.1, 0.5, 1, 2, 5, 10, 30, 60},
	})

	// SyncOrderPaymentConfirmed compte les paiements confirmés via sync
	SyncOrderPaymentConfirmed = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_sync_order_payment_confirmed_total",
		Help: "Total number of payments confirmed via sync",
	})
)

// ================================
// 🆕 MÉTRIQUES FILE HANDLER
// ================================

var (
	// FilePresignedURLGenerated compte les URLs pré-signées générées
	FilePresignedURLGenerated = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_file_presigned_url_generated_total",
		Help: "Total number of presigned URLs generated",
	}, []string{"status"})

	// FileDownloadTotal compte les téléchargements de fichiers
	FileDownloadTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_file_download_total",
		Help: "Total number of file downloads",
	}, []string{"status", "mime_type"})

	// FileOperationDuration mesure la durée des opérations fichier
	FileOperationDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "goshop_file_operation_duration_seconds",
		Help:    "Duration of file operations in seconds",
		Buckets: []float64{0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 2, 5},
	}, []string{"operation"})

	// FileDownloadSizeBytes observe la taille des fichiers téléchargés
	FileDownloadSizeBytes = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "goshop_file_download_size_bytes",
		Help:    "Distribution of downloaded file sizes in bytes",
		Buckets: []float64{1024, 10240, 102400, 1048576, 10485760, 104857600},
	})

	// FileSecurityViolations compte les violations de sécurité
	FileSecurityViolations = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "goshop_file_security_violations_total",
		Help: "Total number of file security violations",
	}, []string{"type"})

	// FileExpiredURLs compte les URLs expirées
	FileExpiredURLs = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_file_expired_urls_total",
		Help: "Total number of expired presigned URLs",
	})

	// FileInvalidSignatures compte les signatures invalides
	FileInvalidSignatures = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "goshop_file_invalid_signatures_total",
		Help: "Total number of invalid file signatures",
	})
)
