// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/service (interfaces: NotificationService)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/service/mock_notification_service.go -package=service . NotificationService
//

// Package service is a generated GoMock package.
package service

import (
	entity "Goshop/domain/entity"
	service "Goshop/domain/service"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationService is a mock of NotificationService interface.
type MockNotificationService struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationServiceMockRecorder
	isgomock struct{}
}

// MockNotificationServiceMockRecorder is the mock recorder for MockNotificationService.
type MockNotificationServiceMockRecorder struct {
	mock *MockNotificationService
}

// NewMockNotificationService creates a new mock instance.
func NewMockNotificationService(ctrl *gomock.Controller) *MockNotificationService {
	mock := &MockNotificationService{ctrl: ctrl}
	mock.recorder = &MockNotificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationService) EXPECT() *MockNotificationServiceMockRecorder {
	return m.recorder
}

// NotifyClientDisputeResolved mocks base method.
func (m *MockNotificationService) NotifyClientDisputeResolved(ctx context.Context, customerID, orderID, resolution string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyClientDisputeResolved", ctx, customerID, orderID, resolution)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyClientDisputeResolved indicates an expected call of NotifyClientDisputeResolved.
func (mr *MockNotificationServiceMockRecorder) NotifyClientDisputeResolved(ctx, customerID, orderID, resolution any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyClientDisputeResolved", reflect.TypeOf((*MockNotificationService)(nil).NotifyClientDisputeResolved), ctx, customerID, orderID, resolution)
}

// NotifyClientOrderConfirmed mocks base method.
func (m *MockNotificationService) NotifyClientOrderConfirmed(ctx context.Context, order *entity.Order, customerPhone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyClientOrderConfirmed", ctx, order, customerPhone)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyClientOrderConfirmed indicates an expected call of NotifyClientOrderConfirmed.
func (mr *MockNotificationServiceMockRecorder) NotifyClientOrderConfirmed(ctx, order, customerPhone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyClientOrderConfirmed", reflect.TypeOf((*MockNotificationService)(nil).NotifyClientOrderConfirmed), ctx, order, customerPhone)
}

// NotifyClientOrderDelivered mocks base method.
func (m *MockNotificationService) NotifyClientOrderDelivered(ctx context.Context, order *entity.Order, customerPhone string, amountReceived int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyClientOrderDelivered", ctx, order, customerPhone, amountReceived)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyClientOrderDelivered indicates an expected call of NotifyClientOrderDelivered.
func (mr *MockNotificationServiceMockRecorder) NotifyClientOrderDelivered(ctx, order, customerPhone, amountReceived any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyClientOrderDelivered", reflect.TypeOf((*MockNotificationService)(nil).NotifyClientOrderDelivered), ctx, order, customerPhone, amountReceived)
}

// NotifyClientOrderExpired mocks base method.
func (m *MockNotificationService) NotifyClientOrderExpired(ctx context.Context, order *entity.Order, customerPhone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyClientOrderExpired", ctx, order, customerPhone)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyClientOrderExpired indicates an expected call of NotifyClientOrderExpired.
func (mr *MockNotificationServiceMockRecorder) NotifyClientOrderExpired(ctx, order, customerPhone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyClientOrderExpired", reflect.TypeOf((*MockNotificationService)(nil).NotifyClientOrderExpired), ctx, order, customerPhone)
}

// NotifyClientOrderRejected mocks base method.
func (m *MockNotificationService) NotifyClientOrderRejected(ctx context.Context, order *entity.Order, customerPhone, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyClientOrderRejected", ctx, order, customerPhone, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyClientOrderRejected indicates an expected call of NotifyClientOrderRejected.
func (mr *MockNotificationServiceMockRecorder) NotifyClientOrderRejected(ctx, order, customerPhone, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyClientOrderRejected", reflect.TypeOf((*MockNotificationService)(nil).NotifyClientOrderRejected), ctx, order, customerPhone, reason)
}

// NotifyMerchantCommissionPaid mocks base method.
func (m *MockNotificationService) NotifyMerchantCommissionPaid(ctx context.Context, shop *entity.Shop, order *entity.Order, commissionCents int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyMerchantCommissionPaid", ctx, shop, order, commissionCents)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyMerchantCommissionPaid indicates an expected call of NotifyMerchantCommissionPaid.
func (mr *MockNotificationServiceMockRecorder) NotifyMerchantCommissionPaid(ctx, shop, order, commissionCents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyMerchantCommissionPaid", reflect.TypeOf((*MockNotificationService)(nil).NotifyMerchantCommissionPaid), ctx, shop, order, commissionCents)
}

// NotifyMerchantDeliveryReady mocks base method.
func (m *MockNotificationService) NotifyMerchantDeliveryReady(ctx context.Context, shop *entity.Shop, order *entity.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyMerchantDeliveryReady", ctx, shop, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyMerchantDeliveryReady indicates an expected call of NotifyMerchantDeliveryReady.
func (mr *MockNotificationServiceMockRecorder) NotifyMerchantDeliveryReady(ctx, shop, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyMerchantDeliveryReady", reflect.TypeOf((*MockNotificationService)(nil).NotifyMerchantDeliveryReady), ctx, shop, order)
}

// NotifyMerchantDisputeResolved mocks base method.
func (m *MockNotificationService) NotifyMerchantDisputeResolved(ctx context.Context, shopID, orderID, resolution string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyMerchantDisputeResolved", ctx, shopID, orderID, resolution)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyMerchantDisputeResolved indicates an expected call of NotifyMerchantDisputeResolved.
func (mr *MockNotificationServiceMockRecorder) NotifyMerchantDisputeResolved(ctx, shopID, orderID, resolution any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyMerchantDisputeResolved", reflect.TypeOf((*MockNotificationService)(nil).NotifyMerchantDisputeResolved), ctx, shopID, orderID, resolution)
}

// NotifyMerchantOrderReceived mocks base method.
func (m *MockNotificationService) NotifyMerchantOrderReceived(ctx context.Context, shop *entity.Shop, order *entity.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyMerchantOrderReceived", ctx, shop, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyMerchantOrderReceived indicates an expected call of NotifyMerchantOrderReceived.
func (mr *MockNotificationServiceMockRecorder) NotifyMerchantOrderReceived(ctx, shop, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyMerchantOrderReceived", reflect.TypeOf((*MockNotificationService)(nil).NotifyMerchantOrderReceived), ctx, shop, order)
}

// NotifyOrderStatusChange mocks base method.
func (m *MockNotificationService) NotifyOrderStatusChange(ctx context.Context, order *entity.Order, customerID string, shopID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyOrderStatusChange", ctx, order, customerID, shopID)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyOrderStatusChange indicates an expected call of NotifyOrderStatusChange.
func (mr *MockNotificationServiceMockRecorder) NotifyOrderStatusChange(ctx, order, customerID, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyOrderStatusChange", reflect.TypeOf((*MockNotificationService)(nil).NotifyOrderStatusChange), ctx, order, customerID, shopID)
}

// SendNotification mocks base method.
func (m *MockNotificationService) SendNotification(ctx context.Context, req *service.NotificationRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNotification", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNotification indicates an expected call of SendNotification.
func (mr *MockNotificationServiceMockRecorder) SendNotification(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNotification", reflect.TypeOf((*MockNotificationService)(nil).SendNotification), ctx, req)
}
