// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: PaymentRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_payment_repository.go -package=repository . PaymentRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentRepository is a mock of PaymentRepository interface.
type MockPaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentRepositoryMockRecorder is the mock recorder for MockPaymentRepository.
type MockPaymentRepositoryMockRecorder struct {
	mock *MockPaymentRepository
}

// NewMockPaymentRepository creates a new mock instance.
func NewMockPaymentRepository(ctrl *gomock.Controller) *MockPaymentRepository {
	mock := &MockPaymentRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRepository) EXPECT() *MockPaymentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPaymentRepository) Create(ctx context.Context, payment *entity.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPaymentRepositoryMockRecorder) Create(ctx, payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPaymentRepository)(nil).Create), ctx, payment)
}

// FindByID mocks base method.
func (m *MockPaymentRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPaymentRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPaymentRepository)(nil).FindByID), ctx, id)
}

// FindByOrderID mocks base method.
func (m *MockPaymentRepository) FindByOrderID(ctx context.Context, orderID uuid.UUID) ([]*entity.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOrderID", ctx, orderID)
	ret0, _ := ret[0].([]*entity.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOrderID indicates an expected call of FindByOrderID.
func (mr *MockPaymentRepositoryMockRecorder) FindByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOrderID", reflect.TypeOf((*MockPaymentRepository)(nil).FindByOrderID), ctx, orderID)
}

// FindByProviderRef mocks base method.
func (m *MockPaymentRepository) FindByProviderRef(ctx context.Context, provider entity.PaymentProvider, providerRef string) (*entity.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProviderRef", ctx, provider, providerRef)
	ret0, _ := ret[0].(*entity.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProviderRef indicates an expected call of FindByProviderRef.
func (mr *MockPaymentRepositoryMockRecorder) FindByProviderRef(ctx, provider, providerRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProviderRef", reflect.TypeOf((*MockPaymentRepository)(nil).FindByProviderRef), ctx, provider, providerRef)
}

// FindByProviderRefForUpdate mocks base method.
func (m *MockPaymentRepository) FindByProviderRefForUpdate(ctx context.Context, provider entity.PaymentProvider, providerRef string) (*entity.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProviderRefForUpdate", ctx, provider, providerRef)
	ret0, _ := ret[0].(*entity.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProviderRefForUpdate indicates an expected call of FindByProviderRefForUpdate.
func (mr *MockPaymentRepositoryMockRecorder) FindByProviderRefForUpdate(ctx, provider, providerRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProviderRefForUpdate", reflect.TypeOf((*MockPaymentRepository)(nil).FindByProviderRefForUpdate), ctx, provider, providerRef)
}

// FindByShop mocks base method.
func (m *MockPaymentRepository) FindByShop(ctx context.Context, shopID uuid.UUID, filters repository.PaymentFilters) ([]*entity.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShop", ctx, shopID, filters)
	ret0, _ := ret[0].([]*entity.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShop indicates an expected call of FindByShop.
func (mr *MockPaymentRepositoryMockRecorder) FindByShop(ctx, shopID, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShop", reflect.TypeOf((*MockPaymentRepository)(nil).FindByShop), ctx, shopID, filters)
}

// FindCompletedWithoutCommission mocks base method.
func (m *MockPaymentRepository) FindCompletedWithoutCommission(ctx context.Context, limit int) ([]*entity.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCompletedWithoutCommission", ctx, limit)
	ret0, _ := ret[0].([]*entity.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCompletedWithoutCommission indicates an expected call of FindCompletedWithoutCommission.
func (mr *MockPaymentRepositoryMockRecorder) FindCompletedWithoutCommission(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCompletedWithoutCommission", reflect.TypeOf((*MockPaymentRepository)(nil).FindCompletedWithoutCommission), ctx, limit)
}

// Update mocks base method.
func (m *MockPaymentRepository) Update(ctx context.Context, payment *entity.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPaymentRepositoryMockRecorder) Update(ctx, payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPaymentRepository)(nil).Update), ctx, payment)
}

// UpdateCommissionStatus mocks base method.
func (m *MockPaymentRepository) UpdateCommissionStatus(ctx context.Context, paymentID, status string, commissionCents int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCommissionStatus", ctx, paymentID, status, commissionCents)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCommissionStatus indicates an expected call of UpdateCommissionStatus.
func (mr *MockPaymentRepositoryMockRecorder) UpdateCommissionStatus(ctx, paymentID, status, commissionCents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCommissionStatus", reflect.TypeOf((*MockPaymentRepository)(nil).UpdateCommissionStatus), ctx, paymentID, status, commissionCents)
}

// WithTX mocks base method.
func (m *MockPaymentRepository) WithTX(tx repository.Tx) repository.PaymentRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTX", tx)
	ret0, _ := ret[0].(repository.PaymentRepository)
	return ret0
}

// WithTX indicates an expected call of WithTX.
func (mr *MockPaymentRepositoryMockRecorder) WithTX(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTX", reflect.TypeOf((*MockPaymentRepository)(nil).WithTX), tx)
}
