// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: CreditContractRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_credit_contract_repository.go -package=repository . CreditContractRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreditContractRepository is a mock of CreditContractRepository interface.
type MockCreditContractRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCreditContractRepositoryMockRecorder
	isgomock struct{}
}

// MockCreditContractRepositoryMockRecorder is the mock recorder for MockCreditContractRepository.
type MockCreditContractRepositoryMockRecorder struct {
	mock *MockCreditContractRepository
}

// NewMockCreditContractRepository creates a new mock instance.
func NewMockCreditContractRepository(ctrl *gomock.Controller) *MockCreditContractRepository {
	mock := &MockCreditContractRepository{ctrl: ctrl}
	mock.recorder = &MockCreditContractRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreditContractRepository) EXPECT() *MockCreditContractRepositoryMockRecorder {
	return m.recorder
}

// CountActiveByCustomerID mocks base method.
func (m *MockCreditContractRepository) CountActiveByCustomerID(ctx context.Context, customerID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveByCustomerID", ctx, customerID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveByCustomerID indicates an expected call of CountActiveByCustomerID.
func (mr *MockCreditContractRepositoryMockRecorder) CountActiveByCustomerID(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveByCustomerID", reflect.TypeOf((*MockCreditContractRepository)(nil).CountActiveByCustomerID), ctx, customerID)
}

// Create mocks base method.
func (m *MockCreditContractRepository) Create(ctx context.Context, contract *entity.CreditContract) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, contract)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCreditContractRepositoryMockRecorder) Create(ctx, contract any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCreditContractRepository)(nil).Create), ctx, contract)
}

// FindActiveByCustomerID mocks base method.
func (m *MockCreditContractRepository) FindActiveByCustomerID(ctx context.Context, customerID string) ([]*entity.CreditContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByCustomerID", ctx, customerID)
	ret0, _ := ret[0].([]*entity.CreditContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByCustomerID indicates an expected call of FindActiveByCustomerID.
func (mr *MockCreditContractRepositoryMockRecorder) FindActiveByCustomerID(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByCustomerID", reflect.TypeOf((*MockCreditContractRepository)(nil).FindActiveByCustomerID), ctx, customerID)
}

// FindActiveByShopID mocks base method.
func (m *MockCreditContractRepository) FindActiveByShopID(ctx context.Context, shopID string) ([]*entity.CreditContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.CreditContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByShopID indicates an expected call of FindActiveByShopID.
func (mr *MockCreditContractRepositoryMockRecorder) FindActiveByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByShopID", reflect.TypeOf((*MockCreditContractRepository)(nil).FindActiveByShopID), ctx, shopID)
}

// FindByApplicationID mocks base method.
func (m *MockCreditContractRepository) FindByApplicationID(ctx context.Context, applicationID string) (*entity.CreditContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByApplicationID", ctx, applicationID)
	ret0, _ := ret[0].(*entity.CreditContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByApplicationID indicates an expected call of FindByApplicationID.
func (mr *MockCreditContractRepositoryMockRecorder) FindByApplicationID(ctx, applicationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByApplicationID", reflect.TypeOf((*MockCreditContractRepository)(nil).FindByApplicationID), ctx, applicationID)
}

// FindByCustomerID mocks base method.
func (m *MockCreditContractRepository) FindByCustomerID(ctx context.Context, customerID string) ([]*entity.CreditContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCustomerID", ctx, customerID)
	ret0, _ := ret[0].([]*entity.CreditContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCustomerID indicates an expected call of FindByCustomerID.
func (mr *MockCreditContractRepositoryMockRecorder) FindByCustomerID(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCustomerID", reflect.TypeOf((*MockCreditContractRepository)(nil).FindByCustomerID), ctx, customerID)
}

// FindByID mocks base method.
func (m *MockCreditContractRepository) FindByID(ctx context.Context, id string) (*entity.CreditContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.CreditContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCreditContractRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCreditContractRepository)(nil).FindByID), ctx, id)
}

// FindByShopID mocks base method.
func (m *MockCreditContractRepository) FindByShopID(ctx context.Context, shopID string) ([]*entity.CreditContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.CreditContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShopID indicates an expected call of FindByShopID.
func (mr *MockCreditContractRepositoryMockRecorder) FindByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShopID", reflect.TypeOf((*MockCreditContractRepository)(nil).FindByShopID), ctx, shopID)
}

// Update mocks base method.
func (m *MockCreditContractRepository) Update(ctx context.Context, contract *entity.CreditContract) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, contract)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCreditContractRepositoryMockRecorder) Update(ctx, contract any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCreditContractRepository)(nil).Update), ctx, contract)
}

// WithTX mocks base method.
func (m *MockCreditContractRepository) WithTX(tx repository.Tx) repository.CreditContractRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTX", tx)
	ret0, _ := ret[0].(repository.CreditContractRepository)
	return ret0
}

// WithTX indicates an expected call of WithTX.
func (mr *MockCreditContractRepositoryMockRecorder) WithTX(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTX", reflect.TypeOf((*MockCreditContractRepository)(nil).WithTX), tx)
}
