// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: DeliveryProofRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_delivery_proof_repository.go -package=repository . DeliveryProofRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeliveryProofRepository is a mock of DeliveryProofRepository interface.
type MockDeliveryProofRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryProofRepositoryMockRecorder
	isgomock struct{}
}

// MockDeliveryProofRepositoryMockRecorder is the mock recorder for MockDeliveryProofRepository.
type MockDeliveryProofRepositoryMockRecorder struct {
	mock *MockDeliveryProofRepository
}

// NewMockDeliveryProofRepository creates a new mock instance.
func NewMockDeliveryProofRepository(ctrl *gomock.Controller) *MockDeliveryProofRepository {
	mock := &MockDeliveryProofRepository{ctrl: ctrl}
	mock.recorder = &MockDeliveryProofRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryProofRepository) EXPECT() *MockDeliveryProofRepositoryMockRecorder {
	return m.recorder
}

// CountByStatusByShopID mocks base method.
func (m *MockDeliveryProofRepository) CountByStatusByShopID(ctx context.Context, shopID string, status entity.EscrowStatus) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByStatusByShopID", ctx, shopID, status)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByStatusByShopID indicates an expected call of CountByStatusByShopID.
func (mr *MockDeliveryProofRepositoryMockRecorder) CountByStatusByShopID(ctx, shopID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByStatusByShopID", reflect.TypeOf((*MockDeliveryProofRepository)(nil).CountByStatusByShopID), ctx, shopID, status)
}

// Create mocks base method.
func (m *MockDeliveryProofRepository) Create(ctx context.Context, proof *entity.DeliveryProof) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, proof)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDeliveryProofRepositoryMockRecorder) Create(ctx, proof any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeliveryProofRepository)(nil).Create), ctx, proof)
}

// FindAutoReleaseEligible mocks base method.
func (m *MockDeliveryProofRepository) FindAutoReleaseEligible(ctx context.Context) ([]*entity.DeliveryProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAutoReleaseEligible", ctx)
	ret0, _ := ret[0].([]*entity.DeliveryProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAutoReleaseEligible indicates an expected call of FindAutoReleaseEligible.
func (mr *MockDeliveryProofRepositoryMockRecorder) FindAutoReleaseEligible(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAutoReleaseEligible", reflect.TypeOf((*MockDeliveryProofRepository)(nil).FindAutoReleaseEligible), ctx)
}

// FindByCreditContractID mocks base method.
func (m *MockDeliveryProofRepository) FindByCreditContractID(ctx context.Context, contractID string) (*entity.DeliveryProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCreditContractID", ctx, contractID)
	ret0, _ := ret[0].(*entity.DeliveryProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCreditContractID indicates an expected call of FindByCreditContractID.
func (mr *MockDeliveryProofRepositoryMockRecorder) FindByCreditContractID(ctx, contractID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCreditContractID", reflect.TypeOf((*MockDeliveryProofRepository)(nil).FindByCreditContractID), ctx, contractID)
}

// FindByID mocks base method.
func (m *MockDeliveryProofRepository) FindByID(ctx context.Context, id string) (*entity.DeliveryProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.DeliveryProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockDeliveryProofRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockDeliveryProofRepository)(nil).FindByID), ctx, id)
}

// FindByOrderID mocks base method.
func (m *MockDeliveryProofRepository) FindByOrderID(ctx context.Context, orderID string) (*entity.DeliveryProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*entity.DeliveryProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOrderID indicates an expected call of FindByOrderID.
func (mr *MockDeliveryProofRepositoryMockRecorder) FindByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOrderID", reflect.TypeOf((*MockDeliveryProofRepository)(nil).FindByOrderID), ctx, orderID)
}

// FindByReferenceID mocks base method.
func (m *MockDeliveryProofRepository) FindByReferenceID(ctx context.Context, referenceType, referenceID string) (*entity.DeliveryProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByReferenceID", ctx, referenceType, referenceID)
	ret0, _ := ret[0].(*entity.DeliveryProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByReferenceID indicates an expected call of FindByReferenceID.
func (mr *MockDeliveryProofRepositoryMockRecorder) FindByReferenceID(ctx, referenceType, referenceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByReferenceID", reflect.TypeOf((*MockDeliveryProofRepository)(nil).FindByReferenceID), ctx, referenceType, referenceID)
}

// FindByStatus mocks base method.
func (m *MockDeliveryProofRepository) FindByStatus(ctx context.Context, status entity.EscrowStatus) ([]*entity.DeliveryProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByStatus", ctx, status)
	ret0, _ := ret[0].([]*entity.DeliveryProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByStatus indicates an expected call of FindByStatus.
func (mr *MockDeliveryProofRepositoryMockRecorder) FindByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByStatus", reflect.TypeOf((*MockDeliveryProofRepository)(nil).FindByStatus), ctx, status)
}

// FindByTontineVoucherID mocks base method.
func (m *MockDeliveryProofRepository) FindByTontineVoucherID(ctx context.Context, voucherID string) (*entity.DeliveryProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTontineVoucherID", ctx, voucherID)
	ret0, _ := ret[0].(*entity.DeliveryProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTontineVoucherID indicates an expected call of FindByTontineVoucherID.
func (mr *MockDeliveryProofRepositoryMockRecorder) FindByTontineVoucherID(ctx, voucherID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTontineVoucherID", reflect.TypeOf((*MockDeliveryProofRepository)(nil).FindByTontineVoucherID), ctx, voucherID)
}

// FindDeliveredByShopID mocks base method.
func (m *MockDeliveryProofRepository) FindDeliveredByShopID(ctx context.Context, shopID string) ([]*entity.DeliveryProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDeliveredByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.DeliveryProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDeliveredByShopID indicates an expected call of FindDeliveredByShopID.
func (mr *MockDeliveryProofRepositoryMockRecorder) FindDeliveredByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDeliveredByShopID", reflect.TypeOf((*MockDeliveryProofRepository)(nil).FindDeliveredByShopID), ctx, shopID)
}

// FindDisputeDeadlineExpired mocks base method.
func (m *MockDeliveryProofRepository) FindDisputeDeadlineExpired(ctx context.Context) ([]*entity.DeliveryProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDisputeDeadlineExpired", ctx)
	ret0, _ := ret[0].([]*entity.DeliveryProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDisputeDeadlineExpired indicates an expected call of FindDisputeDeadlineExpired.
func (mr *MockDeliveryProofRepositoryMockRecorder) FindDisputeDeadlineExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDisputeDeadlineExpired", reflect.TypeOf((*MockDeliveryProofRepository)(nil).FindDisputeDeadlineExpired), ctx)
}

// FindDisputedByShopID mocks base method.
func (m *MockDeliveryProofRepository) FindDisputedByShopID(ctx context.Context, shopID string) ([]*entity.DeliveryProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDisputedByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.DeliveryProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDisputedByShopID indicates an expected call of FindDisputedByShopID.
func (mr *MockDeliveryProofRepositoryMockRecorder) FindDisputedByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDisputedByShopID", reflect.TypeOf((*MockDeliveryProofRepository)(nil).FindDisputedByShopID), ctx, shopID)
}

// FindPendingShipmentByShopID mocks base method.
func (m *MockDeliveryProofRepository) FindPendingShipmentByShopID(ctx context.Context, shopID string) ([]*entity.DeliveryProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPendingShipmentByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.DeliveryProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPendingShipmentByShopID indicates an expected call of FindPendingShipmentByShopID.
func (mr *MockDeliveryProofRepositoryMockRecorder) FindPendingShipmentByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPendingShipmentByShopID", reflect.TypeOf((*MockDeliveryProofRepository)(nil).FindPendingShipmentByShopID), ctx, shopID)
}

// FindShippedByShopID mocks base method.
func (m *MockDeliveryProofRepository) FindShippedByShopID(ctx context.Context, shopID string) ([]*entity.DeliveryProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindShippedByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.DeliveryProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindShippedByShopID indicates an expected call of FindShippedByShopID.
func (mr *MockDeliveryProofRepositoryMockRecorder) FindShippedByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindShippedByShopID", reflect.TypeOf((*MockDeliveryProofRepository)(nil).FindShippedByShopID), ctx, shopID)
}

// Update mocks base method.
func (m *MockDeliveryProofRepository) Update(ctx context.Context, proof *entity.DeliveryProof) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, proof)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDeliveryProofRepositoryMockRecorder) Update(ctx, proof any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeliveryProofRepository)(nil).Update), ctx, proof)
}

// UpdateEscrowStatus mocks base method.
func (m *MockDeliveryProofRepository) UpdateEscrowStatus(ctx context.Context, id string, status entity.EscrowStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEscrowStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEscrowStatus indicates an expected call of UpdateEscrowStatus.
func (mr *MockDeliveryProofRepositoryMockRecorder) UpdateEscrowStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEscrowStatus", reflect.TypeOf((*MockDeliveryProofRepository)(nil).UpdateEscrowStatus), ctx, id, status)
}

// WithTX mocks base method.
func (m *MockDeliveryProofRepository) WithTX(tx repository.Tx) repository.DeliveryProofRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTX", tx)
	ret0, _ := ret[0].(repository.DeliveryProofRepository)
	return ret0
}

// WithTX indicates an expected call of WithTX.
func (mr *MockDeliveryProofRepositoryMockRecorder) WithTX(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTX", reflect.TypeOf((*MockDeliveryProofRepository)(nil).WithTX), tx)
}
