// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: DisputeRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_dispute_repository.go -package=repository . DisputeRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDisputeRepository is a mock of DisputeRepository interface.
type MockDisputeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDisputeRepositoryMockRecorder
	isgomock struct{}
}

// MockDisputeRepositoryMockRecorder is the mock recorder for MockDisputeRepository.
type MockDisputeRepositoryMockRecorder struct {
	mock *MockDisputeRepository
}

// NewMockDisputeRepository creates a new mock instance.
func NewMockDisputeRepository(ctrl *gomock.Controller) *MockDisputeRepository {
	mock := &MockDisputeRepository{ctrl: ctrl}
	mock.recorder = &MockDisputeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDisputeRepository) EXPECT() *MockDisputeRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockDisputeRepository) Count(ctx context.Context, filters repository.DisputeFilters) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filters)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockDisputeRepositoryMockRecorder) Count(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockDisputeRepository)(nil).Count), ctx, filters)
}

// Create mocks base method.
func (m *MockDisputeRepository) Create(ctx context.Context, dispute *entity.Dispute) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, dispute)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDisputeRepositoryMockRecorder) Create(ctx, dispute any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDisputeRepository)(nil).Create), ctx, dispute)
}

// ExistsByOrderID mocks base method.
func (m *MockDisputeRepository) ExistsByOrderID(ctx context.Context, orderID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByOrderID", ctx, orderID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByOrderID indicates an expected call of ExistsByOrderID.
func (mr *MockDisputeRepositoryMockRecorder) ExistsByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByOrderID", reflect.TypeOf((*MockDisputeRepository)(nil).ExistsByOrderID), ctx, orderID)
}

// FindAll mocks base method.
func (m *MockDisputeRepository) FindAll(ctx context.Context, status string, limit, offset int) ([]*entity.Dispute, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, status, limit, offset)
	ret0, _ := ret[0].([]*entity.Dispute)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockDisputeRepositoryMockRecorder) FindAll(ctx, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockDisputeRepository)(nil).FindAll), ctx, status, limit, offset)
}

// FindByID mocks base method.
func (m *MockDisputeRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.Dispute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.Dispute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockDisputeRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockDisputeRepository)(nil).FindByID), ctx, id)
}

// FindByOrderID mocks base method.
func (m *MockDisputeRepository) FindByOrderID(ctx context.Context, orderID uuid.UUID) (*entity.Dispute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*entity.Dispute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOrderID indicates an expected call of FindByOrderID.
func (mr *MockDisputeRepositoryMockRecorder) FindByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOrderID", reflect.TypeOf((*MockDisputeRepository)(nil).FindByOrderID), ctx, orderID)
}

// FindByPaymentID mocks base method.
func (m *MockDisputeRepository) FindByPaymentID(ctx context.Context, paymentID uuid.UUID) (*entity.Dispute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPaymentID", ctx, paymentID)
	ret0, _ := ret[0].(*entity.Dispute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPaymentID indicates an expected call of FindByPaymentID.
func (mr *MockDisputeRepositoryMockRecorder) FindByPaymentID(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPaymentID", reflect.TypeOf((*MockDisputeRepository)(nil).FindByPaymentID), ctx, paymentID)
}

// List mocks base method.
func (m *MockDisputeRepository) List(ctx context.Context, filters repository.DisputeFilters) ([]*entity.Dispute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filters)
	ret0, _ := ret[0].([]*entity.Dispute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDisputeRepositoryMockRecorder) List(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDisputeRepository)(nil).List), ctx, filters)
}

// Update mocks base method.
func (m *MockDisputeRepository) Update(ctx context.Context, dispute *entity.Dispute) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, dispute)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDisputeRepositoryMockRecorder) Update(ctx, dispute any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDisputeRepository)(nil).Update), ctx, dispute)
}

// WithTX mocks base method.
func (m *MockDisputeRepository) WithTX(tx repository.Tx) repository.DisputeRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTX", tx)
	ret0, _ := ret[0].(repository.DisputeRepository)
	return ret0
}

// WithTX indicates an expected call of WithTX.
func (mr *MockDisputeRepositoryMockRecorder) WithTX(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTX", reflect.TypeOf((*MockDisputeRepository)(nil).WithTX), tx)
}
