// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: ProductCache)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_product_cache.go -package=repository . ProductCache
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProductCache is a mock of ProductCache interface.
type MockProductCache struct {
	ctrl     *gomock.Controller
	recorder *MockProductCacheMockRecorder
	isgomock struct{}
}

// MockProductCacheMockRecorder is the mock recorder for MockProductCache.
type MockProductCacheMockRecorder struct {
	mock *MockProductCache
}

// NewMockProductCache creates a new mock instance.
func NewMockProductCache(ctrl *gomock.Controller) *MockProductCache {
	mock := &MockProductCache{ctrl: ctrl}
	mock.recorder = &MockProductCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductCache) EXPECT() *MockProductCacheMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockProductCache) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProductCacheMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProductCache)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockProductCache) Get(ctx context.Context, id string) (*entity.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*entity.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProductCacheMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProductCache)(nil).Get), ctx, id)
}

// Set mocks base method.
func (m *MockProductCache) Set(ctx context.Context, product *entity.Product, expirationSeconds int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, product, expirationSeconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockProductCacheMockRecorder) Set(ctx, product, expirationSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockProductCache)(nil).Set), ctx, product, expirationSeconds)
}
