// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: UploadTokenRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_upload_token_repository.go -package=repository . UploadTokenRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUploadTokenRepository is a mock of UploadTokenRepository interface.
type MockUploadTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUploadTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockUploadTokenRepositoryMockRecorder is the mock recorder for MockUploadTokenRepository.
type MockUploadTokenRepositoryMockRecorder struct {
	mock *MockUploadTokenRepository
}

// NewMockUploadTokenRepository creates a new mock instance.
func NewMockUploadTokenRepository(ctrl *gomock.Controller) *MockUploadTokenRepository {
	mock := &MockUploadTokenRepository{ctrl: ctrl}
	mock.recorder = &MockUploadTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadTokenRepository) EXPECT() *MockUploadTokenRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUploadTokenRepository) Create(ctx context.Context, token *entity.UploadToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUploadTokenRepositoryMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUploadTokenRepository)(nil).Create), ctx, token)
}

// DeleteByUser mocks base method.
func (m *MockUploadTokenRepository) DeleteByUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUser indicates an expected call of DeleteByUser.
func (mr *MockUploadTokenRepositoryMockRecorder) DeleteByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUser", reflect.TypeOf((*MockUploadTokenRepository)(nil).DeleteByUser), ctx, userID)
}

// DeleteExpired mocks base method.
func (m *MockUploadTokenRepository) DeleteExpired(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockUploadTokenRepositoryMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockUploadTokenRepository)(nil).DeleteExpired), ctx)
}

// FindByID mocks base method.
func (m *MockUploadTokenRepository) FindByID(ctx context.Context, tokenID string) (*entity.UploadToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, tokenID)
	ret0, _ := ret[0].(*entity.UploadToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUploadTokenRepositoryMockRecorder) FindByID(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUploadTokenRepository)(nil).FindByID), ctx, tokenID)
}

// MarkUsed mocks base method.
func (m *MockUploadTokenRepository) MarkUsed(ctx context.Context, tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUsed", ctx, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUsed indicates an expected call of MarkUsed.
func (mr *MockUploadTokenRepositoryMockRecorder) MarkUsed(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUsed", reflect.TypeOf((*MockUploadTokenRepository)(nil).MarkUsed), ctx, tokenID)
}
