// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: TontineVoucherRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_tontine_voucher_repository.go -package=repository . TontineVoucherRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTontineVoucherRepository is a mock of TontineVoucherRepository interface.
type MockTontineVoucherRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTontineVoucherRepositoryMockRecorder
	isgomock struct{}
}

// MockTontineVoucherRepositoryMockRecorder is the mock recorder for MockTontineVoucherRepository.
type MockTontineVoucherRepositoryMockRecorder struct {
	mock *MockTontineVoucherRepository
}

// NewMockTontineVoucherRepository creates a new mock instance.
func NewMockTontineVoucherRepository(ctrl *gomock.Controller) *MockTontineVoucherRepository {
	mock := &MockTontineVoucherRepository{ctrl: ctrl}
	mock.recorder = &MockTontineVoucherRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTontineVoucherRepository) EXPECT() *MockTontineVoucherRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTontineVoucherRepository) Create(ctx context.Context, voucher *entity.TontineVoucher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, voucher)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTontineVoucherRepositoryMockRecorder) Create(ctx, voucher any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTontineVoucherRepository)(nil).Create), ctx, voucher)
}

// ExpireOldVouchers mocks base method.
func (m *MockTontineVoucherRepository) ExpireOldVouchers(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireOldVouchers", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpireOldVouchers indicates an expected call of ExpireOldVouchers.
func (mr *MockTontineVoucherRepositoryMockRecorder) ExpireOldVouchers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireOldVouchers", reflect.TypeOf((*MockTontineVoucherRepository)(nil).ExpireOldVouchers), ctx)
}

// FindActiveByShopID mocks base method.
func (m *MockTontineVoucherRepository) FindActiveByShopID(ctx context.Context, shopID string) ([]*entity.TontineVoucher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.TontineVoucher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByShopID indicates an expected call of FindActiveByShopID.
func (mr *MockTontineVoucherRepositoryMockRecorder) FindActiveByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByShopID", reflect.TypeOf((*MockTontineVoucherRepository)(nil).FindActiveByShopID), ctx, shopID)
}

// FindByCode mocks base method.
func (m *MockTontineVoucherRepository) FindByCode(ctx context.Context, code string) (*entity.TontineVoucher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCode", ctx, code)
	ret0, _ := ret[0].(*entity.TontineVoucher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCode indicates an expected call of FindByCode.
func (mr *MockTontineVoucherRepositoryMockRecorder) FindByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCode", reflect.TypeOf((*MockTontineVoucherRepository)(nil).FindByCode), ctx, code)
}

// FindByCustomerID mocks base method.
func (m *MockTontineVoucherRepository) FindByCustomerID(ctx context.Context, customerID string) ([]*entity.TontineVoucher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCustomerID", ctx, customerID)
	ret0, _ := ret[0].([]*entity.TontineVoucher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCustomerID indicates an expected call of FindByCustomerID.
func (mr *MockTontineVoucherRepositoryMockRecorder) FindByCustomerID(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCustomerID", reflect.TypeOf((*MockTontineVoucherRepository)(nil).FindByCustomerID), ctx, customerID)
}

// FindByID mocks base method.
func (m *MockTontineVoucherRepository) FindByID(ctx context.Context, id string) (*entity.TontineVoucher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.TontineVoucher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTontineVoucherRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTontineVoucherRepository)(nil).FindByID), ctx, id)
}

// FindByParticipantAndCycle mocks base method.
func (m *MockTontineVoucherRepository) FindByParticipantAndCycle(ctx context.Context, participantID string, cycle int) (*entity.TontineVoucher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByParticipantAndCycle", ctx, participantID, cycle)
	ret0, _ := ret[0].(*entity.TontineVoucher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByParticipantAndCycle indicates an expected call of FindByParticipantAndCycle.
func (mr *MockTontineVoucherRepositoryMockRecorder) FindByParticipantAndCycle(ctx, participantID, cycle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByParticipantAndCycle", reflect.TypeOf((*MockTontineVoucherRepository)(nil).FindByParticipantAndCycle), ctx, participantID, cycle)
}

// FindByShopID mocks base method.
func (m *MockTontineVoucherRepository) FindByShopID(ctx context.Context, shopID string) ([]*entity.TontineVoucher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.TontineVoucher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShopID indicates an expected call of FindByShopID.
func (mr *MockTontineVoucherRepositoryMockRecorder) FindByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShopID", reflect.TypeOf((*MockTontineVoucherRepository)(nil).FindByShopID), ctx, shopID)
}

// Redeem mocks base method.
func (m *MockTontineVoucherRepository) Redeem(ctx context.Context, voucherCode, redeemedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Redeem", ctx, voucherCode, redeemedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// Redeem indicates an expected call of Redeem.
func (mr *MockTontineVoucherRepositoryMockRecorder) Redeem(ctx, voucherCode, redeemedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Redeem", reflect.TypeOf((*MockTontineVoucherRepository)(nil).Redeem), ctx, voucherCode, redeemedBy)
}

// WithTX mocks base method.
func (m *MockTontineVoucherRepository) WithTX(tx repository.Tx) repository.TontineVoucherRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTX", tx)
	ret0, _ := ret[0].(repository.TontineVoucherRepository)
	return ret0
}

// WithTX indicates an expected call of WithTX.
func (mr *MockTontineVoucherRepositoryMockRecorder) WithTX(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTX", reflect.TypeOf((*MockTontineVoucherRepository)(nil).WithTX), tx)
}
