// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: TontinePaymentRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_tontine_payment_repository.go -package=repository . TontinePaymentRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTontinePaymentRepository is a mock of TontinePaymentRepository interface.
type MockTontinePaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTontinePaymentRepositoryMockRecorder
	isgomock struct{}
}

// MockTontinePaymentRepositoryMockRecorder is the mock recorder for MockTontinePaymentRepository.
type MockTontinePaymentRepositoryMockRecorder struct {
	mock *MockTontinePaymentRepository
}

// NewMockTontinePaymentRepository creates a new mock instance.
func NewMockTontinePaymentRepository(ctrl *gomock.Controller) *MockTontinePaymentRepository {
	mock := &MockTontinePaymentRepository{ctrl: ctrl}
	mock.recorder = &MockTontinePaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTontinePaymentRepository) EXPECT() *MockTontinePaymentRepositoryMockRecorder {
	return m.recorder
}

// CountDoneByGroupAndCycle mocks base method.
func (m *MockTontinePaymentRepository) CountDoneByGroupAndCycle(ctx context.Context, groupID string, cycle int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDoneByGroupAndCycle", ctx, groupID, cycle)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDoneByGroupAndCycle indicates an expected call of CountDoneByGroupAndCycle.
func (mr *MockTontinePaymentRepositoryMockRecorder) CountDoneByGroupAndCycle(ctx, groupID, cycle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDoneByGroupAndCycle", reflect.TypeOf((*MockTontinePaymentRepository)(nil).CountDoneByGroupAndCycle), ctx, groupID, cycle)
}

// Create mocks base method.
func (m *MockTontinePaymentRepository) Create(ctx context.Context, payment *entity.TontinePayment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTontinePaymentRepositoryMockRecorder) Create(ctx, payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTontinePaymentRepository)(nil).Create), ctx, payment)
}

// FindByCustomerAndGroup mocks base method.
func (m *MockTontinePaymentRepository) FindByCustomerAndGroup(ctx context.Context, customerID, groupID string) ([]*entity.TontinePayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCustomerAndGroup", ctx, customerID, groupID)
	ret0, _ := ret[0].([]*entity.TontinePayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCustomerAndGroup indicates an expected call of FindByCustomerAndGroup.
func (mr *MockTontinePaymentRepositoryMockRecorder) FindByCustomerAndGroup(ctx, customerID, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCustomerAndGroup", reflect.TypeOf((*MockTontinePaymentRepository)(nil).FindByCustomerAndGroup), ctx, customerID, groupID)
}

// FindByGroupAndCycle mocks base method.
func (m *MockTontinePaymentRepository) FindByGroupAndCycle(ctx context.Context, groupID string, cycle int) ([]*entity.TontinePayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByGroupAndCycle", ctx, groupID, cycle)
	ret0, _ := ret[0].([]*entity.TontinePayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByGroupAndCycle indicates an expected call of FindByGroupAndCycle.
func (mr *MockTontinePaymentRepositoryMockRecorder) FindByGroupAndCycle(ctx, groupID, cycle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByGroupAndCycle", reflect.TypeOf((*MockTontinePaymentRepository)(nil).FindByGroupAndCycle), ctx, groupID, cycle)
}

// FindByID mocks base method.
func (m *MockTontinePaymentRepository) FindByID(ctx context.Context, id string) (*entity.TontinePayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.TontinePayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTontinePaymentRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTontinePaymentRepository)(nil).FindByID), ctx, id)
}

// FindByIDUnscoped mocks base method.
func (m *MockTontinePaymentRepository) FindByIDUnscoped(ctx context.Context, id string) (*entity.TontinePayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDUnscoped", ctx, id)
	ret0, _ := ret[0].(*entity.TontinePayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDUnscoped indicates an expected call of FindByIDUnscoped.
func (mr *MockTontinePaymentRepositoryMockRecorder) FindByIDUnscoped(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDUnscoped", reflect.TypeOf((*MockTontinePaymentRepository)(nil).FindByIDUnscoped), ctx, id)
}

// FindByIDUnscopedForUpdate mocks base method.
func (m *MockTontinePaymentRepository) FindByIDUnscopedForUpdate(ctx context.Context, id string) (*entity.TontinePayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDUnscopedForUpdate", ctx, id)
	ret0, _ := ret[0].(*entity.TontinePayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDUnscopedForUpdate indicates an expected call of FindByIDUnscopedForUpdate.
func (mr *MockTontinePaymentRepositoryMockRecorder) FindByIDUnscopedForUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDUnscopedForUpdate", reflect.TypeOf((*MockTontinePaymentRepository)(nil).FindByIDUnscopedForUpdate), ctx, id)
}

// FindByParticipantAndCycle mocks base method.
func (m *MockTontinePaymentRepository) FindByParticipantAndCycle(ctx context.Context, participantID string, cycle int) (*entity.TontinePayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByParticipantAndCycle", ctx, participantID, cycle)
	ret0, _ := ret[0].(*entity.TontinePayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByParticipantAndCycle indicates an expected call of FindByParticipantAndCycle.
func (mr *MockTontinePaymentRepositoryMockRecorder) FindByParticipantAndCycle(ctx, participantID, cycle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByParticipantAndCycle", reflect.TypeOf((*MockTontinePaymentRepository)(nil).FindByParticipantAndCycle), ctx, participantID, cycle)
}

// FindByParticipantAndCycleForUpdate mocks base method.
func (m *MockTontinePaymentRepository) FindByParticipantAndCycleForUpdate(ctx context.Context, participantID string, cycle int) (*entity.TontinePayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByParticipantAndCycleForUpdate", ctx, participantID, cycle)
	ret0, _ := ret[0].(*entity.TontinePayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByParticipantAndCycleForUpdate indicates an expected call of FindByParticipantAndCycleForUpdate.
func (mr *MockTontinePaymentRepositoryMockRecorder) FindByParticipantAndCycleForUpdate(ctx, participantID, cycle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByParticipantAndCycleForUpdate", reflect.TypeOf((*MockTontinePaymentRepository)(nil).FindByParticipantAndCycleForUpdate), ctx, participantID, cycle)
}

// FindByReference mocks base method.
func (m *MockTontinePaymentRepository) FindByReference(ctx context.Context, reference string) (*entity.TontinePayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByReference", ctx, reference)
	ret0, _ := ret[0].(*entity.TontinePayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByReference indicates an expected call of FindByReference.
func (mr *MockTontinePaymentRepositoryMockRecorder) FindByReference(ctx, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByReference", reflect.TypeOf((*MockTontinePaymentRepository)(nil).FindByReference), ctx, reference)
}

// FindByReferencePrefix mocks base method.
func (m *MockTontinePaymentRepository) FindByReferencePrefix(ctx context.Context, referencePrefix string) (*entity.TontinePayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByReferencePrefix", ctx, referencePrefix)
	ret0, _ := ret[0].(*entity.TontinePayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByReferencePrefix indicates an expected call of FindByReferencePrefix.
func (mr *MockTontinePaymentRepositoryMockRecorder) FindByReferencePrefix(ctx, referencePrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByReferencePrefix", reflect.TypeOf((*MockTontinePaymentRepository)(nil).FindByReferencePrefix), ctx, referencePrefix)
}

// FindByReferenceUnscoped mocks base method.
func (m *MockTontinePaymentRepository) FindByReferenceUnscoped(ctx context.Context, reference string) (*entity.TontinePayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByReferenceUnscoped", ctx, reference)
	ret0, _ := ret[0].(*entity.TontinePayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByReferenceUnscoped indicates an expected call of FindByReferenceUnscoped.
func (mr *MockTontinePaymentRepositoryMockRecorder) FindByReferenceUnscoped(ctx, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByReferenceUnscoped", reflect.TypeOf((*MockTontinePaymentRepository)(nil).FindByReferenceUnscoped), ctx, reference)
}

// FindByReferenceUnscopedForUpdate mocks base method.
func (m *MockTontinePaymentRepository) FindByReferenceUnscopedForUpdate(ctx context.Context, reference string) (*entity.TontinePayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByReferenceUnscopedForUpdate", ctx, reference)
	ret0, _ := ret[0].(*entity.TontinePayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByReferenceUnscopedForUpdate indicates an expected call of FindByReferenceUnscopedForUpdate.
func (mr *MockTontinePaymentRepositoryMockRecorder) FindByReferenceUnscopedForUpdate(ctx, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByReferenceUnscopedForUpdate", reflect.TypeOf((*MockTontinePaymentRepository)(nil).FindByReferenceUnscopedForUpdate), ctx, reference)
}

// FindDoneWithoutCommission mocks base method.
func (m *MockTontinePaymentRepository) FindDoneWithoutCommission(ctx context.Context, limit int) ([]*entity.TontinePayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDoneWithoutCommission", ctx, limit)
	ret0, _ := ret[0].([]*entity.TontinePayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDoneWithoutCommission indicates an expected call of FindDoneWithoutCommission.
func (mr *MockTontinePaymentRepositoryMockRecorder) FindDoneWithoutCommission(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDoneWithoutCommission", reflect.TypeOf((*MockTontinePaymentRepository)(nil).FindDoneWithoutCommission), ctx, limit)
}

// MarkDone mocks base method.
func (m *MockTontinePaymentRepository) MarkDone(ctx context.Context, paymentID, transactionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDone", ctx, paymentID, transactionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDone indicates an expected call of MarkDone.
func (mr *MockTontinePaymentRepositoryMockRecorder) MarkDone(ctx, paymentID, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDone", reflect.TypeOf((*MockTontinePaymentRepository)(nil).MarkDone), ctx, paymentID, transactionID)
}

// SetProviderIntentID mocks base method.
func (m *MockTontinePaymentRepository) SetProviderIntentID(ctx context.Context, id, intentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProviderIntentID", ctx, id, intentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProviderIntentID indicates an expected call of SetProviderIntentID.
func (mr *MockTontinePaymentRepositoryMockRecorder) SetProviderIntentID(ctx, id, intentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProviderIntentID", reflect.TypeOf((*MockTontinePaymentRepository)(nil).SetProviderIntentID), ctx, id, intentID)
}

// UpdateStatus mocks base method.
func (m *MockTontinePaymentRepository) UpdateStatus(ctx context.Context, paymentID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, paymentID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockTontinePaymentRepositoryMockRecorder) UpdateStatus(ctx, paymentID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockTontinePaymentRepository)(nil).UpdateStatus), ctx, paymentID, status)
}

// UpdateTontineCommissionStatus mocks base method.
func (m *MockTontinePaymentRepository) UpdateTontineCommissionStatus(ctx context.Context, paymentID, status string, batchID *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTontineCommissionStatus", ctx, paymentID, status, batchID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTontineCommissionStatus indicates an expected call of UpdateTontineCommissionStatus.
func (mr *MockTontinePaymentRepositoryMockRecorder) UpdateTontineCommissionStatus(ctx, paymentID, status, batchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTontineCommissionStatus", reflect.TypeOf((*MockTontinePaymentRepository)(nil).UpdateTontineCommissionStatus), ctx, paymentID, status, batchID)
}

// WithTX mocks base method.
func (m *MockTontinePaymentRepository) WithTX(tx repository.Tx) repository.TontinePaymentRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTX", tx)
	ret0, _ := ret[0].(repository.TontinePaymentRepository)
	return ret0
}

// WithTX indicates an expected call of WithTX.
func (mr *MockTontinePaymentRepositoryMockRecorder) WithTX(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTX", reflect.TypeOf((*MockTontinePaymentRepository)(nil).WithTX), tx)
}
