// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: AccountFreezeRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_account_freeze_repository.go -package=repository . AccountFreezeRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockAccountFreezeRepository is a mock of AccountFreezeRepository interface.
type MockAccountFreezeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountFreezeRepositoryMockRecorder
	isgomock struct{}
}

// MockAccountFreezeRepositoryMockRecorder is the mock recorder for MockAccountFreezeRepository.
type MockAccountFreezeRepositoryMockRecorder struct {
	mock *MockAccountFreezeRepository
}

// NewMockAccountFreezeRepository creates a new mock instance.
func NewMockAccountFreezeRepository(ctrl *gomock.Controller) *MockAccountFreezeRepository {
	mock := &MockAccountFreezeRepository{ctrl: ctrl}
	mock.recorder = &MockAccountFreezeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountFreezeRepository) EXPECT() *MockAccountFreezeRepositoryMockRecorder {
	return m.recorder
}

// CountActive mocks base method.
func (m *MockAccountFreezeRepository) CountActive(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActive", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActive indicates an expected call of CountActive.
func (mr *MockAccountFreezeRepositoryMockRecorder) CountActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActive", reflect.TypeOf((*MockAccountFreezeRepository)(nil).CountActive), ctx)
}

// CountByReason mocks base method.
func (m *MockAccountFreezeRepository) CountByReason(ctx context.Context, reason entity.FreezeReason) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByReason", ctx, reason)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByReason indicates an expected call of CountByReason.
func (mr *MockAccountFreezeRepositoryMockRecorder) CountByReason(ctx, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByReason", reflect.TypeOf((*MockAccountFreezeRepository)(nil).CountByReason), ctx, reason)
}

// CountByResolution mocks base method.
func (m *MockAccountFreezeRepository) CountByResolution(ctx context.Context, resolution entity.FreezeResolution) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByResolution", ctx, resolution)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByResolution indicates an expected call of CountByResolution.
func (mr *MockAccountFreezeRepositoryMockRecorder) CountByResolution(ctx, resolution any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByResolution", reflect.TypeOf((*MockAccountFreezeRepository)(nil).CountByResolution), ctx, resolution)
}

// CountGracePeriodExpired mocks base method.
func (m *MockAccountFreezeRepository) CountGracePeriodExpired(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountGracePeriodExpired", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountGracePeriodExpired indicates an expected call of CountGracePeriodExpired.
func (mr *MockAccountFreezeRepositoryMockRecorder) CountGracePeriodExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountGracePeriodExpired", reflect.TypeOf((*MockAccountFreezeRepository)(nil).CountGracePeriodExpired), ctx)
}

// CountResolved mocks base method.
func (m *MockAccountFreezeRepository) CountResolved(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountResolved", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountResolved indicates an expected call of CountResolved.
func (mr *MockAccountFreezeRepositoryMockRecorder) CountResolved(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountResolved", reflect.TypeOf((*MockAccountFreezeRepository)(nil).CountResolved), ctx)
}

// Create mocks base method.
func (m *MockAccountFreezeRepository) Create(ctx context.Context, freeze *entity.AccountFreeze) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, freeze)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAccountFreezeRepositoryMockRecorder) Create(ctx, freeze any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountFreezeRepository)(nil).Create), ctx, freeze)
}

// FindActive mocks base method.
func (m *MockAccountFreezeRepository) FindActive(ctx context.Context) ([]*entity.AccountFreeze, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActive", ctx)
	ret0, _ := ret[0].([]*entity.AccountFreeze)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActive indicates an expected call of FindActive.
func (mr *MockAccountFreezeRepositoryMockRecorder) FindActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActive", reflect.TypeOf((*MockAccountFreezeRepository)(nil).FindActive), ctx)
}

// FindActiveByShopID mocks base method.
func (m *MockAccountFreezeRepository) FindActiveByShopID(ctx context.Context, shopID string) (*entity.AccountFreeze, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByShopID", ctx, shopID)
	ret0, _ := ret[0].(*entity.AccountFreeze)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByShopID indicates an expected call of FindActiveByShopID.
func (mr *MockAccountFreezeRepositoryMockRecorder) FindActiveByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByShopID", reflect.TypeOf((*MockAccountFreezeRepository)(nil).FindActiveByShopID), ctx, shopID)
}

// FindAll mocks base method.
func (m *MockAccountFreezeRepository) FindAll(ctx context.Context) ([]*entity.AccountFreeze, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*entity.AccountFreeze)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockAccountFreezeRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockAccountFreezeRepository)(nil).FindAll), ctx)
}

// FindByID mocks base method.
func (m *MockAccountFreezeRepository) FindByID(ctx context.Context, id string) (*entity.AccountFreeze, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.AccountFreeze)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAccountFreezeRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAccountFreezeRepository)(nil).FindByID), ctx, id)
}

// FindByReason mocks base method.
func (m *MockAccountFreezeRepository) FindByReason(ctx context.Context, reason entity.FreezeReason) ([]*entity.AccountFreeze, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByReason", ctx, reason)
	ret0, _ := ret[0].([]*entity.AccountFreeze)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByReason indicates an expected call of FindByReason.
func (mr *MockAccountFreezeRepositoryMockRecorder) FindByReason(ctx, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByReason", reflect.TypeOf((*MockAccountFreezeRepository)(nil).FindByReason), ctx, reason)
}

// FindByResolution mocks base method.
func (m *MockAccountFreezeRepository) FindByResolution(ctx context.Context, resolution entity.FreezeResolution) ([]*entity.AccountFreeze, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByResolution", ctx, resolution)
	ret0, _ := ret[0].([]*entity.AccountFreeze)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByResolution indicates an expected call of FindByResolution.
func (mr *MockAccountFreezeRepositoryMockRecorder) FindByResolution(ctx, resolution any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByResolution", reflect.TypeOf((*MockAccountFreezeRepository)(nil).FindByResolution), ctx, resolution)
}

// FindByShopID mocks base method.
func (m *MockAccountFreezeRepository) FindByShopID(ctx context.Context, shopID string) (*entity.AccountFreeze, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShopID", ctx, shopID)
	ret0, _ := ret[0].(*entity.AccountFreeze)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShopID indicates an expected call of FindByShopID.
func (mr *MockAccountFreezeRepositoryMockRecorder) FindByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShopID", reflect.TypeOf((*MockAccountFreezeRepository)(nil).FindByShopID), ctx, shopID)
}

// FindGracePeriodExpired mocks base method.
func (m *MockAccountFreezeRepository) FindGracePeriodExpired(ctx context.Context) ([]*entity.AccountFreeze, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindGracePeriodExpired", ctx)
	ret0, _ := ret[0].([]*entity.AccountFreeze)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindGracePeriodExpired indicates an expected call of FindGracePeriodExpired.
func (mr *MockAccountFreezeRepositoryMockRecorder) FindGracePeriodExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindGracePeriodExpired", reflect.TypeOf((*MockAccountFreezeRepository)(nil).FindGracePeriodExpired), ctx)
}

// FindGracePeriodExpiringSoon mocks base method.
func (m *MockAccountFreezeRepository) FindGracePeriodExpiringSoon(ctx context.Context, daysRemaining int) ([]*entity.AccountFreeze, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindGracePeriodExpiringSoon", ctx, daysRemaining)
	ret0, _ := ret[0].([]*entity.AccountFreeze)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindGracePeriodExpiringSoon indicates an expected call of FindGracePeriodExpiringSoon.
func (mr *MockAccountFreezeRepositoryMockRecorder) FindGracePeriodExpiringSoon(ctx, daysRemaining any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindGracePeriodExpiringSoon", reflect.TypeOf((*MockAccountFreezeRepository)(nil).FindGracePeriodExpiringSoon), ctx, daysRemaining)
}

// FindHighValue mocks base method.
func (m *MockAccountFreezeRepository) FindHighValue(ctx context.Context, minAmountCents int64) ([]*entity.AccountFreeze, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindHighValue", ctx, minAmountCents)
	ret0, _ := ret[0].([]*entity.AccountFreeze)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindHighValue indicates an expected call of FindHighValue.
func (mr *MockAccountFreezeRepositoryMockRecorder) FindHighValue(ctx, minAmountCents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindHighValue", reflect.TypeOf((*MockAccountFreezeRepository)(nil).FindHighValue), ctx, minAmountCents)
}

// FindNeedsReminder1 mocks base method.
func (m *MockAccountFreezeRepository) FindNeedsReminder1(ctx context.Context) ([]*entity.AccountFreeze, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNeedsReminder1", ctx)
	ret0, _ := ret[0].([]*entity.AccountFreeze)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNeedsReminder1 indicates an expected call of FindNeedsReminder1.
func (mr *MockAccountFreezeRepositoryMockRecorder) FindNeedsReminder1(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNeedsReminder1", reflect.TypeOf((*MockAccountFreezeRepository)(nil).FindNeedsReminder1), ctx)
}

// FindNeedsReminder2 mocks base method.
func (m *MockAccountFreezeRepository) FindNeedsReminder2(ctx context.Context) ([]*entity.AccountFreeze, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNeedsReminder2", ctx)
	ret0, _ := ret[0].([]*entity.AccountFreeze)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNeedsReminder2 indicates an expected call of FindNeedsReminder2.
func (mr *MockAccountFreezeRepositoryMockRecorder) FindNeedsReminder2(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNeedsReminder2", reflect.TypeOf((*MockAccountFreezeRepository)(nil).FindNeedsReminder2), ctx)
}

// FindNeedsReminder3 mocks base method.
func (m *MockAccountFreezeRepository) FindNeedsReminder3(ctx context.Context) ([]*entity.AccountFreeze, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNeedsReminder3", ctx)
	ret0, _ := ret[0].([]*entity.AccountFreeze)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNeedsReminder3 indicates an expected call of FindNeedsReminder3.
func (mr *MockAccountFreezeRepositoryMockRecorder) FindNeedsReminder3(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNeedsReminder3", reflect.TypeOf((*MockAccountFreezeRepository)(nil).FindNeedsReminder3), ctx)
}

// FindNeedsSuspension mocks base method.
func (m *MockAccountFreezeRepository) FindNeedsSuspension(ctx context.Context) ([]*entity.AccountFreeze, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNeedsSuspension", ctx)
	ret0, _ := ret[0].([]*entity.AccountFreeze)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNeedsSuspension indicates an expected call of FindNeedsSuspension.
func (mr *MockAccountFreezeRepositoryMockRecorder) FindNeedsSuspension(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNeedsSuspension", reflect.TypeOf((*MockAccountFreezeRepository)(nil).FindNeedsSuspension), ctx)
}

// FindResolved mocks base method.
func (m *MockAccountFreezeRepository) FindResolved(ctx context.Context) ([]*entity.AccountFreeze, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindResolved", ctx)
	ret0, _ := ret[0].([]*entity.AccountFreeze)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindResolved indicates an expected call of FindResolved.
func (mr *MockAccountFreezeRepositoryMockRecorder) FindResolved(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindResolved", reflect.TypeOf((*MockAccountFreezeRepository)(nil).FindResolved), ctx)
}

// ResolveEscalated mocks base method.
func (m *MockAccountFreezeRepository) ResolveEscalated(ctx context.Context, id, resolvedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveEscalated", ctx, id, resolvedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveEscalated indicates an expected call of ResolveEscalated.
func (mr *MockAccountFreezeRepositoryMockRecorder) ResolveEscalated(ctx, id, resolvedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveEscalated", reflect.TypeOf((*MockAccountFreezeRepository)(nil).ResolveEscalated), ctx, id, resolvedBy)
}

// ResolvePaid mocks base method.
func (m *MockAccountFreezeRepository) ResolvePaid(ctx context.Context, id, resolvedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolvePaid", ctx, id, resolvedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolvePaid indicates an expected call of ResolvePaid.
func (mr *MockAccountFreezeRepositoryMockRecorder) ResolvePaid(ctx, id, resolvedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolvePaid", reflect.TypeOf((*MockAccountFreezeRepository)(nil).ResolvePaid), ctx, id, resolvedBy)
}

// ResolveSuspended mocks base method.
func (m *MockAccountFreezeRepository) ResolveSuspended(ctx context.Context, id, resolvedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveSuspended", ctx, id, resolvedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveSuspended indicates an expected call of ResolveSuspended.
func (mr *MockAccountFreezeRepositoryMockRecorder) ResolveSuspended(ctx, id, resolvedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveSuspended", reflect.TypeOf((*MockAccountFreezeRepository)(nil).ResolveSuspended), ctx, id, resolvedBy)
}

// ResolveWaived mocks base method.
func (m *MockAccountFreezeRepository) ResolveWaived(ctx context.Context, id, resolvedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveWaived", ctx, id, resolvedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveWaived indicates an expected call of ResolveWaived.
func (mr *MockAccountFreezeRepositoryMockRecorder) ResolveWaived(ctx, id, resolvedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveWaived", reflect.TypeOf((*MockAccountFreezeRepository)(nil).ResolveWaived), ctx, id, resolvedBy)
}

// SumAmountDueActive mocks base method.
func (m *MockAccountFreezeRepository) SumAmountDueActive(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumAmountDueActive", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumAmountDueActive indicates an expected call of SumAmountDueActive.
func (mr *MockAccountFreezeRepositoryMockRecorder) SumAmountDueActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumAmountDueActive", reflect.TypeOf((*MockAccountFreezeRepository)(nil).SumAmountDueActive), ctx)
}

// SumAmountDueByReason mocks base method.
func (m *MockAccountFreezeRepository) SumAmountDueByReason(ctx context.Context, reason entity.FreezeReason) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumAmountDueByReason", ctx, reason)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumAmountDueByReason indicates an expected call of SumAmountDueByReason.
func (mr *MockAccountFreezeRepositoryMockRecorder) SumAmountDueByReason(ctx, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumAmountDueByReason", reflect.TypeOf((*MockAccountFreezeRepository)(nil).SumAmountDueByReason), ctx, reason)
}

// SumAmountDueResolved mocks base method.
func (m *MockAccountFreezeRepository) SumAmountDueResolved(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumAmountDueResolved", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumAmountDueResolved indicates an expected call of SumAmountDueResolved.
func (mr *MockAccountFreezeRepositoryMockRecorder) SumAmountDueResolved(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumAmountDueResolved", reflect.TypeOf((*MockAccountFreezeRepository)(nil).SumAmountDueResolved), ctx)
}

// SumTotalAmountDue mocks base method.
func (m *MockAccountFreezeRepository) SumTotalAmountDue(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumTotalAmountDue", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumTotalAmountDue indicates an expected call of SumTotalAmountDue.
func (mr *MockAccountFreezeRepositoryMockRecorder) SumTotalAmountDue(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumTotalAmountDue", reflect.TypeOf((*MockAccountFreezeRepository)(nil).SumTotalAmountDue), ctx)
}

// Update mocks base method.
func (m *MockAccountFreezeRepository) Update(ctx context.Context, freeze *entity.AccountFreeze) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, freeze)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAccountFreezeRepositoryMockRecorder) Update(ctx, freeze any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccountFreezeRepository)(nil).Update), ctx, freeze)
}

// UpdateReminder1 mocks base method.
func (m *MockAccountFreezeRepository) UpdateReminder1(ctx context.Context, id string, sentAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReminder1", ctx, id, sentAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReminder1 indicates an expected call of UpdateReminder1.
func (mr *MockAccountFreezeRepositoryMockRecorder) UpdateReminder1(ctx, id, sentAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReminder1", reflect.TypeOf((*MockAccountFreezeRepository)(nil).UpdateReminder1), ctx, id, sentAt)
}

// UpdateReminder2 mocks base method.
func (m *MockAccountFreezeRepository) UpdateReminder2(ctx context.Context, id string, sentAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReminder2", ctx, id, sentAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReminder2 indicates an expected call of UpdateReminder2.
func (mr *MockAccountFreezeRepositoryMockRecorder) UpdateReminder2(ctx, id, sentAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReminder2", reflect.TypeOf((*MockAccountFreezeRepository)(nil).UpdateReminder2), ctx, id, sentAt)
}

// UpdateReminder3 mocks base method.
func (m *MockAccountFreezeRepository) UpdateReminder3(ctx context.Context, id string, sentAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReminder3", ctx, id, sentAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReminder3 indicates an expected call of UpdateReminder3.
func (mr *MockAccountFreezeRepositoryMockRecorder) UpdateReminder3(ctx, id, sentAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReminder3", reflect.TypeOf((*MockAccountFreezeRepository)(nil).UpdateReminder3), ctx, id, sentAt)
}

// UpdateResolution mocks base method.
func (m *MockAccountFreezeRepository) UpdateResolution(ctx context.Context, id string, resolution entity.FreezeResolution, resolvedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResolution", ctx, id, resolution, resolvedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateResolution indicates an expected call of UpdateResolution.
func (mr *MockAccountFreezeRepositoryMockRecorder) UpdateResolution(ctx, id, resolution, resolvedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResolution", reflect.TypeOf((*MockAccountFreezeRepository)(nil).UpdateResolution), ctx, id, resolution, resolvedBy)
}

// WithTX mocks base method.
func (m *MockAccountFreezeRepository) WithTX(tx repository.Tx) repository.AccountFreezeRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTX", tx)
	ret0, _ := ret[0].(repository.AccountFreezeRepository)
	return ret0
}

// WithTX indicates an expected call of WithTX.
func (mr *MockAccountFreezeRepositoryMockRecorder) WithTX(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTX", reflect.TypeOf((*MockAccountFreezeRepository)(nil).WithTX), tx)
}
