// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: CreditPlanRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_credit_plan_repository.go -package=repository . CreditPlanRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreditPlanRepository is a mock of CreditPlanRepository interface.
type MockCreditPlanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCreditPlanRepositoryMockRecorder
	isgomock struct{}
}

// MockCreditPlanRepositoryMockRecorder is the mock recorder for MockCreditPlanRepository.
type MockCreditPlanRepositoryMockRecorder struct {
	mock *MockCreditPlanRepository
}

// NewMockCreditPlanRepository creates a new mock instance.
func NewMockCreditPlanRepository(ctrl *gomock.Controller) *MockCreditPlanRepository {
	mock := &MockCreditPlanRepository{ctrl: ctrl}
	mock.recorder = &MockCreditPlanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreditPlanRepository) EXPECT() *MockCreditPlanRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCreditPlanRepository) Create(ctx context.Context, plan *entity.CreditPlan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, plan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCreditPlanRepositoryMockRecorder) Create(ctx, plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCreditPlanRepository)(nil).Create), ctx, plan)
}

// Delete mocks base method.
func (m *MockCreditPlanRepository) Delete(ctx context.Context, productID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCreditPlanRepositoryMockRecorder) Delete(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCreditPlanRepository)(nil).Delete), ctx, productID)
}

// FindByProductID mocks base method.
func (m *MockCreditPlanRepository) FindByProductID(ctx context.Context, productID string) (*entity.CreditPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProductID", ctx, productID)
	ret0, _ := ret[0].(*entity.CreditPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProductID indicates an expected call of FindByProductID.
func (mr *MockCreditPlanRepositoryMockRecorder) FindByProductID(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProductID", reflect.TypeOf((*MockCreditPlanRepository)(nil).FindByProductID), ctx, productID)
}

// FindByShopID mocks base method.
func (m *MockCreditPlanRepository) FindByShopID(ctx context.Context, shopID string) ([]*entity.CreditPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.CreditPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShopID indicates an expected call of FindByShopID.
func (mr *MockCreditPlanRepositoryMockRecorder) FindByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShopID", reflect.TypeOf((*MockCreditPlanRepository)(nil).FindByShopID), ctx, shopID)
}

// FindEnabledByShopID mocks base method.
func (m *MockCreditPlanRepository) FindEnabledByShopID(ctx context.Context, shopID string) ([]*entity.CreditPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindEnabledByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.CreditPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindEnabledByShopID indicates an expected call of FindEnabledByShopID.
func (mr *MockCreditPlanRepositoryMockRecorder) FindEnabledByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindEnabledByShopID", reflect.TypeOf((*MockCreditPlanRepository)(nil).FindEnabledByShopID), ctx, shopID)
}

// Update mocks base method.
func (m *MockCreditPlanRepository) Update(ctx context.Context, plan *entity.CreditPlan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, plan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCreditPlanRepositoryMockRecorder) Update(ctx, plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCreditPlanRepository)(nil).Update), ctx, plan)
}

// Upsert mocks base method.
func (m *MockCreditPlanRepository) Upsert(ctx context.Context, plan *entity.CreditPlan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, plan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockCreditPlanRepositoryMockRecorder) Upsert(ctx, plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockCreditPlanRepository)(nil).Upsert), ctx, plan)
}

// WithTX mocks base method.
func (m *MockCreditPlanRepository) WithTX(tx repository.Tx) repository.CreditPlanRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTX", tx)
	ret0, _ := ret[0].(repository.CreditPlanRepository)
	return ret0
}

// WithTX indicates an expected call of WithTX.
func (mr *MockCreditPlanRepositoryMockRecorder) WithTX(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTX", reflect.TypeOf((*MockCreditPlanRepository)(nil).WithTX), tx)
}
