// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: EscrowAccountRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_escrow_account_repository.go -package=repository . EscrowAccountRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEscrowAccountRepository is a mock of EscrowAccountRepository interface.
type MockEscrowAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEscrowAccountRepositoryMockRecorder
	isgomock struct{}
}

// MockEscrowAccountRepositoryMockRecorder is the mock recorder for MockEscrowAccountRepository.
type MockEscrowAccountRepositoryMockRecorder struct {
	mock *MockEscrowAccountRepository
}

// NewMockEscrowAccountRepository creates a new mock instance.
func NewMockEscrowAccountRepository(ctrl *gomock.Controller) *MockEscrowAccountRepository {
	mock := &MockEscrowAccountRepository{ctrl: ctrl}
	mock.recorder = &MockEscrowAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEscrowAccountRepository) EXPECT() *MockEscrowAccountRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEscrowAccountRepository) Create(ctx context.Context, account *entity.EscrowAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEscrowAccountRepositoryMockRecorder) Create(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEscrowAccountRepository)(nil).Create), ctx, account)
}

// FindByCreditContractID mocks base method.
func (m *MockEscrowAccountRepository) FindByCreditContractID(ctx context.Context, contractID string) (*entity.EscrowAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCreditContractID", ctx, contractID)
	ret0, _ := ret[0].(*entity.EscrowAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCreditContractID indicates an expected call of FindByCreditContractID.
func (mr *MockEscrowAccountRepositoryMockRecorder) FindByCreditContractID(ctx, contractID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCreditContractID", reflect.TypeOf((*MockEscrowAccountRepository)(nil).FindByCreditContractID), ctx, contractID)
}

// FindByID mocks base method.
func (m *MockEscrowAccountRepository) FindByID(ctx context.Context, id string) (*entity.EscrowAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.EscrowAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockEscrowAccountRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockEscrowAccountRepository)(nil).FindByID), ctx, id)
}

// FindByOrderID mocks base method.
func (m *MockEscrowAccountRepository) FindByOrderID(ctx context.Context, orderID string) (*entity.EscrowAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*entity.EscrowAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOrderID indicates an expected call of FindByOrderID.
func (mr *MockEscrowAccountRepositoryMockRecorder) FindByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOrderID", reflect.TypeOf((*MockEscrowAccountRepository)(nil).FindByOrderID), ctx, orderID)
}

// FindByReferenceID mocks base method.
func (m *MockEscrowAccountRepository) FindByReferenceID(ctx context.Context, sourceType entity.EscrowSourceType, referenceID string) (*entity.EscrowAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByReferenceID", ctx, sourceType, referenceID)
	ret0, _ := ret[0].(*entity.EscrowAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByReferenceID indicates an expected call of FindByReferenceID.
func (mr *MockEscrowAccountRepositoryMockRecorder) FindByReferenceID(ctx, sourceType, referenceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByReferenceID", reflect.TypeOf((*MockEscrowAccountRepository)(nil).FindByReferenceID), ctx, sourceType, referenceID)
}

// FindByStatus mocks base method.
func (m *MockEscrowAccountRepository) FindByStatus(ctx context.Context, status entity.EscrowAccountStatus) ([]*entity.EscrowAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByStatus", ctx, status)
	ret0, _ := ret[0].([]*entity.EscrowAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByStatus indicates an expected call of FindByStatus.
func (mr *MockEscrowAccountRepositoryMockRecorder) FindByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByStatus", reflect.TypeOf((*MockEscrowAccountRepository)(nil).FindByStatus), ctx, status)
}

// FindByTontineGroupID mocks base method.
func (m *MockEscrowAccountRepository) FindByTontineGroupID(ctx context.Context, groupID string) (*entity.EscrowAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTontineGroupID", ctx, groupID)
	ret0, _ := ret[0].(*entity.EscrowAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTontineGroupID indicates an expected call of FindByTontineGroupID.
func (mr *MockEscrowAccountRepositoryMockRecorder) FindByTontineGroupID(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTontineGroupID", reflect.TypeOf((*MockEscrowAccountRepository)(nil).FindByTontineGroupID), ctx, groupID)
}

// FindDisputedByShopID mocks base method.
func (m *MockEscrowAccountRepository) FindDisputedByShopID(ctx context.Context, shopID string) ([]*entity.EscrowAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDisputedByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.EscrowAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDisputedByShopID indicates an expected call of FindDisputedByShopID.
func (mr *MockEscrowAccountRepositoryMockRecorder) FindDisputedByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDisputedByShopID", reflect.TypeOf((*MockEscrowAccountRepository)(nil).FindDisputedByShopID), ctx, shopID)
}

// FindHeldByShopID mocks base method.
func (m *MockEscrowAccountRepository) FindHeldByShopID(ctx context.Context, shopID string) ([]*entity.EscrowAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindHeldByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.EscrowAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindHeldByShopID indicates an expected call of FindHeldByShopID.
func (mr *MockEscrowAccountRepositoryMockRecorder) FindHeldByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindHeldByShopID", reflect.TypeOf((*MockEscrowAccountRepository)(nil).FindHeldByShopID), ctx, shopID)
}

// SumHeldAmountByShopID mocks base method.
func (m *MockEscrowAccountRepository) SumHeldAmountByShopID(ctx context.Context, shopID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumHeldAmountByShopID", ctx, shopID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumHeldAmountByShopID indicates an expected call of SumHeldAmountByShopID.
func (mr *MockEscrowAccountRepositoryMockRecorder) SumHeldAmountByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumHeldAmountByShopID", reflect.TypeOf((*MockEscrowAccountRepository)(nil).SumHeldAmountByShopID), ctx, shopID)
}

// SumTotalHeldAmount mocks base method.
func (m *MockEscrowAccountRepository) SumTotalHeldAmount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumTotalHeldAmount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumTotalHeldAmount indicates an expected call of SumTotalHeldAmount.
func (mr *MockEscrowAccountRepositoryMockRecorder) SumTotalHeldAmount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumTotalHeldAmount", reflect.TypeOf((*MockEscrowAccountRepository)(nil).SumTotalHeldAmount), ctx)
}

// Update mocks base method.
func (m *MockEscrowAccountRepository) Update(ctx context.Context, account *entity.EscrowAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockEscrowAccountRepositoryMockRecorder) Update(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEscrowAccountRepository)(nil).Update), ctx, account)
}

// UpdateStatus mocks base method.
func (m *MockEscrowAccountRepository) UpdateStatus(ctx context.Context, id string, status entity.EscrowAccountStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockEscrowAccountRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockEscrowAccountRepository)(nil).UpdateStatus), ctx, id, status)
}

// WithTX mocks base method.
func (m *MockEscrowAccountRepository) WithTX(tx repository.Tx) repository.EscrowAccountRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTX", tx)
	ret0, _ := ret[0].(repository.EscrowAccountRepository)
	return ret0
}

// WithTX indicates an expected call of WithTX.
func (mr *MockEscrowAccountRepositoryMockRecorder) WithTX(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTX", reflect.TypeOf((*MockEscrowAccountRepository)(nil).WithTX), tx)
}
