// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: ShopKYCDocumentRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_shop_kyc_document_repository.go -package=repository . ShopKYCDocumentRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockShopKYCDocumentRepository is a mock of ShopKYCDocumentRepository interface.
type MockShopKYCDocumentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShopKYCDocumentRepositoryMockRecorder
	isgomock struct{}
}

// MockShopKYCDocumentRepositoryMockRecorder is the mock recorder for MockShopKYCDocumentRepository.
type MockShopKYCDocumentRepositoryMockRecorder struct {
	mock *MockShopKYCDocumentRepository
}

// NewMockShopKYCDocumentRepository creates a new mock instance.
func NewMockShopKYCDocumentRepository(ctrl *gomock.Controller) *MockShopKYCDocumentRepository {
	mock := &MockShopKYCDocumentRepository{ctrl: ctrl}
	mock.recorder = &MockShopKYCDocumentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShopKYCDocumentRepository) EXPECT() *MockShopKYCDocumentRepositoryMockRecorder {
	return m.recorder
}

// CountByShopID mocks base method.
func (m *MockShopKYCDocumentRepository) CountByShopID(ctx context.Context, shopID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByShopID", ctx, shopID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByShopID indicates an expected call of CountByShopID.
func (mr *MockShopKYCDocumentRepositoryMockRecorder) CountByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByShopID", reflect.TypeOf((*MockShopKYCDocumentRepository)(nil).CountByShopID), ctx, shopID)
}

// CountPendingByShopID mocks base method.
func (m *MockShopKYCDocumentRepository) CountPendingByShopID(ctx context.Context, shopID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPendingByShopID", ctx, shopID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPendingByShopID indicates an expected call of CountPendingByShopID.
func (mr *MockShopKYCDocumentRepositoryMockRecorder) CountPendingByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPendingByShopID", reflect.TypeOf((*MockShopKYCDocumentRepository)(nil).CountPendingByShopID), ctx, shopID)
}

// Create mocks base method.
func (m *MockShopKYCDocumentRepository) Create(ctx context.Context, doc *entity.ShopKYCDocument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockShopKYCDocumentRepositoryMockRecorder) Create(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShopKYCDocumentRepository)(nil).Create), ctx, doc)
}

// Delete mocks base method.
func (m *MockShopKYCDocumentRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockShopKYCDocumentRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockShopKYCDocumentRepository)(nil).Delete), ctx, id)
}

// DeleteByShopID mocks base method.
func (m *MockShopKYCDocumentRepository) DeleteByShopID(ctx context.Context, shopID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByShopID", ctx, shopID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByShopID indicates an expected call of DeleteByShopID.
func (mr *MockShopKYCDocumentRepositoryMockRecorder) DeleteByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByShopID", reflect.TypeOf((*MockShopKYCDocumentRepository)(nil).DeleteByShopID), ctx, shopID)
}

// FindAllPending mocks base method.
func (m *MockShopKYCDocumentRepository) FindAllPending(ctx context.Context, limit, offset int) ([]*entity.ShopKYCDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllPending", ctx, limit, offset)
	ret0, _ := ret[0].([]*entity.ShopKYCDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllPending indicates an expected call of FindAllPending.
func (mr *MockShopKYCDocumentRepositoryMockRecorder) FindAllPending(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllPending", reflect.TypeOf((*MockShopKYCDocumentRepository)(nil).FindAllPending), ctx, limit, offset)
}

// FindByID mocks base method.
func (m *MockShopKYCDocumentRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.ShopKYCDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.ShopKYCDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockShopKYCDocumentRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockShopKYCDocumentRepository)(nil).FindByID), ctx, id)
}

// FindByShopID mocks base method.
func (m *MockShopKYCDocumentRepository) FindByShopID(ctx context.Context, shopID uuid.UUID) ([]*entity.ShopKYCDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.ShopKYCDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShopID indicates an expected call of FindByShopID.
func (mr *MockShopKYCDocumentRepositoryMockRecorder) FindByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShopID", reflect.TypeOf((*MockShopKYCDocumentRepository)(nil).FindByShopID), ctx, shopID)
}

// FindByTypeAndShop mocks base method.
func (m *MockShopKYCDocumentRepository) FindByTypeAndShop(ctx context.Context, shopID uuid.UUID, docType entity.ShopKYCDocumentType) (*entity.ShopKYCDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTypeAndShop", ctx, shopID, docType)
	ret0, _ := ret[0].(*entity.ShopKYCDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTypeAndShop indicates an expected call of FindByTypeAndShop.
func (mr *MockShopKYCDocumentRepositoryMockRecorder) FindByTypeAndShop(ctx, shopID, docType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTypeAndShop", reflect.TypeOf((*MockShopKYCDocumentRepository)(nil).FindByTypeAndShop), ctx, shopID, docType)
}

// FindPendingByShopID mocks base method.
func (m *MockShopKYCDocumentRepository) FindPendingByShopID(ctx context.Context, shopID uuid.UUID) ([]*entity.ShopKYCDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPendingByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.ShopKYCDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPendingByShopID indicates an expected call of FindPendingByShopID.
func (mr *MockShopKYCDocumentRepositoryMockRecorder) FindPendingByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPendingByShopID", reflect.TypeOf((*MockShopKYCDocumentRepository)(nil).FindPendingByShopID), ctx, shopID)
}

// Update mocks base method.
func (m *MockShopKYCDocumentRepository) Update(ctx context.Context, doc *entity.ShopKYCDocument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockShopKYCDocumentRepositoryMockRecorder) Update(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockShopKYCDocumentRepository)(nil).Update), ctx, doc)
}

// WithTX mocks base method.
func (m *MockShopKYCDocumentRepository) WithTX(tx repository.Tx) repository.ShopKYCDocumentRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTX", tx)
	ret0, _ := ret[0].(repository.ShopKYCDocumentRepository)
	return ret0
}

// WithTX indicates an expected call of WithTX.
func (mr *MockShopKYCDocumentRepositoryMockRecorder) WithTX(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTX", reflect.TypeOf((*MockShopKYCDocumentRepository)(nil).WithTX), tx)
}
