// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: CreditApplicationRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_credit_application_repository.go -package=repository . CreditApplicationRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreditApplicationRepository is a mock of CreditApplicationRepository interface.
type MockCreditApplicationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCreditApplicationRepositoryMockRecorder
	isgomock struct{}
}

// MockCreditApplicationRepositoryMockRecorder is the mock recorder for MockCreditApplicationRepository.
type MockCreditApplicationRepositoryMockRecorder struct {
	mock *MockCreditApplicationRepository
}

// NewMockCreditApplicationRepository creates a new mock instance.
func NewMockCreditApplicationRepository(ctrl *gomock.Controller) *MockCreditApplicationRepository {
	mock := &MockCreditApplicationRepository{ctrl: ctrl}
	mock.recorder = &MockCreditApplicationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreditApplicationRepository) EXPECT() *MockCreditApplicationRepositoryMockRecorder {
	return m.recorder
}

// CountByCustomerAndStatus mocks base method.
func (m *MockCreditApplicationRepository) CountByCustomerAndStatus(ctx context.Context, customerID string, status entity.CreditApplicationStatus) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByCustomerAndStatus", ctx, customerID, status)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByCustomerAndStatus indicates an expected call of CountByCustomerAndStatus.
func (mr *MockCreditApplicationRepositoryMockRecorder) CountByCustomerAndStatus(ctx, customerID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByCustomerAndStatus", reflect.TypeOf((*MockCreditApplicationRepository)(nil).CountByCustomerAndStatus), ctx, customerID, status)
}

// Create mocks base method.
func (m *MockCreditApplicationRepository) Create(ctx context.Context, app *entity.CreditApplication) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, app)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCreditApplicationRepositoryMockRecorder) Create(ctx, app any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCreditApplicationRepository)(nil).Create), ctx, app)
}

// FindByCustomerAndProduct mocks base method.
func (m *MockCreditApplicationRepository) FindByCustomerAndProduct(ctx context.Context, customerID, productID string) (*entity.CreditApplication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCustomerAndProduct", ctx, customerID, productID)
	ret0, _ := ret[0].(*entity.CreditApplication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCustomerAndProduct indicates an expected call of FindByCustomerAndProduct.
func (mr *MockCreditApplicationRepositoryMockRecorder) FindByCustomerAndProduct(ctx, customerID, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCustomerAndProduct", reflect.TypeOf((*MockCreditApplicationRepository)(nil).FindByCustomerAndProduct), ctx, customerID, productID)
}

// FindByCustomerID mocks base method.
func (m *MockCreditApplicationRepository) FindByCustomerID(ctx context.Context, customerID string) ([]*entity.CreditApplication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCustomerID", ctx, customerID)
	ret0, _ := ret[0].([]*entity.CreditApplication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCustomerID indicates an expected call of FindByCustomerID.
func (mr *MockCreditApplicationRepositoryMockRecorder) FindByCustomerID(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCustomerID", reflect.TypeOf((*MockCreditApplicationRepository)(nil).FindByCustomerID), ctx, customerID)
}

// FindByID mocks base method.
func (m *MockCreditApplicationRepository) FindByID(ctx context.Context, id string) (*entity.CreditApplication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.CreditApplication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCreditApplicationRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCreditApplicationRepository)(nil).FindByID), ctx, id)
}

// FindPendingByShopID mocks base method.
func (m *MockCreditApplicationRepository) FindPendingByShopID(ctx context.Context, shopID string) ([]*entity.CreditApplication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPendingByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.CreditApplication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPendingByShopID indicates an expected call of FindPendingByShopID.
func (mr *MockCreditApplicationRepositoryMockRecorder) FindPendingByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPendingByShopID", reflect.TypeOf((*MockCreditApplicationRepository)(nil).FindPendingByShopID), ctx, shopID)
}

// Update mocks base method.
func (m *MockCreditApplicationRepository) Update(ctx context.Context, app *entity.CreditApplication) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, app)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCreditApplicationRepositoryMockRecorder) Update(ctx, app any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCreditApplicationRepository)(nil).Update), ctx, app)
}

// WithTX mocks base method.
func (m *MockCreditApplicationRepository) WithTX(tx repository.Tx) repository.CreditApplicationRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTX", tx)
	ret0, _ := ret[0].(repository.CreditApplicationRepository)
	return ret0
}

// WithTX indicates an expected call of WithTX.
func (mr *MockCreditApplicationRepositoryMockRecorder) WithTX(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTX", reflect.TypeOf((*MockCreditApplicationRepository)(nil).WithTX), tx)
}
