// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: CreditInstallmentRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_credit_installment_repository.go -package=repository . CreditInstallmentRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreditInstallmentRepository is a mock of CreditInstallmentRepository interface.
type MockCreditInstallmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCreditInstallmentRepositoryMockRecorder
	isgomock struct{}
}

// MockCreditInstallmentRepositoryMockRecorder is the mock recorder for MockCreditInstallmentRepository.
type MockCreditInstallmentRepositoryMockRecorder struct {
	mock *MockCreditInstallmentRepository
}

// NewMockCreditInstallmentRepository creates a new mock instance.
func NewMockCreditInstallmentRepository(ctrl *gomock.Controller) *MockCreditInstallmentRepository {
	mock := &MockCreditInstallmentRepository{ctrl: ctrl}
	mock.recorder = &MockCreditInstallmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreditInstallmentRepository) EXPECT() *MockCreditInstallmentRepositoryMockRecorder {
	return m.recorder
}

// CountPendingByContractID mocks base method.
func (m *MockCreditInstallmentRepository) CountPendingByContractID(ctx context.Context, contractID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPendingByContractID", ctx, contractID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPendingByContractID indicates an expected call of CountPendingByContractID.
func (mr *MockCreditInstallmentRepositoryMockRecorder) CountPendingByContractID(ctx, contractID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPendingByContractID", reflect.TypeOf((*MockCreditInstallmentRepository)(nil).CountPendingByContractID), ctx, contractID)
}

// Create mocks base method.
func (m *MockCreditInstallmentRepository) Create(ctx context.Context, installment *entity.CreditInstallment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, installment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCreditInstallmentRepositoryMockRecorder) Create(ctx, installment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCreditInstallmentRepository)(nil).Create), ctx, installment)
}

// CreateBatch mocks base method.
func (m *MockCreditInstallmentRepository) CreateBatch(ctx context.Context, installments []*entity.CreditInstallment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, installments)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockCreditInstallmentRepositoryMockRecorder) CreateBatch(ctx, installments any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockCreditInstallmentRepository)(nil).CreateBatch), ctx, installments)
}

// FindByContractID mocks base method.
func (m *MockCreditInstallmentRepository) FindByContractID(ctx context.Context, contractID string) ([]*entity.CreditInstallment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByContractID", ctx, contractID)
	ret0, _ := ret[0].([]*entity.CreditInstallment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByContractID indicates an expected call of FindByContractID.
func (mr *MockCreditInstallmentRepositoryMockRecorder) FindByContractID(ctx, contractID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByContractID", reflect.TypeOf((*MockCreditInstallmentRepository)(nil).FindByContractID), ctx, contractID)
}

// FindByContractIDAndNumber mocks base method.
func (m *MockCreditInstallmentRepository) FindByContractIDAndNumber(ctx context.Context, contractID string, number int) (*entity.CreditInstallment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByContractIDAndNumber", ctx, contractID, number)
	ret0, _ := ret[0].(*entity.CreditInstallment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByContractIDAndNumber indicates an expected call of FindByContractIDAndNumber.
func (mr *MockCreditInstallmentRepositoryMockRecorder) FindByContractIDAndNumber(ctx, contractID, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByContractIDAndNumber", reflect.TypeOf((*MockCreditInstallmentRepository)(nil).FindByContractIDAndNumber), ctx, contractID, number)
}

// FindByID mocks base method.
func (m *MockCreditInstallmentRepository) FindByID(ctx context.Context, id string) (*entity.CreditInstallment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.CreditInstallment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCreditInstallmentRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCreditInstallmentRepository)(nil).FindByID), ctx, id)
}

// FindDueInstallments mocks base method.
func (m *MockCreditInstallmentRepository) FindDueInstallments(ctx context.Context, limit int) ([]*entity.CreditInstallment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDueInstallments", ctx, limit)
	ret0, _ := ret[0].([]*entity.CreditInstallment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDueInstallments indicates an expected call of FindDueInstallments.
func (mr *MockCreditInstallmentRepositoryMockRecorder) FindDueInstallments(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDueInstallments", reflect.TypeOf((*MockCreditInstallmentRepository)(nil).FindDueInstallments), ctx, limit)
}

// FindOverdue mocks base method.
func (m *MockCreditInstallmentRepository) FindOverdue(ctx context.Context) ([]*entity.CreditInstallment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOverdue", ctx)
	ret0, _ := ret[0].([]*entity.CreditInstallment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOverdue indicates an expected call of FindOverdue.
func (mr *MockCreditInstallmentRepositoryMockRecorder) FindOverdue(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOverdue", reflect.TypeOf((*MockCreditInstallmentRepository)(nil).FindOverdue), ctx)
}

// FindOverdueByContractID mocks base method.
func (m *MockCreditInstallmentRepository) FindOverdueByContractID(ctx context.Context, contractID string) ([]*entity.CreditInstallment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOverdueByContractID", ctx, contractID)
	ret0, _ := ret[0].([]*entity.CreditInstallment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOverdueByContractID indicates an expected call of FindOverdueByContractID.
func (mr *MockCreditInstallmentRepositoryMockRecorder) FindOverdueByContractID(ctx, contractID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOverdueByContractID", reflect.TypeOf((*MockCreditInstallmentRepository)(nil).FindOverdueByContractID), ctx, contractID)
}

// FindPaidWithoutCommission mocks base method.
func (m *MockCreditInstallmentRepository) FindPaidWithoutCommission(ctx context.Context, limit int) ([]*entity.CreditInstallment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPaidWithoutCommission", ctx, limit)
	ret0, _ := ret[0].([]*entity.CreditInstallment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPaidWithoutCommission indicates an expected call of FindPaidWithoutCommission.
func (mr *MockCreditInstallmentRepositoryMockRecorder) FindPaidWithoutCommission(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPaidWithoutCommission", reflect.TypeOf((*MockCreditInstallmentRepository)(nil).FindPaidWithoutCommission), ctx, limit)
}

// FindPendingByContractID mocks base method.
func (m *MockCreditInstallmentRepository) FindPendingByContractID(ctx context.Context, contractID string) ([]*entity.CreditInstallment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPendingByContractID", ctx, contractID)
	ret0, _ := ret[0].([]*entity.CreditInstallment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPendingByContractID indicates an expected call of FindPendingByContractID.
func (mr *MockCreditInstallmentRepositoryMockRecorder) FindPendingByContractID(ctx, contractID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPendingByContractID", reflect.TypeOf((*MockCreditInstallmentRepository)(nil).FindPendingByContractID), ctx, contractID)
}

// SumPendingAmountByContractID mocks base method.
func (m *MockCreditInstallmentRepository) SumPendingAmountByContractID(ctx context.Context, contractID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumPendingAmountByContractID", ctx, contractID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumPendingAmountByContractID indicates an expected call of SumPendingAmountByContractID.
func (mr *MockCreditInstallmentRepositoryMockRecorder) SumPendingAmountByContractID(ctx, contractID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumPendingAmountByContractID", reflect.TypeOf((*MockCreditInstallmentRepository)(nil).SumPendingAmountByContractID), ctx, contractID)
}

// Update mocks base method.
func (m *MockCreditInstallmentRepository) Update(ctx context.Context, installment *entity.CreditInstallment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, installment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCreditInstallmentRepositoryMockRecorder) Update(ctx, installment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCreditInstallmentRepository)(nil).Update), ctx, installment)
}

// UpdateCreditCommissionStatus mocks base method.
func (m *MockCreditInstallmentRepository) UpdateCreditCommissionStatus(ctx context.Context, installmentID, status string, commissionCents int64, batchID *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCreditCommissionStatus", ctx, installmentID, status, commissionCents, batchID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCreditCommissionStatus indicates an expected call of UpdateCreditCommissionStatus.
func (mr *MockCreditInstallmentRepositoryMockRecorder) UpdateCreditCommissionStatus(ctx, installmentID, status, commissionCents, batchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCreditCommissionStatus", reflect.TypeOf((*MockCreditInstallmentRepository)(nil).UpdateCreditCommissionStatus), ctx, installmentID, status, commissionCents, batchID)
}

// WithTX mocks base method.
func (m *MockCreditInstallmentRepository) WithTX(tx repository.Tx) repository.CreditInstallmentRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTX", tx)
	ret0, _ := ret[0].(repository.CreditInstallmentRepository)
	return ret0
}

// WithTX indicates an expected call of WithTX.
func (mr *MockCreditInstallmentRepositoryMockRecorder) WithTX(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTX", reflect.TypeOf((*MockCreditInstallmentRepository)(nil).WithTX), tx)
}
