// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: ShopRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_shop_repository.go -package=repository . ShopRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockShopRepository is a mock of ShopRepository interface.
type MockShopRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShopRepositoryMockRecorder
	isgomock struct{}
}

// MockShopRepositoryMockRecorder is the mock recorder for MockShopRepository.
type MockShopRepositoryMockRecorder struct {
	mock *MockShopRepository
}

// NewMockShopRepository creates a new mock instance.
func NewMockShopRepository(ctrl *gomock.Controller) *MockShopRepository {
	mock := &MockShopRepository{ctrl: ctrl}
	mock.recorder = &MockShopRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShopRepository) EXPECT() *MockShopRepositoryMockRecorder {
	return m.recorder
}

// ActivateShop mocks base method.
func (m *MockShopRepository) ActivateShop(ctx context.Context, shopID uuid.UUID, adminID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateShop", ctx, shopID, adminID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateShop indicates an expected call of ActivateShop.
func (mr *MockShopRepositoryMockRecorder) ActivateShop(ctx, shopID, adminID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateShop", reflect.TypeOf((*MockShopRepository)(nil).ActivateShop), ctx, shopID, adminID)
}

// AddAdminNote mocks base method.
func (m *MockShopRepository) AddAdminNote(ctx context.Context, shopID uuid.UUID, note, adminID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAdminNote", ctx, shopID, note, adminID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAdminNote indicates an expected call of AddAdminNote.
func (mr *MockShopRepositoryMockRecorder) AddAdminNote(ctx, shopID, note, adminID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAdminNote", reflect.TypeOf((*MockShopRepository)(nil).AddAdminNote), ctx, shopID, note, adminID)
}

// CountByKYCStatus mocks base method.
func (m *MockShopRepository) CountByKYCStatus(ctx context.Context) (map[entity.ShopKYCStatus]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByKYCStatus", ctx)
	ret0, _ := ret[0].(map[entity.ShopKYCStatus]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByKYCStatus indicates an expected call of CountByKYCStatus.
func (mr *MockShopRepositoryMockRecorder) CountByKYCStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByKYCStatus", reflect.TypeOf((*MockShopRepository)(nil).CountByKYCStatus), ctx)
}

// Create mocks base method.
func (m *MockShopRepository) Create(ctx context.Context, shop *entity.Shop) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, shop)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockShopRepositoryMockRecorder) Create(ctx, shop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShopRepository)(nil).Create), ctx, shop)
}

// Deactivate mocks base method.
func (m *MockShopRepository) Deactivate(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deactivate", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deactivate indicates an expected call of Deactivate.
func (mr *MockShopRepositoryMockRecorder) Deactivate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deactivate", reflect.TypeOf((*MockShopRepository)(nil).Deactivate), ctx, id)
}

// FindAllShopsAdmin mocks base method.
func (m *MockShopRepository) FindAllShopsAdmin(ctx context.Context, filters *repository.ShopAdminFilters) ([]*entity.Shop, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllShopsAdmin", ctx, filters)
	ret0, _ := ret[0].([]*entity.Shop)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAllShopsAdmin indicates an expected call of FindAllShopsAdmin.
func (mr *MockShopRepositoryMockRecorder) FindAllShopsAdmin(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllShopsAdmin", reflect.TypeOf((*MockShopRepository)(nil).FindAllShopsAdmin), ctx, filters)
}

// FindByCustomDomain mocks base method.
func (m *MockShopRepository) FindByCustomDomain(ctx context.Context, domain string) (*entity.Shop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCustomDomain", ctx, domain)
	ret0, _ := ret[0].(*entity.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCustomDomain indicates an expected call of FindByCustomDomain.
func (mr *MockShopRepositoryMockRecorder) FindByCustomDomain(ctx, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCustomDomain", reflect.TypeOf((*MockShopRepository)(nil).FindByCustomDomain), ctx, domain)
}

// FindByID mocks base method.
func (m *MockShopRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.Shop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockShopRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockShopRepository)(nil).FindByID), ctx, id)
}

// FindByKYCStatus mocks base method.
func (m *MockShopRepository) FindByKYCStatus(ctx context.Context, status entity.ShopKYCStatus, limit, offset int) ([]*entity.Shop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByKYCStatus", ctx, status, limit, offset)
	ret0, _ := ret[0].([]*entity.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByKYCStatus indicates an expected call of FindByKYCStatus.
func (mr *MockShopRepositoryMockRecorder) FindByKYCStatus(ctx, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByKYCStatus", reflect.TypeOf((*MockShopRepository)(nil).FindByKYCStatus), ctx, status, limit, offset)
}

// FindByOwnerID mocks base method.
func (m *MockShopRepository) FindByOwnerID(ctx context.Context, ownerID string) ([]*entity.Shop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOwnerID", ctx, ownerID)
	ret0, _ := ret[0].([]*entity.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOwnerID indicates an expected call of FindByOwnerID.
func (mr *MockShopRepositoryMockRecorder) FindByOwnerID(ctx, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOwnerID", reflect.TypeOf((*MockShopRepository)(nil).FindByOwnerID), ctx, ownerID)
}

// FindBySlug mocks base method.
func (m *MockShopRepository) FindBySlug(ctx context.Context, slug string) (*entity.Shop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySlug", ctx, slug)
	ret0, _ := ret[0].(*entity.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySlug indicates an expected call of FindBySlug.
func (mr *MockShopRepositoryMockRecorder) FindBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySlug", reflect.TypeOf((*MockShopRepository)(nil).FindBySlug), ctx, slug)
}

// GetCriticalShops mocks base method.
func (m *MockShopRepository) GetCriticalShops(ctx context.Context, limit, offset int) ([]*entity.Shop, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCriticalShops", ctx, limit, offset)
	ret0, _ := ret[0].([]*entity.Shop)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCriticalShops indicates an expected call of GetCriticalShops.
func (mr *MockShopRepositoryMockRecorder) GetCriticalShops(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCriticalShops", reflect.TypeOf((*MockShopRepository)(nil).GetCriticalShops), ctx, limit, offset)
}

// GetHealthStats mocks base method.
func (m *MockShopRepository) GetHealthStats(ctx context.Context) (*repository.ShopHealthStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHealthStats", ctx)
	ret0, _ := ret[0].(*repository.ShopHealthStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHealthStats indicates an expected call of GetHealthStats.
func (mr *MockShopRepositoryMockRecorder) GetHealthStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHealthStats", reflect.TypeOf((*MockShopRepository)(nil).GetHealthStats), ctx)
}

// GetPaymentSettings mocks base method.
func (m *MockShopRepository) GetPaymentSettings(ctx context.Context, shopID uuid.UUID) (*entity.ShopPaymentSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentSettings", ctx, shopID)
	ret0, _ := ret[0].(*entity.ShopPaymentSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentSettings indicates an expected call of GetPaymentSettings.
func (mr *MockShopRepositoryMockRecorder) GetPaymentSettings(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentSettings", reflect.TypeOf((*MockShopRepository)(nil).GetPaymentSettings), ctx, shopID)
}

// GetShopsByHealthLevel mocks base method.
func (m *MockShopRepository) GetShopsByHealthLevel(ctx context.Context, level entity.ShopHealthLevel, limit, offset int) ([]*entity.Shop, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShopsByHealthLevel", ctx, level, limit, offset)
	ret0, _ := ret[0].([]*entity.Shop)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetShopsByHealthLevel indicates an expected call of GetShopsByHealthLevel.
func (mr *MockShopRepositoryMockRecorder) GetShopsByHealthLevel(ctx, level, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShopsByHealthLevel", reflect.TypeOf((*MockShopRepository)(nil).GetShopsByHealthLevel), ctx, level, limit, offset)
}

// GetSuspendedShops mocks base method.
func (m *MockShopRepository) GetSuspendedShops(ctx context.Context, limit, offset int) ([]*entity.Shop, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuspendedShops", ctx, limit, offset)
	ret0, _ := ret[0].([]*entity.Shop)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSuspendedShops indicates an expected call of GetSuspendedShops.
func (mr *MockShopRepositoryMockRecorder) GetSuspendedShops(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuspendedShops", reflect.TypeOf((*MockShopRepository)(nil).GetSuspendedShops), ctx, limit, offset)
}

// IsOwner mocks base method.
func (m *MockShopRepository) IsOwner(ctx context.Context, shopID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOwner", ctx, shopID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsOwner indicates an expected call of IsOwner.
func (mr *MockShopRepositoryMockRecorder) IsOwner(ctx, shopID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOwner", reflect.TypeOf((*MockShopRepository)(nil).IsOwner), ctx, shopID, userID)
}

// MarkShopReviewed mocks base method.
func (m *MockShopRepository) MarkShopReviewed(ctx context.Context, shopID uuid.UUID, adminID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkShopReviewed", ctx, shopID, adminID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkShopReviewed indicates an expected call of MarkShopReviewed.
func (mr *MockShopRepositoryMockRecorder) MarkShopReviewed(ctx, shopID, adminID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkShopReviewed", reflect.TypeOf((*MockShopRepository)(nil).MarkShopReviewed), ctx, shopID, adminID)
}

// SearchShopsAdmin mocks base method.
func (m *MockShopRepository) SearchShopsAdmin(ctx context.Context, query string, limit, offset int) ([]*entity.Shop, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchShopsAdmin", ctx, query, limit, offset)
	ret0, _ := ret[0].([]*entity.Shop)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchShopsAdmin indicates an expected call of SearchShopsAdmin.
func (mr *MockShopRepositoryMockRecorder) SearchShopsAdmin(ctx, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchShopsAdmin", reflect.TypeOf((*MockShopRepository)(nil).SearchShopsAdmin), ctx, query, limit, offset)
}

// SuspendShop mocks base method.
func (m *MockShopRepository) SuspendShop(ctx context.Context, shopID uuid.UUID, adminID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuspendShop", ctx, shopID, adminID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// SuspendShop indicates an expected call of SuspendShop.
func (mr *MockShopRepositoryMockRecorder) SuspendShop(ctx, shopID, adminID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuspendShop", reflect.TypeOf((*MockShopRepository)(nil).SuspendShop), ctx, shopID, adminID, reason)
}

// Update mocks base method.
func (m *MockShopRepository) Update(ctx context.Context, shop *entity.Shop) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, shop)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockShopRepositoryMockRecorder) Update(ctx, shop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockShopRepository)(nil).Update), ctx, shop)
}

// UpdateHealthScore mocks base method.
func (m *MockShopRepository) UpdateHealthScore(ctx context.Context, shopID uuid.UUID, score int, level entity.ShopHealthLevel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHealthScore", ctx, shopID, score, level)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHealthScore indicates an expected call of UpdateHealthScore.
func (mr *MockShopRepositoryMockRecorder) UpdateHealthScore(ctx, shopID, score, level any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHealthScore", reflect.TypeOf((*MockShopRepository)(nil).UpdateHealthScore), ctx, shopID, score, level)
}

// UpdateKYCStatus mocks base method.
func (m *MockShopRepository) UpdateKYCStatus(ctx context.Context, shopID uuid.UUID, status entity.ShopKYCStatus, adminID string, rejectionReason *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKYCStatus", ctx, shopID, status, adminID, rejectionReason)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateKYCStatus indicates an expected call of UpdateKYCStatus.
func (mr *MockShopRepositoryMockRecorder) UpdateKYCStatus(ctx, shopID, status, adminID, rejectionReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKYCStatus", reflect.TypeOf((*MockShopRepository)(nil).UpdateKYCStatus), ctx, shopID, status, adminID, rejectionReason)
}

// UpdateShopPlan mocks base method.
func (m *MockShopRepository) UpdateShopPlan(ctx context.Context, shopID uuid.UUID, plan entity.ShopPlan, adminID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShopPlan", ctx, shopID, plan, adminID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateShopPlan indicates an expected call of UpdateShopPlan.
func (mr *MockShopRepositoryMockRecorder) UpdateShopPlan(ctx, shopID, plan, adminID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShopPlan", reflect.TypeOf((*MockShopRepository)(nil).UpdateShopPlan), ctx, shopID, plan, adminID)
}

// UpdateShopStatus mocks base method.
func (m *MockShopRepository) UpdateShopStatus(ctx context.Context, shopID uuid.UUID, isActive bool, adminID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShopStatus", ctx, shopID, isActive, adminID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateShopStatus indicates an expected call of UpdateShopStatus.
func (mr *MockShopRepositoryMockRecorder) UpdateShopStatus(ctx, shopID, isActive, adminID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShopStatus", reflect.TypeOf((*MockShopRepository)(nil).UpdateShopStatus), ctx, shopID, isActive, adminID)
}

// UpsertPaymentSettings mocks base method.
func (m *MockShopRepository) UpsertPaymentSettings(ctx context.Context, settings *entity.ShopPaymentSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPaymentSettings", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertPaymentSettings indicates an expected call of UpsertPaymentSettings.
func (mr *MockShopRepositoryMockRecorder) UpsertPaymentSettings(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPaymentSettings", reflect.TypeOf((*MockShopRepository)(nil).UpsertPaymentSettings), ctx, settings)
}

// WithTX mocks base method.
func (m *MockShopRepository) WithTX(tx repository.Tx) repository.ShopRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTX", tx)
	ret0, _ := ret[0].(repository.ShopRepository)
	return ret0
}

// WithTX indicates an expected call of WithTX.
func (mr *MockShopRepositoryMockRecorder) WithTX(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTX", reflect.TypeOf((*MockShopRepository)(nil).WithTX), tx)
}
