// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: APIKeyRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_api_key_repository.go -package=repository . APIKeyRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockAPIKeyRepository is a mock of APIKeyRepository interface.
type MockAPIKeyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAPIKeyRepositoryMockRecorder
	isgomock struct{}
}

// MockAPIKeyRepositoryMockRecorder is the mock recorder for MockAPIKeyRepository.
type MockAPIKeyRepositoryMockRecorder struct {
	mock *MockAPIKeyRepository
}

// NewMockAPIKeyRepository creates a new mock instance.
func NewMockAPIKeyRepository(ctrl *gomock.Controller) *MockAPIKeyRepository {
	mock := &MockAPIKeyRepository{ctrl: ctrl}
	mock.recorder = &MockAPIKeyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIKeyRepository) EXPECT() *MockAPIKeyRepositoryMockRecorder {
	return m.recorder
}

// CheckScope mocks base method.
func (m *MockAPIKeyRepository) CheckScope(ctx context.Context, keyHash string, scope entity.APIKeyScope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckScope", ctx, keyHash, scope)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckScope indicates an expected call of CheckScope.
func (mr *MockAPIKeyRepositoryMockRecorder) CheckScope(ctx, keyHash, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckScope", reflect.TypeOf((*MockAPIKeyRepository)(nil).CheckScope), ctx, keyHash, scope)
}

// CleanupAllInactive mocks base method.
func (m *MockAPIKeyRepository) CleanupAllInactive(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupAllInactive", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupAllInactive indicates an expected call of CleanupAllInactive.
func (mr *MockAPIKeyRepositoryMockRecorder) CleanupAllInactive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupAllInactive", reflect.TypeOf((*MockAPIKeyRepository)(nil).CleanupAllInactive), ctx)
}

// CleanupExpiredKeys mocks base method.
func (m *MockAPIKeyRepository) CleanupExpiredKeys(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpiredKeys", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupExpiredKeys indicates an expected call of CleanupExpiredKeys.
func (mr *MockAPIKeyRepositoryMockRecorder) CleanupExpiredKeys(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredKeys", reflect.TypeOf((*MockAPIKeyRepository)(nil).CleanupExpiredKeys), ctx)
}

// CleanupOldUsageLogs mocks base method.
func (m *MockAPIKeyRepository) CleanupOldUsageLogs(ctx context.Context, retentionDays int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupOldUsageLogs", ctx, retentionDays)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupOldUsageLogs indicates an expected call of CleanupOldUsageLogs.
func (mr *MockAPIKeyRepositoryMockRecorder) CleanupOldUsageLogs(ctx, retentionDays any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupOldUsageLogs", reflect.TypeOf((*MockAPIKeyRepository)(nil).CleanupOldUsageLogs), ctx, retentionDays)
}

// CountActiveByUserID mocks base method.
func (m *MockAPIKeyRepository) CountActiveByUserID(ctx context.Context, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveByUserID", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveByUserID indicates an expected call of CountActiveByUserID.
func (mr *MockAPIKeyRepositoryMockRecorder) CountActiveByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveByUserID", reflect.TypeOf((*MockAPIKeyRepository)(nil).CountActiveByUserID), ctx, userID)
}

// CountByUserID mocks base method.
func (m *MockAPIKeyRepository) CountByUserID(ctx context.Context, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserID", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserID indicates an expected call of CountByUserID.
func (mr *MockAPIKeyRepositoryMockRecorder) CountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserID", reflect.TypeOf((*MockAPIKeyRepository)(nil).CountByUserID), ctx, userID)
}

// CountUsageLast7Days mocks base method.
func (m *MockAPIKeyRepository) CountUsageLast7Days(ctx context.Context, apiKeyID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsageLast7Days", ctx, apiKeyID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsageLast7Days indicates an expected call of CountUsageLast7Days.
func (mr *MockAPIKeyRepositoryMockRecorder) CountUsageLast7Days(ctx, apiKeyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsageLast7Days", reflect.TypeOf((*MockAPIKeyRepository)(nil).CountUsageLast7Days), ctx, apiKeyID)
}

// CountUsageToday mocks base method.
func (m *MockAPIKeyRepository) CountUsageToday(ctx context.Context, apiKeyID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsageToday", ctx, apiKeyID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsageToday indicates an expected call of CountUsageToday.
func (mr *MockAPIKeyRepositoryMockRecorder) CountUsageToday(ctx, apiKeyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsageToday", reflect.TypeOf((*MockAPIKeyRepository)(nil).CountUsageToday), ctx, apiKeyID)
}

// Create mocks base method.
func (m *MockAPIKeyRepository) Create(ctx context.Context, apiKey *entity.APIKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, apiKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAPIKeyRepositoryMockRecorder) Create(ctx, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAPIKeyRepository)(nil).Create), ctx, apiKey)
}

// Delete mocks base method.
func (m *MockAPIKeyRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAPIKeyRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAPIKeyRepository)(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockAPIKeyRepository) Exists(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockAPIKeyRepositoryMockRecorder) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockAPIKeyRepository)(nil).Exists), ctx, id)
}

// ExtendExpiration mocks base method.
func (m *MockAPIKeyRepository) ExtendExpiration(ctx context.Context, id string, duration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtendExpiration", ctx, id, duration)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExtendExpiration indicates an expected call of ExtendExpiration.
func (mr *MockAPIKeyRepositoryMockRecorder) ExtendExpiration(ctx, id, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtendExpiration", reflect.TypeOf((*MockAPIKeyRepository)(nil).ExtendExpiration), ctx, id, duration)
}

// FindActiveByUserID mocks base method.
func (m *MockAPIKeyRepository) FindActiveByUserID(ctx context.Context, userID string) ([]*entity.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByUserID", ctx, userID)
	ret0, _ := ret[0].([]*entity.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByUserID indicates an expected call of FindActiveByUserID.
func (mr *MockAPIKeyRepositoryMockRecorder) FindActiveByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByUserID", reflect.TypeOf((*MockAPIKeyRepository)(nil).FindActiveByUserID), ctx, userID)
}

// FindByHash mocks base method.
func (m *MockAPIKeyRepository) FindByHash(ctx context.Context, keyHash string) (*entity.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHash", ctx, keyHash)
	ret0, _ := ret[0].(*entity.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHash indicates an expected call of FindByHash.
func (mr *MockAPIKeyRepositoryMockRecorder) FindByHash(ctx, keyHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHash", reflect.TypeOf((*MockAPIKeyRepository)(nil).FindByHash), ctx, keyHash)
}

// FindByID mocks base method.
func (m *MockAPIKeyRepository) FindByID(ctx context.Context, id string) (*entity.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAPIKeyRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAPIKeyRepository)(nil).FindByID), ctx, id)
}

// FindByUserID mocks base method.
func (m *MockAPIKeyRepository) FindByUserID(ctx context.Context, userID string) ([]*entity.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].([]*entity.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockAPIKeyRepositoryMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockAPIKeyRepository)(nil).FindByUserID), ctx, userID)
}

// FindDuplicateUsers mocks base method.
func (m *MockAPIKeyRepository) FindDuplicateUsers(ctx context.Context, maxKeysPerUser int) ([]*entity.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDuplicateUsers", ctx, maxKeysPerUser)
	ret0, _ := ret[0].([]*entity.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDuplicateUsers indicates an expected call of FindDuplicateUsers.
func (mr *MockAPIKeyRepositoryMockRecorder) FindDuplicateUsers(ctx, maxKeysPerUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDuplicateUsers", reflect.TypeOf((*MockAPIKeyRepository)(nil).FindDuplicateUsers), ctx, maxKeysPerUser)
}

// FindKeysByIP mocks base method.
func (m *MockAPIKeyRepository) FindKeysByIP(ctx context.Context, ipAddress string) ([]*entity.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindKeysByIP", ctx, ipAddress)
	ret0, _ := ret[0].([]*entity.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindKeysByIP indicates an expected call of FindKeysByIP.
func (mr *MockAPIKeyRepositoryMockRecorder) FindKeysByIP(ctx, ipAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindKeysByIP", reflect.TypeOf((*MockAPIKeyRepository)(nil).FindKeysByIP), ctx, ipAddress)
}

// GetExpiringKeys mocks base method.
func (m *MockAPIKeyRepository) GetExpiringKeys(ctx context.Context, withinDays int) ([]*entity.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpiringKeys", ctx, withinDays)
	ret0, _ := ret[0].([]*entity.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExpiringKeys indicates an expected call of GetExpiringKeys.
func (mr *MockAPIKeyRepositoryMockRecorder) GetExpiringKeys(ctx, withinDays any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpiringKeys", reflect.TypeOf((*MockAPIKeyRepository)(nil).GetExpiringKeys), ctx, withinDays)
}

// GetMostUsedKeys mocks base method.
func (m *MockAPIKeyRepository) GetMostUsedKeys(ctx context.Context, limit int) ([]repository.APIKeyUsageCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMostUsedKeys", ctx, limit)
	ret0, _ := ret[0].([]repository.APIKeyUsageCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMostUsedKeys indicates an expected call of GetMostUsedKeys.
func (mr *MockAPIKeyRepositoryMockRecorder) GetMostUsedKeys(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMostUsedKeys", reflect.TypeOf((*MockAPIKeyRepository)(nil).GetMostUsedKeys), ctx, limit)
}

// GetRecentUsageLogs mocks base method.
func (m *MockAPIKeyRepository) GetRecentUsageLogs(ctx context.Context, apiKeyID string) ([]*entity.APIKeyUsageLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentUsageLogs", ctx, apiKeyID)
	ret0, _ := ret[0].([]*entity.APIKeyUsageLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentUsageLogs indicates an expected call of GetRecentUsageLogs.
func (mr *MockAPIKeyRepositoryMockRecorder) GetRecentUsageLogs(ctx, apiKeyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentUsageLogs", reflect.TypeOf((*MockAPIKeyRepository)(nil).GetRecentUsageLogs), ctx, apiKeyID)
}

// GetStatistics mocks base method.
func (m *MockAPIKeyRepository) GetStatistics(ctx context.Context) (*entity.APIKeyStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatistics", ctx)
	ret0, _ := ret[0].(*entity.APIKeyStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatistics indicates an expected call of GetStatistics.
func (mr *MockAPIKeyRepositoryMockRecorder) GetStatistics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatistics", reflect.TypeOf((*MockAPIKeyRepository)(nil).GetStatistics), ctx)
}

// GetStatisticsByUser mocks base method.
func (m *MockAPIKeyRepository) GetStatisticsByUser(ctx context.Context, userID string) (*entity.APIKeyStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatisticsByUser", ctx, userID)
	ret0, _ := ret[0].(*entity.APIKeyStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatisticsByUser indicates an expected call of GetStatisticsByUser.
func (mr *MockAPIKeyRepositoryMockRecorder) GetStatisticsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatisticsByUser", reflect.TypeOf((*MockAPIKeyRepository)(nil).GetStatisticsByUser), ctx, userID)
}

// GetUsageLogs mocks base method.
func (m *MockAPIKeyRepository) GetUsageLogs(ctx context.Context, apiKeyID string, limit int) ([]*entity.APIKeyUsageLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsageLogs", ctx, apiKeyID, limit)
	ret0, _ := ret[0].([]*entity.APIKeyUsageLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsageLogs indicates an expected call of GetUsageLogs.
func (mr *MockAPIKeyRepositoryMockRecorder) GetUsageLogs(ctx, apiKeyID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsageLogs", reflect.TypeOf((*MockAPIKeyRepository)(nil).GetUsageLogs), ctx, apiKeyID, limit)
}

// ListActiveKeys mocks base method.
func (m *MockAPIKeyRepository) ListActiveKeys(ctx context.Context, limit, offset int) ([]*entity.APIKey, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveKeys", ctx, limit, offset)
	ret0, _ := ret[0].([]*entity.APIKey)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListActiveKeys indicates an expected call of ListActiveKeys.
func (mr *MockAPIKeyRepositoryMockRecorder) ListActiveKeys(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveKeys", reflect.TypeOf((*MockAPIKeyRepository)(nil).ListActiveKeys), ctx, limit, offset)
}

// ListActiveKeysByUser mocks base method.
func (m *MockAPIKeyRepository) ListActiveKeysByUser(ctx context.Context, userID string, limit, offset int) ([]*entity.APIKey, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveKeysByUser", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*entity.APIKey)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListActiveKeysByUser indicates an expected call of ListActiveKeysByUser.
func (mr *MockAPIKeyRepositoryMockRecorder) ListActiveKeysByUser(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveKeysByUser", reflect.TypeOf((*MockAPIKeyRepository)(nil).ListActiveKeysByUser), ctx, userID, limit, offset)
}

// LogUsage mocks base method.
func (m *MockAPIKeyRepository) LogUsage(ctx context.Context, log *entity.APIKeyUsageLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogUsage", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogUsage indicates an expected call of LogUsage.
func (mr *MockAPIKeyRepositoryMockRecorder) LogUsage(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogUsage", reflect.TypeOf((*MockAPIKeyRepository)(nil).LogUsage), ctx, log)
}

// MarkKeyUsed mocks base method.
func (m *MockAPIKeyRepository) MarkKeyUsed(ctx context.Context, keyHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkKeyUsed", ctx, keyHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkKeyUsed indicates an expected call of MarkKeyUsed.
func (mr *MockAPIKeyRepositoryMockRecorder) MarkKeyUsed(ctx, keyHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkKeyUsed", reflect.TypeOf((*MockAPIKeyRepository)(nil).MarkKeyUsed), ctx, keyHash)
}

// RevokeAPIKey mocks base method.
func (m *MockAPIKeyRepository) RevokeAPIKey(ctx context.Context, id, revokedBy, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAPIKey", ctx, id, revokedBy, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAPIKey indicates an expected call of RevokeAPIKey.
func (mr *MockAPIKeyRepositoryMockRecorder) RevokeAPIKey(ctx, id, revokedBy, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAPIKey", reflect.TypeOf((*MockAPIKeyRepository)(nil).RevokeAPIKey), ctx, id, revokedBy, reason)
}

// RevokeAllUserAPIKeys mocks base method.
func (m *MockAPIKeyRepository) RevokeAllUserAPIKeys(ctx context.Context, userID, excludeKeyID, revokedBy, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllUserAPIKeys", ctx, userID, excludeKeyID, revokedBy, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllUserAPIKeys indicates an expected call of RevokeAllUserAPIKeys.
func (mr *MockAPIKeyRepositoryMockRecorder) RevokeAllUserAPIKeys(ctx, userID, excludeKeyID, revokedBy, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllUserAPIKeys", reflect.TypeOf((*MockAPIKeyRepository)(nil).RevokeAllUserAPIKeys), ctx, userID, excludeKeyID, revokedBy, reason)
}

// Update mocks base method.
func (m *MockAPIKeyRepository) Update(ctx context.Context, apiKey *entity.APIKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, apiKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAPIKeyRepositoryMockRecorder) Update(ctx, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAPIKeyRepository)(nil).Update), ctx, apiKey)
}

// ValidateKey mocks base method.
func (m *MockAPIKeyRepository) ValidateKey(ctx context.Context, keyHash string) (*entity.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateKey", ctx, keyHash)
	ret0, _ := ret[0].(*entity.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateKey indicates an expected call of ValidateKey.
func (mr *MockAPIKeyRepositoryMockRecorder) ValidateKey(ctx, keyHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateKey", reflect.TypeOf((*MockAPIKeyRepository)(nil).ValidateKey), ctx, keyHash)
}
