// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: UserSessionRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_user_session_repository.go -package=repository . UserSessionRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockUserSessionRepository is a mock of UserSessionRepository interface.
type MockUserSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockUserSessionRepositoryMockRecorder is the mock recorder for MockUserSessionRepository.
type MockUserSessionRepositoryMockRecorder struct {
	mock *MockUserSessionRepository
}

// NewMockUserSessionRepository creates a new mock instance.
func NewMockUserSessionRepository(ctrl *gomock.Controller) *MockUserSessionRepository {
	mock := &MockUserSessionRepository{ctrl: ctrl}
	mock.recorder = &MockUserSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSessionRepository) EXPECT() *MockUserSessionRepositoryMockRecorder {
	return m.recorder
}

// CleanupAllInactive mocks base method.
func (m *MockUserSessionRepository) CleanupAllInactive(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupAllInactive", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupAllInactive indicates an expected call of CleanupAllInactive.
func (mr *MockUserSessionRepositoryMockRecorder) CleanupAllInactive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupAllInactive", reflect.TypeOf((*MockUserSessionRepository)(nil).CleanupAllInactive), ctx)
}

// CleanupExpiredSessions mocks base method.
func (m *MockUserSessionRepository) CleanupExpiredSessions(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpiredSessions", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupExpiredSessions indicates an expected call of CleanupExpiredSessions.
func (mr *MockUserSessionRepositoryMockRecorder) CleanupExpiredSessions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredSessions", reflect.TypeOf((*MockUserSessionRepository)(nil).CleanupExpiredSessions), ctx)
}

// CleanupOldRevokedSessions mocks base method.
func (m *MockUserSessionRepository) CleanupOldRevokedSessions(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupOldRevokedSessions", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupOldRevokedSessions indicates an expected call of CleanupOldRevokedSessions.
func (mr *MockUserSessionRepositoryMockRecorder) CleanupOldRevokedSessions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupOldRevokedSessions", reflect.TypeOf((*MockUserSessionRepository)(nil).CleanupOldRevokedSessions), ctx)
}

// CountActiveByUserID mocks base method.
func (m *MockUserSessionRepository) CountActiveByUserID(ctx context.Context, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveByUserID", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveByUserID indicates an expected call of CountActiveByUserID.
func (mr *MockUserSessionRepositoryMockRecorder) CountActiveByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveByUserID", reflect.TypeOf((*MockUserSessionRepository)(nil).CountActiveByUserID), ctx, userID)
}

// CountByUserID mocks base method.
func (m *MockUserSessionRepository) CountByUserID(ctx context.Context, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserID", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserID indicates an expected call of CountByUserID.
func (mr *MockUserSessionRepositoryMockRecorder) CountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserID", reflect.TypeOf((*MockUserSessionRepository)(nil).CountByUserID), ctx, userID)
}

// Create mocks base method.
func (m *MockUserSessionRepository) Create(ctx context.Context, session *entity.UserSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserSessionRepositoryMockRecorder) Create(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserSessionRepository)(nil).Create), ctx, session)
}

// Delete mocks base method.
func (m *MockUserSessionRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserSessionRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserSessionRepository)(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockUserSessionRepository) Exists(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockUserSessionRepositoryMockRecorder) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockUserSessionRepository)(nil).Exists), ctx, id)
}

// ExtendSession mocks base method.
func (m *MockUserSessionRepository) ExtendSession(ctx context.Context, sessionID string, duration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtendSession", ctx, sessionID, duration)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExtendSession indicates an expected call of ExtendSession.
func (mr *MockUserSessionRepositoryMockRecorder) ExtendSession(ctx, sessionID, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtendSession", reflect.TypeOf((*MockUserSessionRepository)(nil).ExtendSession), ctx, sessionID, duration)
}

// FindActiveByUserID mocks base method.
func (m *MockUserSessionRepository) FindActiveByUserID(ctx context.Context, userID string) ([]*entity.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByUserID", ctx, userID)
	ret0, _ := ret[0].([]*entity.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByUserID indicates an expected call of FindActiveByUserID.
func (mr *MockUserSessionRepositoryMockRecorder) FindActiveByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByUserID", reflect.TypeOf((*MockUserSessionRepository)(nil).FindActiveByUserID), ctx, userID)
}

// FindByID mocks base method.
func (m *MockUserSessionRepository) FindByID(ctx context.Context, id string) (*entity.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserSessionRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserSessionRepository)(nil).FindByID), ctx, id)
}

// FindBySessionID mocks base method.
func (m *MockUserSessionRepository) FindBySessionID(ctx context.Context, sessionID string) (*entity.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySessionID", ctx, sessionID)
	ret0, _ := ret[0].(*entity.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySessionID indicates an expected call of FindBySessionID.
func (mr *MockUserSessionRepositoryMockRecorder) FindBySessionID(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySessionID", reflect.TypeOf((*MockUserSessionRepository)(nil).FindBySessionID), ctx, sessionID)
}

// FindByUserID mocks base method.
func (m *MockUserSessionRepository) FindByUserID(ctx context.Context, userID string) ([]*entity.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].([]*entity.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockUserSessionRepositoryMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockUserSessionRepository)(nil).FindByUserID), ctx, userID)
}

// FindDuplicateSessions mocks base method.
func (m *MockUserSessionRepository) FindDuplicateSessions(ctx context.Context, maxSessionsPerUser int) ([]*entity.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDuplicateSessions", ctx, maxSessionsPerUser)
	ret0, _ := ret[0].([]*entity.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDuplicateSessions indicates an expected call of FindDuplicateSessions.
func (mr *MockUserSessionRepositoryMockRecorder) FindDuplicateSessions(ctx, maxSessionsPerUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDuplicateSessions", reflect.TypeOf((*MockUserSessionRepository)(nil).FindDuplicateSessions), ctx, maxSessionsPerUser)
}

// FindSessionsByIP mocks base method.
func (m *MockUserSessionRepository) FindSessionsByIP(ctx context.Context, ipAddress string) ([]*entity.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSessionsByIP", ctx, ipAddress)
	ret0, _ := ret[0].([]*entity.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSessionsByIP indicates an expected call of FindSessionsByIP.
func (mr *MockUserSessionRepositoryMockRecorder) FindSessionsByIP(ctx, ipAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSessionsByIP", reflect.TypeOf((*MockUserSessionRepository)(nil).FindSessionsByIP), ctx, ipAddress)
}

// GetMostActiveUsers mocks base method.
func (m *MockUserSessionRepository) GetMostActiveUsers(ctx context.Context, limit int) ([]repository.UserSessionCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMostActiveUsers", ctx, limit)
	ret0, _ := ret[0].([]repository.UserSessionCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMostActiveUsers indicates an expected call of GetMostActiveUsers.
func (mr *MockUserSessionRepositoryMockRecorder) GetMostActiveUsers(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMostActiveUsers", reflect.TypeOf((*MockUserSessionRepository)(nil).GetMostActiveUsers), ctx, limit)
}

// GetStatistics mocks base method.
func (m *MockUserSessionRepository) GetStatistics(ctx context.Context) (*entity.SessionStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatistics", ctx)
	ret0, _ := ret[0].(*entity.SessionStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatistics indicates an expected call of GetStatistics.
func (mr *MockUserSessionRepositoryMockRecorder) GetStatistics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatistics", reflect.TypeOf((*MockUserSessionRepository)(nil).GetStatistics), ctx)
}

// GetStatisticsByUser mocks base method.
func (m *MockUserSessionRepository) GetStatisticsByUser(ctx context.Context, userID string) (*entity.SessionStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatisticsByUser", ctx, userID)
	ret0, _ := ret[0].(*entity.SessionStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatisticsByUser indicates an expected call of GetStatisticsByUser.
func (mr *MockUserSessionRepositoryMockRecorder) GetStatisticsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatisticsByUser", reflect.TypeOf((*MockUserSessionRepository)(nil).GetStatisticsByUser), ctx, userID)
}

// ListActiveSessions mocks base method.
func (m *MockUserSessionRepository) ListActiveSessions(ctx context.Context, limit, offset int) ([]*entity.UserSession, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveSessions", ctx, limit, offset)
	ret0, _ := ret[0].([]*entity.UserSession)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListActiveSessions indicates an expected call of ListActiveSessions.
func (mr *MockUserSessionRepositoryMockRecorder) ListActiveSessions(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveSessions", reflect.TypeOf((*MockUserSessionRepository)(nil).ListActiveSessions), ctx, limit, offset)
}

// ListActiveSessionsByUser mocks base method.
func (m *MockUserSessionRepository) ListActiveSessionsByUser(ctx context.Context, userID string, limit, offset int) ([]*entity.UserSession, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveSessionsByUser", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*entity.UserSession)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListActiveSessionsByUser indicates an expected call of ListActiveSessionsByUser.
func (mr *MockUserSessionRepositoryMockRecorder) ListActiveSessionsByUser(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveSessionsByUser", reflect.TypeOf((*MockUserSessionRepository)(nil).ListActiveSessionsByUser), ctx, userID, limit, offset)
}

// RevokeAllUserSessions mocks base method.
func (m *MockUserSessionRepository) RevokeAllUserSessions(ctx context.Context, userID, excludeSessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllUserSessions", ctx, userID, excludeSessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllUserSessions indicates an expected call of RevokeAllUserSessions.
func (mr *MockUserSessionRepositoryMockRecorder) RevokeAllUserSessions(ctx, userID, excludeSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllUserSessions", reflect.TypeOf((*MockUserSessionRepository)(nil).RevokeAllUserSessions), ctx, userID, excludeSessionID)
}

// RevokeSession mocks base method.
func (m *MockUserSessionRepository) RevokeSession(ctx context.Context, sessionID, revokedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSession", ctx, sessionID, revokedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSession indicates an expected call of RevokeSession.
func (mr *MockUserSessionRepositoryMockRecorder) RevokeSession(ctx, sessionID, revokedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSession", reflect.TypeOf((*MockUserSessionRepository)(nil).RevokeSession), ctx, sessionID, revokedBy)
}

// Update mocks base method.
func (m *MockUserSessionRepository) Update(ctx context.Context, session *entity.UserSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserSessionRepositoryMockRecorder) Update(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserSessionRepository)(nil).Update), ctx, session)
}

// UpdateLastActivity mocks base method.
func (m *MockUserSessionRepository) UpdateLastActivity(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastActivity", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastActivity indicates an expected call of UpdateLastActivity.
func (mr *MockUserSessionRepositoryMockRecorder) UpdateLastActivity(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastActivity", reflect.TypeOf((*MockUserSessionRepository)(nil).UpdateLastActivity), ctx, sessionID)
}

// ValidateToken mocks base method.
func (m *MockUserSessionRepository) ValidateToken(ctx context.Context, sessionID, token string) (*entity.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, sessionID, token)
	ret0, _ := ret[0].(*entity.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockUserSessionRepositoryMockRecorder) ValidateToken(ctx, sessionID, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockUserSessionRepository)(nil).ValidateToken), ctx, sessionID, token)
}
