// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: CustomerKYCRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_customer_kyc_repository.go -package=repository . CustomerKYCRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCustomerKYCRepository is a mock of CustomerKYCRepository interface.
type MockCustomerKYCRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerKYCRepositoryMockRecorder
	isgomock struct{}
}

// MockCustomerKYCRepositoryMockRecorder is the mock recorder for MockCustomerKYCRepository.
type MockCustomerKYCRepositoryMockRecorder struct {
	mock *MockCustomerKYCRepository
}

// NewMockCustomerKYCRepository creates a new mock instance.
func NewMockCustomerKYCRepository(ctrl *gomock.Controller) *MockCustomerKYCRepository {
	mock := &MockCustomerKYCRepository{ctrl: ctrl}
	mock.recorder = &MockCustomerKYCRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerKYCRepository) EXPECT() *MockCustomerKYCRepositoryMockRecorder {
	return m.recorder
}

// CountByCustomer mocks base method.
func (m *MockCustomerKYCRepository) CountByCustomer(ctx context.Context, customerID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByCustomer", ctx, customerID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByCustomer indicates an expected call of CountByCustomer.
func (mr *MockCustomerKYCRepositoryMockRecorder) CountByCustomer(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByCustomer", reflect.TypeOf((*MockCustomerKYCRepository)(nil).CountByCustomer), ctx, customerID)
}

// Create mocks base method.
func (m *MockCustomerKYCRepository) Create(ctx context.Context, doc *entity.CustomerKYCDocument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCustomerKYCRepositoryMockRecorder) Create(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomerKYCRepository)(nil).Create), ctx, doc)
}

// FindByCustomerID mocks base method.
func (m *MockCustomerKYCRepository) FindByCustomerID(ctx context.Context, customerID string) ([]*entity.CustomerKYCDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCustomerID", ctx, customerID)
	ret0, _ := ret[0].([]*entity.CustomerKYCDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCustomerID indicates an expected call of FindByCustomerID.
func (mr *MockCustomerKYCRepositoryMockRecorder) FindByCustomerID(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCustomerID", reflect.TypeOf((*MockCustomerKYCRepository)(nil).FindByCustomerID), ctx, customerID)
}

// FindByID mocks base method.
func (m *MockCustomerKYCRepository) FindByID(ctx context.Context, id string) (*entity.CustomerKYCDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.CustomerKYCDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCustomerKYCRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCustomerKYCRepository)(nil).FindByID), ctx, id)
}

// FindPendingByCustomer mocks base method.
func (m *MockCustomerKYCRepository) FindPendingByCustomer(ctx context.Context, customerID string) ([]*entity.CustomerKYCDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPendingByCustomer", ctx, customerID)
	ret0, _ := ret[0].([]*entity.CustomerKYCDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPendingByCustomer indicates an expected call of FindPendingByCustomer.
func (mr *MockCustomerKYCRepositoryMockRecorder) FindPendingByCustomer(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPendingByCustomer", reflect.TypeOf((*MockCustomerKYCRepository)(nil).FindPendingByCustomer), ctx, customerID)
}

// FindPendingByShop mocks base method.
func (m *MockCustomerKYCRepository) FindPendingByShop(ctx context.Context, shopID string) ([]*entity.CustomerKYCDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPendingByShop", ctx, shopID)
	ret0, _ := ret[0].([]*entity.CustomerKYCDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPendingByShop indicates an expected call of FindPendingByShop.
func (mr *MockCustomerKYCRepositoryMockRecorder) FindPendingByShop(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPendingByShop", reflect.TypeOf((*MockCustomerKYCRepository)(nil).FindPendingByShop), ctx, shopID)
}

// Update mocks base method.
func (m *MockCustomerKYCRepository) Update(ctx context.Context, doc *entity.CustomerKYCDocument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCustomerKYCRepositoryMockRecorder) Update(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomerKYCRepository)(nil).Update), ctx, doc)
}

// WithTX mocks base method.
func (m *MockCustomerKYCRepository) WithTX(tx repository.Tx) repository.CustomerKYCRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTX", tx)
	ret0, _ := ret[0].(repository.CustomerKYCRepository)
	return ret0
}

// WithTX indicates an expected call of WithTX.
func (mr *MockCustomerKYCRepositoryMockRecorder) WithTX(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTX", reflect.TypeOf((*MockCustomerKYCRepository)(nil).WithTX), tx)
}
