// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: MerchantWalletRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_merchant_wallet_repository.go -package=repository . MerchantWalletRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMerchantWalletRepository is a mock of MerchantWalletRepository interface.
type MockMerchantWalletRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMerchantWalletRepositoryMockRecorder
	isgomock struct{}
}

// MockMerchantWalletRepositoryMockRecorder is the mock recorder for MockMerchantWalletRepository.
type MockMerchantWalletRepositoryMockRecorder struct {
	mock *MockMerchantWalletRepository
}

// NewMockMerchantWalletRepository creates a new mock instance.
func NewMockMerchantWalletRepository(ctrl *gomock.Controller) *MockMerchantWalletRepository {
	mock := &MockMerchantWalletRepository{ctrl: ctrl}
	mock.recorder = &MockMerchantWalletRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMerchantWalletRepository) EXPECT() *MockMerchantWalletRepositoryMockRecorder {
	return m.recorder
}

// CountFrozen mocks base method.
func (m *MockMerchantWalletRepository) CountFrozen(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFrozen", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFrozen indicates an expected call of CountFrozen.
func (mr *MockMerchantWalletRepositoryMockRecorder) CountFrozen(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFrozen", reflect.TypeOf((*MockMerchantWalletRepository)(nil).CountFrozen), ctx)
}

// CountNegativeBalance mocks base method.
func (m *MockMerchantWalletRepository) CountNegativeBalance(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountNegativeBalance", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountNegativeBalance indicates an expected call of CountNegativeBalance.
func (mr *MockMerchantWalletRepositoryMockRecorder) CountNegativeBalance(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountNegativeBalance", reflect.TypeOf((*MockMerchantWalletRepository)(nil).CountNegativeBalance), ctx)
}

// Create mocks base method.
func (m *MockMerchantWalletRepository) Create(ctx context.Context, wallet *entity.MerchantWallet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, wallet)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMerchantWalletRepositoryMockRecorder) Create(ctx, wallet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMerchantWalletRepository)(nil).Create), ctx, wallet)
}

// CreateAdmin mocks base method.
func (m *MockMerchantWalletRepository) CreateAdmin(ctx context.Context, wallet *entity.MerchantWallet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdmin", ctx, wallet)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAdmin indicates an expected call of CreateAdmin.
func (mr *MockMerchantWalletRepositoryMockRecorder) CreateAdmin(ctx, wallet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdmin", reflect.TypeOf((*MockMerchantWalletRepository)(nil).CreateAdmin), ctx, wallet)
}

// FindAboveThreshold mocks base method.
func (m *MockMerchantWalletRepository) FindAboveThreshold(ctx context.Context, thresholdCents int64) ([]*entity.MerchantWallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAboveThreshold", ctx, thresholdCents)
	ret0, _ := ret[0].([]*entity.MerchantWallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAboveThreshold indicates an expected call of FindAboveThreshold.
func (mr *MockMerchantWalletRepositoryMockRecorder) FindAboveThreshold(ctx, thresholdCents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAboveThreshold", reflect.TypeOf((*MockMerchantWalletRepository)(nil).FindAboveThreshold), ctx, thresholdCents)
}

// FindAll mocks base method.
func (m *MockMerchantWalletRepository) FindAll(ctx context.Context) ([]*entity.MerchantWallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*entity.MerchantWallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockMerchantWalletRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockMerchantWalletRepository)(nil).FindAll), ctx)
}

// FindBelowThreshold mocks base method.
func (m *MockMerchantWalletRepository) FindBelowThreshold(ctx context.Context, thresholdCents int64) ([]*entity.MerchantWallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBelowThreshold", ctx, thresholdCents)
	ret0, _ := ret[0].([]*entity.MerchantWallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBelowThreshold indicates an expected call of FindBelowThreshold.
func (mr *MockMerchantWalletRepositoryMockRecorder) FindBelowThreshold(ctx, thresholdCents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBelowThreshold", reflect.TypeOf((*MockMerchantWalletRepository)(nil).FindBelowThreshold), ctx, thresholdCents)
}

// FindByShopID mocks base method.
func (m *MockMerchantWalletRepository) FindByShopID(ctx context.Context, shopID string) (*entity.MerchantWallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShopID", ctx, shopID)
	ret0, _ := ret[0].(*entity.MerchantWallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShopID indicates an expected call of FindByShopID.
func (mr *MockMerchantWalletRepositoryMockRecorder) FindByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShopID", reflect.TypeOf((*MockMerchantWalletRepository)(nil).FindByShopID), ctx, shopID)
}

// FindByShopIDForUpdate mocks base method.
func (m *MockMerchantWalletRepository) FindByShopIDForUpdate(ctx context.Context, shopID string) (*entity.MerchantWallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShopIDForUpdate", ctx, shopID)
	ret0, _ := ret[0].(*entity.MerchantWallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShopIDForUpdate indicates an expected call of FindByShopIDForUpdate.
func (mr *MockMerchantWalletRepositoryMockRecorder) FindByShopIDForUpdate(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShopIDForUpdate", reflect.TypeOf((*MockMerchantWalletRepository)(nil).FindByShopIDForUpdate), ctx, shopID)
}

// FindByShopIDForUpdateAdmin mocks base method.
func (m *MockMerchantWalletRepository) FindByShopIDForUpdateAdmin(ctx context.Context, shopID string) (*entity.MerchantWallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShopIDForUpdateAdmin", ctx, shopID)
	ret0, _ := ret[0].(*entity.MerchantWallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShopIDForUpdateAdmin indicates an expected call of FindByShopIDForUpdateAdmin.
func (mr *MockMerchantWalletRepositoryMockRecorder) FindByShopIDForUpdateAdmin(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShopIDForUpdateAdmin", reflect.TypeOf((*MockMerchantWalletRepository)(nil).FindByShopIDForUpdateAdmin), ctx, shopID)
}

// FindFrozen mocks base method.
func (m *MockMerchantWalletRepository) FindFrozen(ctx context.Context) ([]*entity.MerchantWallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFrozen", ctx)
	ret0, _ := ret[0].([]*entity.MerchantWallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFrozen indicates an expected call of FindFrozen.
func (mr *MockMerchantWalletRepositoryMockRecorder) FindFrozen(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFrozen", reflect.TypeOf((*MockMerchantWalletRepository)(nil).FindFrozen), ctx)
}

// FindFrozenByShopID mocks base method.
func (m *MockMerchantWalletRepository) FindFrozenByShopID(ctx context.Context, shopID string) (*entity.MerchantWallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFrozenByShopID", ctx, shopID)
	ret0, _ := ret[0].(*entity.MerchantWallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFrozenByShopID indicates an expected call of FindFrozenByShopID.
func (mr *MockMerchantWalletRepositoryMockRecorder) FindFrozenByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFrozenByShopID", reflect.TypeOf((*MockMerchantWalletRepository)(nil).FindFrozenByShopID), ctx, shopID)
}

// FindGracePeriodExpired mocks base method.
func (m *MockMerchantWalletRepository) FindGracePeriodExpired(ctx context.Context) ([]*entity.MerchantWallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindGracePeriodExpired", ctx)
	ret0, _ := ret[0].([]*entity.MerchantWallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindGracePeriodExpired indicates an expected call of FindGracePeriodExpired.
func (mr *MockMerchantWalletRepositoryMockRecorder) FindGracePeriodExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindGracePeriodExpired", reflect.TypeOf((*MockMerchantWalletRepository)(nil).FindGracePeriodExpired), ctx)
}

// FindGracePeriodExpiringSoon mocks base method.
func (m *MockMerchantWalletRepository) FindGracePeriodExpiringSoon(ctx context.Context, daysRemaining int) ([]*entity.MerchantWallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindGracePeriodExpiringSoon", ctx, daysRemaining)
	ret0, _ := ret[0].([]*entity.MerchantWallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindGracePeriodExpiringSoon indicates an expected call of FindGracePeriodExpiringSoon.
func (mr *MockMerchantWalletRepositoryMockRecorder) FindGracePeriodExpiringSoon(ctx, daysRemaining any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindGracePeriodExpiringSoon", reflect.TypeOf((*MockMerchantWalletRepository)(nil).FindGracePeriodExpiringSoon), ctx, daysRemaining)
}

// FindNegativeBalance mocks base method.
func (m *MockMerchantWalletRepository) FindNegativeBalance(ctx context.Context) ([]*entity.MerchantWallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNegativeBalance", ctx)
	ret0, _ := ret[0].([]*entity.MerchantWallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNegativeBalance indicates an expected call of FindNegativeBalance.
func (mr *MockMerchantWalletRepositoryMockRecorder) FindNegativeBalance(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNegativeBalance", reflect.TypeOf((*MockMerchantWalletRepository)(nil).FindNegativeBalance), ctx)
}

// FindPositiveBalance mocks base method.
func (m *MockMerchantWalletRepository) FindPositiveBalance(ctx context.Context) ([]*entity.MerchantWallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPositiveBalance", ctx)
	ret0, _ := ret[0].([]*entity.MerchantWallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPositiveBalance indicates an expected call of FindPositiveBalance.
func (mr *MockMerchantWalletRepositoryMockRecorder) FindPositiveBalance(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPositiveBalance", reflect.TypeOf((*MockMerchantWalletRepository)(nil).FindPositiveBalance), ctx)
}

// SumFrozenBalance mocks base method.
func (m *MockMerchantWalletRepository) SumFrozenBalance(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumFrozenBalance", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumFrozenBalance indicates an expected call of SumFrozenBalance.
func (mr *MockMerchantWalletRepositoryMockRecorder) SumFrozenBalance(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumFrozenBalance", reflect.TypeOf((*MockMerchantWalletRepository)(nil).SumFrozenBalance), ctx)
}

// SumNegativeBalance mocks base method.
func (m *MockMerchantWalletRepository) SumNegativeBalance(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumNegativeBalance", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumNegativeBalance indicates an expected call of SumNegativeBalance.
func (mr *MockMerchantWalletRepositoryMockRecorder) SumNegativeBalance(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumNegativeBalance", reflect.TypeOf((*MockMerchantWalletRepository)(nil).SumNegativeBalance), ctx)
}

// SumTotalBalance mocks base method.
func (m *MockMerchantWalletRepository) SumTotalBalance(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumTotalBalance", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumTotalBalance indicates an expected call of SumTotalBalance.
func (mr *MockMerchantWalletRepositoryMockRecorder) SumTotalBalance(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumTotalBalance", reflect.TypeOf((*MockMerchantWalletRepository)(nil).SumTotalBalance), ctx)
}

// Update mocks base method.
func (m *MockMerchantWalletRepository) Update(ctx context.Context, wallet *entity.MerchantWallet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, wallet)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMerchantWalletRepositoryMockRecorder) Update(ctx, wallet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMerchantWalletRepository)(nil).Update), ctx, wallet)
}

// UpdateAdmin mocks base method.
func (m *MockMerchantWalletRepository) UpdateAdmin(ctx context.Context, wallet *entity.MerchantWallet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdmin", ctx, wallet)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAdmin indicates an expected call of UpdateAdmin.
func (mr *MockMerchantWalletRepositoryMockRecorder) UpdateAdmin(ctx, wallet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdmin", reflect.TypeOf((*MockMerchantWalletRepository)(nil).UpdateAdmin), ctx, wallet)
}

// WithTX mocks base method.
func (m *MockMerchantWalletRepository) WithTX(tx repository.Tx) repository.MerchantWalletRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTX", tx)
	ret0, _ := ret[0].(repository.MerchantWalletRepository)
	return ret0
}

// WithTX indicates an expected call of WithTX.
func (mr *MockMerchantWalletRepositoryMockRecorder) WithTX(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTX", reflect.TypeOf((*MockMerchantWalletRepository)(nil).WithTX), tx)
}
