// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: OrderItemRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_orderitem_repository.go -package=repository . OrderItemRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrderItemRepository is a mock of OrderItemRepository interface.
type MockOrderItemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderItemRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderItemRepositoryMockRecorder is the mock recorder for MockOrderItemRepository.
type MockOrderItemRepositoryMockRecorder struct {
	mock *MockOrderItemRepository
}

// NewMockOrderItemRepository creates a new mock instance.
func NewMockOrderItemRepository(ctrl *gomock.Controller) *MockOrderItemRepository {
	mock := &MockOrderItemRepository{ctrl: ctrl}
	mock.recorder = &MockOrderItemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderItemRepository) EXPECT() *MockOrderItemRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrderItemRepository) Create(ctx context.Context, orderItem *entity.OrderItem) (*entity.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, orderItem)
	ret0, _ := ret[0].(*entity.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrderItemRepositoryMockRecorder) Create(ctx, orderItem any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderItemRepository)(nil).Create), ctx, orderItem)
}

// FindAll mocks base method.
func (m *MockOrderItemRepository) FindAll(ctx context.Context) ([]*entity.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*entity.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockOrderItemRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockOrderItemRepository)(nil).FindAll), ctx)
}

// FindByID mocks base method.
func (m *MockOrderItemRepository) FindByID(ctx context.Context, id string) (*entity.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockOrderItemRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockOrderItemRepository)(nil).FindByID), ctx, id)
}

// WithTX mocks base method.
func (m *MockOrderItemRepository) WithTX(tx repository.Tx) repository.OrderItemRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTX", tx)
	ret0, _ := ret[0].(repository.OrderItemRepository)
	return ret0
}

// WithTX indicates an expected call of WithTX.
func (mr *MockOrderItemRepositoryMockRecorder) WithTX(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTX", reflect.TypeOf((*MockOrderItemRepository)(nil).WithTX), tx)
}
