// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: TontineGroupRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_tontine_group_repository.go -package=repository . TontineGroupRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTontineGroupRepository is a mock of TontineGroupRepository interface.
type MockTontineGroupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTontineGroupRepositoryMockRecorder
	isgomock struct{}
}

// MockTontineGroupRepositoryMockRecorder is the mock recorder for MockTontineGroupRepository.
type MockTontineGroupRepositoryMockRecorder struct {
	mock *MockTontineGroupRepository
}

// NewMockTontineGroupRepository creates a new mock instance.
func NewMockTontineGroupRepository(ctrl *gomock.Controller) *MockTontineGroupRepository {
	mock := &MockTontineGroupRepository{ctrl: ctrl}
	mock.recorder = &MockTontineGroupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTontineGroupRepository) EXPECT() *MockTontineGroupRepositoryMockRecorder {
	return m.recorder
}

// Complete mocks base method.
func (m *MockTontineGroupRepository) Complete(ctx context.Context, groupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Complete indicates an expected call of Complete.
func (mr *MockTontineGroupRepositoryMockRecorder) Complete(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockTontineGroupRepository)(nil).Complete), ctx, groupID)
}

// Create mocks base method.
func (m *MockTontineGroupRepository) Create(ctx context.Context, group *entity.TontineGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTontineGroupRepositoryMockRecorder) Create(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTontineGroupRepository)(nil).Create), ctx, group)
}

// FindByCreatorCustomerID mocks base method.
func (m *MockTontineGroupRepository) FindByCreatorCustomerID(ctx context.Context, customerID string) ([]*entity.TontineGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCreatorCustomerID", ctx, customerID)
	ret0, _ := ret[0].([]*entity.TontineGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCreatorCustomerID indicates an expected call of FindByCreatorCustomerID.
func (mr *MockTontineGroupRepositoryMockRecorder) FindByCreatorCustomerID(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCreatorCustomerID", reflect.TypeOf((*MockTontineGroupRepository)(nil).FindByCreatorCustomerID), ctx, customerID)
}

// FindByID mocks base method.
func (m *MockTontineGroupRepository) FindByID(ctx context.Context, id string) (*entity.TontineGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.TontineGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTontineGroupRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTontineGroupRepository)(nil).FindByID), ctx, id)
}

// FindByInviteCode mocks base method.
func (m *MockTontineGroupRepository) FindByInviteCode(ctx context.Context, code string) (*entity.TontineGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByInviteCode", ctx, code)
	ret0, _ := ret[0].(*entity.TontineGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByInviteCode indicates an expected call of FindByInviteCode.
func (mr *MockTontineGroupRepositoryMockRecorder) FindByInviteCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByInviteCode", reflect.TypeOf((*MockTontineGroupRepository)(nil).FindByInviteCode), ctx, code)
}

// FindByProductID mocks base method.
func (m *MockTontineGroupRepository) FindByProductID(ctx context.Context, productID string) ([]*entity.TontineGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProductID", ctx, productID)
	ret0, _ := ret[0].([]*entity.TontineGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProductID indicates an expected call of FindByProductID.
func (mr *MockTontineGroupRepositoryMockRecorder) FindByProductID(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProductID", reflect.TypeOf((*MockTontineGroupRepository)(nil).FindByProductID), ctx, productID)
}

// FindByShopID mocks base method.
func (m *MockTontineGroupRepository) FindByShopID(ctx context.Context, shopID string) ([]*entity.TontineGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.TontineGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShopID indicates an expected call of FindByShopID.
func (mr *MockTontineGroupRepositoryMockRecorder) FindByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShopID", reflect.TypeOf((*MockTontineGroupRepository)(nil).FindByShopID), ctx, shopID)
}

// IncrementCycle mocks base method.
func (m *MockTontineGroupRepository) IncrementCycle(ctx context.Context, groupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementCycle", ctx, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementCycle indicates an expected call of IncrementCycle.
func (mr *MockTontineGroupRepositoryMockRecorder) IncrementCycle(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCycle", reflect.TypeOf((*MockTontineGroupRepository)(nil).IncrementCycle), ctx, groupID)
}

// Start mocks base method.
func (m *MockTontineGroupRepository) Start(ctx context.Context, groupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockTontineGroupRepositoryMockRecorder) Start(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockTontineGroupRepository)(nil).Start), ctx, groupID)
}

// UpdateStatus mocks base method.
func (m *MockTontineGroupRepository) UpdateStatus(ctx context.Context, groupID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, groupID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockTontineGroupRepositoryMockRecorder) UpdateStatus(ctx, groupID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockTontineGroupRepository)(nil).UpdateStatus), ctx, groupID, status)
}

// WithTX mocks base method.
func (m *MockTontineGroupRepository) WithTX(tx repository.Tx) repository.TontineGroupRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTX", tx)
	ret0, _ := ret[0].(repository.TontineGroupRepository)
	return ret0
}

// WithTX indicates an expected call of WithTX.
func (mr *MockTontineGroupRepositoryMockRecorder) WithTX(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTX", reflect.TypeOf((*MockTontineGroupRepository)(nil).WithTX), tx)
}
