// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: CustomerReliabilityScoreRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_customer_reliability_score_repository.go -package=repository . CustomerReliabilityScoreRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCustomerReliabilityScoreRepository is a mock of CustomerReliabilityScoreRepository interface.
type MockCustomerReliabilityScoreRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerReliabilityScoreRepositoryMockRecorder
	isgomock struct{}
}

// MockCustomerReliabilityScoreRepositoryMockRecorder is the mock recorder for MockCustomerReliabilityScoreRepository.
type MockCustomerReliabilityScoreRepositoryMockRecorder struct {
	mock *MockCustomerReliabilityScoreRepository
}

// NewMockCustomerReliabilityScoreRepository creates a new mock instance.
func NewMockCustomerReliabilityScoreRepository(ctrl *gomock.Controller) *MockCustomerReliabilityScoreRepository {
	mock := &MockCustomerReliabilityScoreRepository{ctrl: ctrl}
	mock.recorder = &MockCustomerReliabilityScoreRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerReliabilityScoreRepository) EXPECT() *MockCustomerReliabilityScoreRepositoryMockRecorder {
	return m.recorder
}

// CountByTier mocks base method.
func (m *MockCustomerReliabilityScoreRepository) CountByTier(ctx context.Context, tier entity.ReliabilityTier) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByTier", ctx, tier)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByTier indicates an expected call of CountByTier.
func (mr *MockCustomerReliabilityScoreRepositoryMockRecorder) CountByTier(ctx, tier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByTier", reflect.TypeOf((*MockCustomerReliabilityScoreRepository)(nil).CountByTier), ctx, tier)
}

// Create mocks base method.
func (m *MockCustomerReliabilityScoreRepository) Create(ctx context.Context, score *entity.CustomerReliabilityScore) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCustomerReliabilityScoreRepositoryMockRecorder) Create(ctx, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomerReliabilityScoreRepository)(nil).Create), ctx, score)
}

// FindByCustomerID mocks base method.
func (m *MockCustomerReliabilityScoreRepository) FindByCustomerID(ctx context.Context, customerID string) (*entity.CustomerReliabilityScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCustomerID", ctx, customerID)
	ret0, _ := ret[0].(*entity.CustomerReliabilityScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCustomerID indicates an expected call of FindByCustomerID.
func (mr *MockCustomerReliabilityScoreRepositoryMockRecorder) FindByCustomerID(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCustomerID", reflect.TypeOf((*MockCustomerReliabilityScoreRepository)(nil).FindByCustomerID), ctx, customerID)
}

// GetAverageScore mocks base method.
func (m *MockCustomerReliabilityScoreRepository) GetAverageScore(ctx context.Context) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAverageScore", ctx)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAverageScore indicates an expected call of GetAverageScore.
func (mr *MockCustomerReliabilityScoreRepositoryMockRecorder) GetAverageScore(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAverageScore", reflect.TypeOf((*MockCustomerReliabilityScoreRepository)(nil).GetAverageScore), ctx)
}

// GetCustomersWithCompletedTontineCycles mocks base method.
func (m *MockCustomerReliabilityScoreRepository) GetCustomersWithCompletedTontineCycles(ctx context.Context, sinceDays int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomersWithCompletedTontineCycles", ctx, sinceDays)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomersWithCompletedTontineCycles indicates an expected call of GetCustomersWithCompletedTontineCycles.
func (mr *MockCustomerReliabilityScoreRepositoryMockRecorder) GetCustomersWithCompletedTontineCycles(ctx, sinceDays any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomersWithCompletedTontineCycles", reflect.TypeOf((*MockCustomerReliabilityScoreRepository)(nil).GetCustomersWithCompletedTontineCycles), ctx, sinceDays)
}

// GetCustomersWithOverdueInstallments mocks base method.
func (m *MockCustomerReliabilityScoreRepository) GetCustomersWithOverdueInstallments(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomersWithOverdueInstallments", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomersWithOverdueInstallments indicates an expected call of GetCustomersWithOverdueInstallments.
func (mr *MockCustomerReliabilityScoreRepositoryMockRecorder) GetCustomersWithOverdueInstallments(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomersWithOverdueInstallments", reflect.TypeOf((*MockCustomerReliabilityScoreRepository)(nil).GetCustomersWithOverdueInstallments), ctx)
}

// GetCustomersWithSuccessfulCODOrders mocks base method.
func (m *MockCustomerReliabilityScoreRepository) GetCustomersWithSuccessfulCODOrders(ctx context.Context, sinceDays int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomersWithSuccessfulCODOrders", ctx, sinceDays)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomersWithSuccessfulCODOrders indicates an expected call of GetCustomersWithSuccessfulCODOrders.
func (mr *MockCustomerReliabilityScoreRepositoryMockRecorder) GetCustomersWithSuccessfulCODOrders(ctx, sinceDays any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomersWithSuccessfulCODOrders", reflect.TypeOf((*MockCustomerReliabilityScoreRepository)(nil).GetCustomersWithSuccessfulCODOrders), ctx, sinceDays)
}

// Update mocks base method.
func (m *MockCustomerReliabilityScoreRepository) Update(ctx context.Context, score *entity.CustomerReliabilityScore) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCustomerReliabilityScoreRepositoryMockRecorder) Update(ctx, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomerReliabilityScoreRepository)(nil).Update), ctx, score)
}

// Upsert mocks base method.
func (m *MockCustomerReliabilityScoreRepository) Upsert(ctx context.Context, score *entity.CustomerReliabilityScore) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockCustomerReliabilityScoreRepositoryMockRecorder) Upsert(ctx, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockCustomerReliabilityScoreRepository)(nil).Upsert), ctx, score)
}

// WithTX mocks base method.
func (m *MockCustomerReliabilityScoreRepository) WithTX(tx repository.Tx) repository.CustomerReliabilityScoreRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTX", tx)
	ret0, _ := ret[0].(repository.CustomerReliabilityScoreRepository)
	return ret0
}

// WithTX indicates an expected call of WithTX.
func (mr *MockCustomerReliabilityScoreRepositoryMockRecorder) WithTX(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTX", reflect.TypeOf((*MockCustomerReliabilityScoreRepository)(nil).WithTX), tx)
}
