// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: CreditScoreRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_credit_score_repository.go -package=repository . CreditScoreRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreditScoreRepository is a mock of CreditScoreRepository interface.
type MockCreditScoreRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCreditScoreRepositoryMockRecorder
	isgomock struct{}
}

// MockCreditScoreRepositoryMockRecorder is the mock recorder for MockCreditScoreRepository.
type MockCreditScoreRepositoryMockRecorder struct {
	mock *MockCreditScoreRepository
}

// NewMockCreditScoreRepository creates a new mock instance.
func NewMockCreditScoreRepository(ctrl *gomock.Controller) *MockCreditScoreRepository {
	mock := &MockCreditScoreRepository{ctrl: ctrl}
	mock.recorder = &MockCreditScoreRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreditScoreRepository) EXPECT() *MockCreditScoreRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCreditScoreRepository) Create(ctx context.Context, score *entity.CreditScore) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCreditScoreRepositoryMockRecorder) Create(ctx, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCreditScoreRepository)(nil).Create), ctx, score)
}

// FindByCustomerAndShop mocks base method.
func (m *MockCreditScoreRepository) FindByCustomerAndShop(ctx context.Context, customerID, shopID string) (*entity.CreditScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCustomerAndShop", ctx, customerID, shopID)
	ret0, _ := ret[0].(*entity.CreditScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCustomerAndShop indicates an expected call of FindByCustomerAndShop.
func (mr *MockCreditScoreRepositoryMockRecorder) FindByCustomerAndShop(ctx, customerID, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCustomerAndShop", reflect.TypeOf((*MockCreditScoreRepository)(nil).FindByCustomerAndShop), ctx, customerID, shopID)
}

// FindByCustomerID mocks base method.
func (m *MockCreditScoreRepository) FindByCustomerID(ctx context.Context, customerID string) ([]*entity.CreditScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCustomerID", ctx, customerID)
	ret0, _ := ret[0].([]*entity.CreditScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCustomerID indicates an expected call of FindByCustomerID.
func (mr *MockCreditScoreRepositoryMockRecorder) FindByCustomerID(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCustomerID", reflect.TypeOf((*MockCreditScoreRepository)(nil).FindByCustomerID), ctx, customerID)
}

// FindByShopID mocks base method.
func (m *MockCreditScoreRepository) FindByShopID(ctx context.Context, shopID string) ([]*entity.CreditScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.CreditScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShopID indicates an expected call of FindByShopID.
func (mr *MockCreditScoreRepositoryMockRecorder) FindByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShopID", reflect.TypeOf((*MockCreditScoreRepository)(nil).FindByShopID), ctx, shopID)
}

// FindLowScores mocks base method.
func (m *MockCreditScoreRepository) FindLowScores(ctx context.Context, shopID string, minScore int) ([]*entity.CreditScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLowScores", ctx, shopID, minScore)
	ret0, _ := ret[0].([]*entity.CreditScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLowScores indicates an expected call of FindLowScores.
func (mr *MockCreditScoreRepositoryMockRecorder) FindLowScores(ctx, shopID, minScore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLowScores", reflect.TypeOf((*MockCreditScoreRepository)(nil).FindLowScores), ctx, shopID, minScore)
}

// Update mocks base method.
func (m *MockCreditScoreRepository) Update(ctx context.Context, score *entity.CreditScore) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCreditScoreRepositoryMockRecorder) Update(ctx, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCreditScoreRepository)(nil).Update), ctx, score)
}

// Upsert mocks base method.
func (m *MockCreditScoreRepository) Upsert(ctx context.Context, score *entity.CreditScore) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockCreditScoreRepositoryMockRecorder) Upsert(ctx, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockCreditScoreRepository)(nil).Upsert), ctx, score)
}

// WithTX mocks base method.
func (m *MockCreditScoreRepository) WithTX(tx repository.Tx) repository.CreditScoreRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTX", tx)
	ret0, _ := ret[0].(repository.CreditScoreRepository)
	return ret0
}

// WithTX indicates an expected call of WithTX.
func (mr *MockCreditScoreRepositoryMockRecorder) WithTX(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTX", reflect.TypeOf((*MockCreditScoreRepository)(nil).WithTX), tx)
}
