// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: CODProofRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_cod_proof_repository.go -package=repository . CODProofRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCODProofRepository is a mock of CODProofRepository interface.
type MockCODProofRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCODProofRepositoryMockRecorder
	isgomock struct{}
}

// MockCODProofRepositoryMockRecorder is the mock recorder for MockCODProofRepository.
type MockCODProofRepositoryMockRecorder struct {
	mock *MockCODProofRepository
}

// NewMockCODProofRepository creates a new mock instance.
func NewMockCODProofRepository(ctrl *gomock.Controller) *MockCODProofRepository {
	mock := &MockCODProofRepository{ctrl: ctrl}
	mock.recorder = &MockCODProofRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCODProofRepository) EXPECT() *MockCODProofRepositoryMockRecorder {
	return m.recorder
}

// CountByStatusByShopID mocks base method.
func (m *MockCODProofRepository) CountByStatusByShopID(ctx context.Context, shopID string, status entity.CODProofStatus) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByStatusByShopID", ctx, shopID, status)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByStatusByShopID indicates an expected call of CountByStatusByShopID.
func (mr *MockCODProofRepositoryMockRecorder) CountByStatusByShopID(ctx, shopID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByStatusByShopID", reflect.TypeOf((*MockCODProofRepository)(nil).CountByStatusByShopID), ctx, shopID, status)
}

// CountConfirmedByShopID mocks base method.
func (m *MockCODProofRepository) CountConfirmedByShopID(ctx context.Context, shopID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountConfirmedByShopID", ctx, shopID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountConfirmedByShopID indicates an expected call of CountConfirmedByShopID.
func (mr *MockCODProofRepositoryMockRecorder) CountConfirmedByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountConfirmedByShopID", reflect.TypeOf((*MockCODProofRepository)(nil).CountConfirmedByShopID), ctx, shopID)
}

// CountDisputedByShopID mocks base method.
func (m *MockCODProofRepository) CountDisputedByShopID(ctx context.Context, shopID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDisputedByShopID", ctx, shopID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDisputedByShopID indicates an expected call of CountDisputedByShopID.
func (mr *MockCODProofRepositoryMockRecorder) CountDisputedByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDisputedByShopID", reflect.TypeOf((*MockCODProofRepository)(nil).CountDisputedByShopID), ctx, shopID)
}

// CountPendingByShopID mocks base method.
func (m *MockCODProofRepository) CountPendingByShopID(ctx context.Context, shopID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPendingByShopID", ctx, shopID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPendingByShopID indicates an expected call of CountPendingByShopID.
func (mr *MockCODProofRepositoryMockRecorder) CountPendingByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPendingByShopID", reflect.TypeOf((*MockCODProofRepository)(nil).CountPendingByShopID), ctx, shopID)
}

// Create mocks base method.
func (m *MockCODProofRepository) Create(ctx context.Context, proof *entity.CODProof) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, proof)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCODProofRepositoryMockRecorder) Create(ctx, proof any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCODProofRepository)(nil).Create), ctx, proof)
}

// FindByCommissionStatus mocks base method.
func (m *MockCODProofRepository) FindByCommissionStatus(ctx context.Context, status entity.CODCommissionStatus) ([]*entity.CODProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCommissionStatus", ctx, status)
	ret0, _ := ret[0].([]*entity.CODProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCommissionStatus indicates an expected call of FindByCommissionStatus.
func (mr *MockCODProofRepositoryMockRecorder) FindByCommissionStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCommissionStatus", reflect.TypeOf((*MockCODProofRepository)(nil).FindByCommissionStatus), ctx, status)
}

// FindByCustomerID mocks base method.
func (m *MockCODProofRepository) FindByCustomerID(ctx context.Context, customerID string) ([]*entity.CODProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCustomerID", ctx, customerID)
	ret0, _ := ret[0].([]*entity.CODProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCustomerID indicates an expected call of FindByCustomerID.
func (mr *MockCODProofRepositoryMockRecorder) FindByCustomerID(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCustomerID", reflect.TypeOf((*MockCODProofRepository)(nil).FindByCustomerID), ctx, customerID)
}

// FindByID mocks base method.
func (m *MockCODProofRepository) FindByID(ctx context.Context, id string) (*entity.CODProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.CODProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCODProofRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCODProofRepository)(nil).FindByID), ctx, id)
}

// FindByOrderID mocks base method.
func (m *MockCODProofRepository) FindByOrderID(ctx context.Context, orderID string) (*entity.CODProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*entity.CODProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOrderID indicates an expected call of FindByOrderID.
func (mr *MockCODProofRepositoryMockRecorder) FindByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOrderID", reflect.TypeOf((*MockCODProofRepository)(nil).FindByOrderID), ctx, orderID)
}

// FindByShopID mocks base method.
func (m *MockCODProofRepository) FindByShopID(ctx context.Context, shopID string) ([]*entity.CODProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.CODProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShopID indicates an expected call of FindByShopID.
func (mr *MockCODProofRepositoryMockRecorder) FindByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShopID", reflect.TypeOf((*MockCODProofRepository)(nil).FindByShopID), ctx, shopID)
}

// FindByShopIDAndStatus mocks base method.
func (m *MockCODProofRepository) FindByShopIDAndStatus(ctx context.Context, shopID string, status entity.CODProofStatus) ([]*entity.CODProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShopIDAndStatus", ctx, shopID, status)
	ret0, _ := ret[0].([]*entity.CODProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShopIDAndStatus indicates an expected call of FindByShopIDAndStatus.
func (mr *MockCODProofRepositoryMockRecorder) FindByShopIDAndStatus(ctx, shopID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShopIDAndStatus", reflect.TypeOf((*MockCODProofRepository)(nil).FindByShopIDAndStatus), ctx, shopID, status)
}

// FindByStatus mocks base method.
func (m *MockCODProofRepository) FindByStatus(ctx context.Context, status entity.CODProofStatus) ([]*entity.CODProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByStatus", ctx, status)
	ret0, _ := ret[0].([]*entity.CODProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByStatus indicates an expected call of FindByStatus.
func (mr *MockCODProofRepositoryMockRecorder) FindByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByStatus", reflect.TypeOf((*MockCODProofRepository)(nil).FindByStatus), ctx, status)
}

// FindCommissionDue mocks base method.
func (m *MockCODProofRepository) FindCommissionDue(ctx context.Context) ([]*entity.CODProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCommissionDue", ctx)
	ret0, _ := ret[0].([]*entity.CODProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCommissionDue indicates an expected call of FindCommissionDue.
func (mr *MockCODProofRepositoryMockRecorder) FindCommissionDue(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCommissionDue", reflect.TypeOf((*MockCODProofRepository)(nil).FindCommissionDue), ctx)
}

// FindCommissionDueByShopID mocks base method.
func (m *MockCODProofRepository) FindCommissionDueByShopID(ctx context.Context, shopID string) ([]*entity.CODProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCommissionDueByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.CODProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCommissionDueByShopID indicates an expected call of FindCommissionDueByShopID.
func (mr *MockCODProofRepositoryMockRecorder) FindCommissionDueByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCommissionDueByShopID", reflect.TypeOf((*MockCODProofRepository)(nil).FindCommissionDueByShopID), ctx, shopID)
}

// FindCompletedProofs mocks base method.
func (m *MockCODProofRepository) FindCompletedProofs(ctx context.Context) ([]*entity.CODProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCompletedProofs", ctx)
	ret0, _ := ret[0].([]*entity.CODProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCompletedProofs indicates an expected call of FindCompletedProofs.
func (mr *MockCODProofRepositoryMockRecorder) FindCompletedProofs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCompletedProofs", reflect.TypeOf((*MockCODProofRepository)(nil).FindCompletedProofs), ctx)
}

// FindCompletedProofsByShopID mocks base method.
func (m *MockCODProofRepository) FindCompletedProofsByShopID(ctx context.Context, shopID string) ([]*entity.CODProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCompletedProofsByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.CODProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCompletedProofsByShopID indicates an expected call of FindCompletedProofsByShopID.
func (mr *MockCODProofRepositoryMockRecorder) FindCompletedProofsByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCompletedProofsByShopID", reflect.TypeOf((*MockCODProofRepository)(nil).FindCompletedProofsByShopID), ctx, shopID)
}

// FindConfirmedProofs mocks base method.
func (m *MockCODProofRepository) FindConfirmedProofs(ctx context.Context) ([]*entity.CODProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindConfirmedProofs", ctx)
	ret0, _ := ret[0].([]*entity.CODProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindConfirmedProofs indicates an expected call of FindConfirmedProofs.
func (mr *MockCODProofRepositoryMockRecorder) FindConfirmedProofs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindConfirmedProofs", reflect.TypeOf((*MockCODProofRepository)(nil).FindConfirmedProofs), ctx)
}

// FindConfirmedProofsByShopID mocks base method.
func (m *MockCODProofRepository) FindConfirmedProofsByShopID(ctx context.Context, shopID string) ([]*entity.CODProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindConfirmedProofsByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.CODProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindConfirmedProofsByShopID indicates an expected call of FindConfirmedProofsByShopID.
func (mr *MockCODProofRepositoryMockRecorder) FindConfirmedProofsByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindConfirmedProofsByShopID", reflect.TypeOf((*MockCODProofRepository)(nil).FindConfirmedProofsByShopID), ctx, shopID)
}

// FindDisputedProofs mocks base method.
func (m *MockCODProofRepository) FindDisputedProofs(ctx context.Context) ([]*entity.CODProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDisputedProofs", ctx)
	ret0, _ := ret[0].([]*entity.CODProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDisputedProofs indicates an expected call of FindDisputedProofs.
func (mr *MockCODProofRepositoryMockRecorder) FindDisputedProofs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDisputedProofs", reflect.TypeOf((*MockCODProofRepository)(nil).FindDisputedProofs), ctx)
}

// FindDisputedProofsByShopID mocks base method.
func (m *MockCODProofRepository) FindDisputedProofsByShopID(ctx context.Context, shopID string) ([]*entity.CODProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDisputedProofsByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.CODProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDisputedProofsByShopID indicates an expected call of FindDisputedProofsByShopID.
func (mr *MockCODProofRepositoryMockRecorder) FindDisputedProofsByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDisputedProofsByShopID", reflect.TypeOf((*MockCODProofRepository)(nil).FindDisputedProofsByShopID), ctx, shopID)
}

// FindIncoherentProofs mocks base method.
func (m *MockCODProofRepository) FindIncoherentProofs(ctx context.Context) ([]*entity.CODProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindIncoherentProofs", ctx)
	ret0, _ := ret[0].([]*entity.CODProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindIncoherentProofs indicates an expected call of FindIncoherentProofs.
func (mr *MockCODProofRepositoryMockRecorder) FindIncoherentProofs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindIncoherentProofs", reflect.TypeOf((*MockCODProofRepository)(nil).FindIncoherentProofs), ctx)
}

// FindPastDeadlineProofs mocks base method.
func (m *MockCODProofRepository) FindPastDeadlineProofs(ctx context.Context) ([]*entity.CODProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPastDeadlineProofs", ctx)
	ret0, _ := ret[0].([]*entity.CODProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPastDeadlineProofs indicates an expected call of FindPastDeadlineProofs.
func (mr *MockCODProofRepositoryMockRecorder) FindPastDeadlineProofs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPastDeadlineProofs", reflect.TypeOf((*MockCODProofRepository)(nil).FindPastDeadlineProofs), ctx)
}

// FindPastDeadlineProofsByShopID mocks base method.
func (m *MockCODProofRepository) FindPastDeadlineProofsByShopID(ctx context.Context, shopID string) ([]*entity.CODProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPastDeadlineProofsByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.CODProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPastDeadlineProofsByShopID indicates an expected call of FindPastDeadlineProofsByShopID.
func (mr *MockCODProofRepositoryMockRecorder) FindPastDeadlineProofsByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPastDeadlineProofsByShopID", reflect.TypeOf((*MockCODProofRepository)(nil).FindPastDeadlineProofsByShopID), ctx, shopID)
}

// FindPendingProofs mocks base method.
func (m *MockCODProofRepository) FindPendingProofs(ctx context.Context) ([]*entity.CODProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPendingProofs", ctx)
	ret0, _ := ret[0].([]*entity.CODProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPendingProofs indicates an expected call of FindPendingProofs.
func (mr *MockCODProofRepositoryMockRecorder) FindPendingProofs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPendingProofs", reflect.TypeOf((*MockCODProofRepository)(nil).FindPendingProofs), ctx)
}

// FindPendingProofsByShopID mocks base method.
func (m *MockCODProofRepository) FindPendingProofsByShopID(ctx context.Context, shopID string) ([]*entity.CODProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPendingProofsByShopID", ctx, shopID)
	ret0, _ := ret[0].([]*entity.CODProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPendingProofsByShopID indicates an expected call of FindPendingProofsByShopID.
func (mr *MockCODProofRepositoryMockRecorder) FindPendingProofsByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPendingProofsByShopID", reflect.TypeOf((*MockCODProofRepository)(nil).FindPendingProofsByShopID), ctx, shopID)
}

// SumCommissionCollectedByShopID mocks base method.
func (m *MockCODProofRepository) SumCommissionCollectedByShopID(ctx context.Context, shopID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumCommissionCollectedByShopID", ctx, shopID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumCommissionCollectedByShopID indicates an expected call of SumCommissionCollectedByShopID.
func (mr *MockCODProofRepositoryMockRecorder) SumCommissionCollectedByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumCommissionCollectedByShopID", reflect.TypeOf((*MockCODProofRepository)(nil).SumCommissionCollectedByShopID), ctx, shopID)
}

// SumCommissionDueByShopID mocks base method.
func (m *MockCODProofRepository) SumCommissionDueByShopID(ctx context.Context, shopID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumCommissionDueByShopID", ctx, shopID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumCommissionDueByShopID indicates an expected call of SumCommissionDueByShopID.
func (mr *MockCODProofRepositoryMockRecorder) SumCommissionDueByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumCommissionDueByShopID", reflect.TypeOf((*MockCODProofRepository)(nil).SumCommissionDueByShopID), ctx, shopID)
}

// SumCommissionPendingByShopID mocks base method.
func (m *MockCODProofRepository) SumCommissionPendingByShopID(ctx context.Context, shopID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumCommissionPendingByShopID", ctx, shopID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumCommissionPendingByShopID indicates an expected call of SumCommissionPendingByShopID.
func (mr *MockCODProofRepositoryMockRecorder) SumCommissionPendingByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumCommissionPendingByShopID", reflect.TypeOf((*MockCODProofRepository)(nil).SumCommissionPendingByShopID), ctx, shopID)
}

// SumTotalCommissionCollected mocks base method.
func (m *MockCODProofRepository) SumTotalCommissionCollected(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumTotalCommissionCollected", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumTotalCommissionCollected indicates an expected call of SumTotalCommissionCollected.
func (mr *MockCODProofRepositoryMockRecorder) SumTotalCommissionCollected(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumTotalCommissionCollected", reflect.TypeOf((*MockCODProofRepository)(nil).SumTotalCommissionCollected), ctx)
}

// SumTotalCommissionDue mocks base method.
func (m *MockCODProofRepository) SumTotalCommissionDue(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumTotalCommissionDue", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumTotalCommissionDue indicates an expected call of SumTotalCommissionDue.
func (mr *MockCODProofRepositoryMockRecorder) SumTotalCommissionDue(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumTotalCommissionDue", reflect.TypeOf((*MockCODProofRepository)(nil).SumTotalCommissionDue), ctx)
}

// SumTotalCommissionPending mocks base method.
func (m *MockCODProofRepository) SumTotalCommissionPending(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumTotalCommissionPending", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumTotalCommissionPending indicates an expected call of SumTotalCommissionPending.
func (mr *MockCODProofRepositoryMockRecorder) SumTotalCommissionPending(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumTotalCommissionPending", reflect.TypeOf((*MockCODProofRepository)(nil).SumTotalCommissionPending), ctx)
}

// Update mocks base method.
func (m *MockCODProofRepository) Update(ctx context.Context, proof *entity.CODProof) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, proof)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCODProofRepositoryMockRecorder) Update(ctx, proof any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCODProofRepository)(nil).Update), ctx, proof)
}

// UpdateCommissionStatus mocks base method.
func (m *MockCODProofRepository) UpdateCommissionStatus(ctx context.Context, id string, status entity.CODCommissionStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCommissionStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCommissionStatus indicates an expected call of UpdateCommissionStatus.
func (mr *MockCODProofRepositoryMockRecorder) UpdateCommissionStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCommissionStatus", reflect.TypeOf((*MockCODProofRepository)(nil).UpdateCommissionStatus), ctx, id, status)
}

// UpdateStatus mocks base method.
func (m *MockCODProofRepository) UpdateStatus(ctx context.Context, id string, status entity.CODProofStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockCODProofRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockCODProofRepository)(nil).UpdateStatus), ctx, id, status)
}

// WithTX mocks base method.
func (m *MockCODProofRepository) WithTX(tx repository.Tx) repository.CODProofRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTX", tx)
	ret0, _ := ret[0].(repository.CODProofRepository)
	return ret0
}

// WithTX indicates an expected call of WithTX.
func (mr *MockCODProofRepositoryMockRecorder) WithTX(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTX", reflect.TypeOf((*MockCODProofRepository)(nil).WithTX), tx)
}
