// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository (interfaces: User2FARepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_user_2fa_repository.go -package=repository . User2FARepository
//

// Package repository is a generated GoMock package.
package repository

import (
	entity "Goshop/domain/entity"
	repository "Goshop/domain/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUser2FARepository is a mock of User2FARepository interface.
type MockUser2FARepository struct {
	ctrl     *gomock.Controller
	recorder *MockUser2FARepositoryMockRecorder
	isgomock struct{}
}

// MockUser2FARepositoryMockRecorder is the mock recorder for MockUser2FARepository.
type MockUser2FARepositoryMockRecorder struct {
	mock *MockUser2FARepository
}

// NewMockUser2FARepository creates a new mock instance.
func NewMockUser2FARepository(ctrl *gomock.Controller) *MockUser2FARepository {
	mock := &MockUser2FARepository{ctrl: ctrl}
	mock.recorder = &MockUser2FARepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUser2FARepository) EXPECT() *MockUser2FARepositoryMockRecorder {
	return m.recorder
}

// CountEnabled mocks base method.
func (m *MockUser2FARepository) CountEnabled(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEnabled", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEnabled indicates an expected call of CountEnabled.
func (mr *MockUser2FARepositoryMockRecorder) CountEnabled(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEnabled", reflect.TypeOf((*MockUser2FARepository)(nil).CountEnabled), ctx)
}

// CountLocked mocks base method.
func (m *MockUser2FARepository) CountLocked(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountLocked", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountLocked indicates an expected call of CountLocked.
func (mr *MockUser2FARepositoryMockRecorder) CountLocked(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountLocked", reflect.TypeOf((*MockUser2FARepository)(nil).CountLocked), ctx)
}

// Create mocks base method.
func (m *MockUser2FARepository) Create(ctx context.Context, user2fa *entity.User2FA) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user2fa)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUser2FARepositoryMockRecorder) Create(ctx, user2fa any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUser2FARepository)(nil).Create), ctx, user2fa)
}

// Delete mocks base method.
func (m *MockUser2FARepository) Delete(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUser2FARepositoryMockRecorder) Delete(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUser2FARepository)(nil).Delete), ctx, userID)
}

// Disable2FA mocks base method.
func (m *MockUser2FARepository) Disable2FA(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable2FA", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disable2FA indicates an expected call of Disable2FA.
func (mr *MockUser2FARepositoryMockRecorder) Disable2FA(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable2FA", reflect.TypeOf((*MockUser2FARepository)(nil).Disable2FA), ctx, userID)
}

// Enable2FA mocks base method.
func (m *MockUser2FARepository) Enable2FA(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enable2FA", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enable2FA indicates an expected call of Enable2FA.
func (mr *MockUser2FARepositoryMockRecorder) Enable2FA(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enable2FA", reflect.TypeOf((*MockUser2FARepository)(nil).Enable2FA), ctx, userID)
}

// Exists mocks base method.
func (m *MockUser2FARepository) Exists(ctx context.Context, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockUser2FARepositoryMockRecorder) Exists(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockUser2FARepository)(nil).Exists), ctx, userID)
}

// FindByUserID mocks base method.
func (m *MockUser2FARepository) FindByUserID(ctx context.Context, userID string) (*entity.User2FA, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.User2FA)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockUser2FARepositoryMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockUser2FARepository)(nil).FindByUserID), ctx, userID)
}

// GetStatistics mocks base method.
func (m *MockUser2FARepository) GetStatistics(ctx context.Context) (*repository.User2FAStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatistics", ctx)
	ret0, _ := ret[0].(*repository.User2FAStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatistics indicates an expected call of GetStatistics.
func (mr *MockUser2FARepositoryMockRecorder) GetStatistics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatistics", reflect.TypeOf((*MockUser2FARepository)(nil).GetStatistics), ctx)
}

// IncrementFailedAttempts mocks base method.
func (m *MockUser2FARepository) IncrementFailedAttempts(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementFailedAttempts", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementFailedAttempts indicates an expected call of IncrementFailedAttempts.
func (mr *MockUser2FARepositoryMockRecorder) IncrementFailedAttempts(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementFailedAttempts", reflect.TypeOf((*MockUser2FARepository)(nil).IncrementFailedAttempts), ctx, userID)
}

// IsAccountLocked mocks base method.
func (m *MockUser2FARepository) IsAccountLocked(ctx context.Context, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAccountLocked", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAccountLocked indicates an expected call of IsAccountLocked.
func (mr *MockUser2FARepositoryMockRecorder) IsAccountLocked(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAccountLocked", reflect.TypeOf((*MockUser2FARepository)(nil).IsAccountLocked), ctx, userID)
}

// ListEnabledUsers mocks base method.
func (m *MockUser2FARepository) ListEnabledUsers(ctx context.Context, limit, offset int) ([]*entity.User2FA, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnabledUsers", ctx, limit, offset)
	ret0, _ := ret[0].([]*entity.User2FA)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEnabledUsers indicates an expected call of ListEnabledUsers.
func (mr *MockUser2FARepositoryMockRecorder) ListEnabledUsers(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnabledUsers", reflect.TypeOf((*MockUser2FARepository)(nil).ListEnabledUsers), ctx, limit, offset)
}

// LockAccount mocks base method.
func (m *MockUser2FARepository) LockAccount(ctx context.Context, userID string, durationMinutes int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockAccount", ctx, userID, durationMinutes)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockAccount indicates an expected call of LockAccount.
func (mr *MockUser2FARepositoryMockRecorder) LockAccount(ctx, userID, durationMinutes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockAccount", reflect.TypeOf((*MockUser2FARepository)(nil).LockAccount), ctx, userID, durationMinutes)
}

// MarkRecoveryCodeUsed mocks base method.
func (m *MockUser2FARepository) MarkRecoveryCodeUsed(ctx context.Context, userID string, codeIndex int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRecoveryCodeUsed", ctx, userID, codeIndex)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRecoveryCodeUsed indicates an expected call of MarkRecoveryCodeUsed.
func (mr *MockUser2FARepositoryMockRecorder) MarkRecoveryCodeUsed(ctx, userID, codeIndex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRecoveryCodeUsed", reflect.TypeOf((*MockUser2FARepository)(nil).MarkRecoveryCodeUsed), ctx, userID, codeIndex)
}

// RecordCodeUsed mocks base method.
func (m *MockUser2FARepository) RecordCodeUsed(ctx context.Context, userID, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordCodeUsed", ctx, userID, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordCodeUsed indicates an expected call of RecordCodeUsed.
func (mr *MockUser2FARepositoryMockRecorder) RecordCodeUsed(ctx, userID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordCodeUsed", reflect.TypeOf((*MockUser2FARepository)(nil).RecordCodeUsed), ctx, userID, code)
}

// RecordSuccessfulVerification mocks base method.
func (m *MockUser2FARepository) RecordSuccessfulVerification(ctx context.Context, userID, ipAddress, userAgent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordSuccessfulVerification", ctx, userID, ipAddress, userAgent)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordSuccessfulVerification indicates an expected call of RecordSuccessfulVerification.
func (mr *MockUser2FARepositoryMockRecorder) RecordSuccessfulVerification(ctx, userID, ipAddress, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordSuccessfulVerification", reflect.TypeOf((*MockUser2FARepository)(nil).RecordSuccessfulVerification), ctx, userID, ipAddress, userAgent)
}

// ResetFailedAttempts mocks base method.
func (m *MockUser2FARepository) ResetFailedAttempts(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetFailedAttempts", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetFailedAttempts indicates an expected call of ResetFailedAttempts.
func (mr *MockUser2FARepositoryMockRecorder) ResetFailedAttempts(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetFailedAttempts", reflect.TypeOf((*MockUser2FARepository)(nil).ResetFailedAttempts), ctx, userID)
}

// ResetRecoveryCodes mocks base method.
func (m *MockUser2FARepository) ResetRecoveryCodes(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetRecoveryCodes", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetRecoveryCodes indicates an expected call of ResetRecoveryCodes.
func (mr *MockUser2FARepositoryMockRecorder) ResetRecoveryCodes(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetRecoveryCodes", reflect.TypeOf((*MockUser2FARepository)(nil).ResetRecoveryCodes), ctx, userID)
}

// UnlockAccount mocks base method.
func (m *MockUser2FARepository) UnlockAccount(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockAccount", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlockAccount indicates an expected call of UnlockAccount.
func (mr *MockUser2FARepositoryMockRecorder) UnlockAccount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockAccount", reflect.TypeOf((*MockUser2FARepository)(nil).UnlockAccount), ctx, userID)
}

// Update mocks base method.
func (m *MockUser2FARepository) Update(ctx context.Context, user2fa *entity.User2FA) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user2fa)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUser2FARepositoryMockRecorder) Update(ctx, user2fa any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUser2FARepository)(nil).Update), ctx, user2fa)
}

// UpdateLastActivity mocks base method.
func (m *MockUser2FARepository) UpdateLastActivity(ctx context.Context, userID, ipAddress, userAgent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastActivity", ctx, userID, ipAddress, userAgent)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastActivity indicates an expected call of UpdateLastActivity.
func (mr *MockUser2FARepositoryMockRecorder) UpdateLastActivity(ctx, userID, ipAddress, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastActivity", reflect.TypeOf((*MockUser2FARepository)(nil).UpdateLastActivity), ctx, userID, ipAddress, userAgent)
}

// UpdateRecoveryCodes mocks base method.
func (m *MockUser2FARepository) UpdateRecoveryCodes(ctx context.Context, userID, codesEncrypted string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecoveryCodes", ctx, userID, codesEncrypted)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRecoveryCodes indicates an expected call of UpdateRecoveryCodes.
func (mr *MockUser2FARepositoryMockRecorder) UpdateRecoveryCodes(ctx, userID, codesEncrypted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecoveryCodes", reflect.TypeOf((*MockUser2FARepository)(nil).UpdateRecoveryCodes), ctx, userID, codesEncrypted)
}

// UpdateSecret mocks base method.
func (m *MockUser2FARepository) UpdateSecret(ctx context.Context, userID, secretEncrypted string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecret", ctx, userID, secretEncrypted)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSecret indicates an expected call of UpdateSecret.
func (mr *MockUser2FARepositoryMockRecorder) UpdateSecret(ctx, userID, secretEncrypted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecret", reflect.TypeOf((*MockUser2FARepository)(nil).UpdateSecret), ctx, userID, secretEncrypted)
}
