// Code generated by MockGen. DO NOT EDIT.
// Source: Goshop/domain/repository/auth_repository (interfaces: RefreshSessionRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/auth_repository/mock_refresh_session_repository.go -package=auth_repository . RefreshSessionRepository
//

// Package auth_repository is a generated GoMock package.
package auth_repository

import (
	authentity "Goshop/domain/auth_entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRefreshSessionRepository is a mock of RefreshSessionRepository interface.
type MockRefreshSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshSessionRepositoryMockRecorder is the mock recorder for MockRefreshSessionRepository.
type MockRefreshSessionRepositoryMockRecorder struct {
	mock *MockRefreshSessionRepository
}

// NewMockRefreshSessionRepository creates a new mock instance.
func NewMockRefreshSessionRepository(ctrl *gomock.Controller) *MockRefreshSessionRepository {
	mock := &MockRefreshSessionRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshSessionRepository) EXPECT() *MockRefreshSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefreshSessionRepository) Create(session *authentity.RefreshSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefreshSessionRepositoryMockRecorder) Create(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshSessionRepository)(nil).Create), session)
}

// FindByID mocks base method.
func (m *MockRefreshSessionRepository) FindByID(id string) (*authentity.RefreshSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*authentity.RefreshSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRefreshSessionRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRefreshSessionRepository)(nil).FindByID), id)
}

// Revoke mocks base method.
func (m *MockRefreshSessionRepository) Revoke(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockRefreshSessionRepositoryMockRecorder) Revoke(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockRefreshSessionRepository)(nil).Revoke), id)
}
